/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'

import type {
  CancelledReservationsList200,
  CancelledReservationsList400,
  CancelledReservationsList401,
  CancelledReservationsList403,
  CancelledReservationsList422,
  CancelledReservationsList500,
  CancelledReservationsListParams,
  CancelledReservationsOverview200,
  CancelledReservationsOverview400,
  CancelledReservationsOverview401,
  CancelledReservationsOverview403,
  CancelledReservationsOverview422,
  CancelledReservationsOverview500,
  CancelledReservationsOverviewParams,
  WeeklyComplianceDetails200,
  WeeklyComplianceDetails400,
  WeeklyComplianceDetails401,
  WeeklyComplianceDetails403,
  WeeklyComplianceDetails422,
  WeeklyComplianceDetails500,
  WeeklyComplianceDetailsParams,
  WeeklyComplianceOverview200,
  WeeklyComplianceOverview400,
  WeeklyComplianceOverview401,
  WeeklyComplianceOverview403,
  WeeklyComplianceOverview500,
} from '../bBZAppBackendAPI.schemas'

import { customFetch } from '../../mutator/custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Este endpoint retorna o status de compliance de reservas semanais do usuário autenticado.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Qualquer usuário autenticado pode consultar.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Regra de negócio**:
- Colaboradores (manager, assistant_manager, assistant) devem fazer reservas da próxima semana até quinta-feira
- Gerentes: 2 dias/semana
- Subgerentes e Assistentes: 3 dias/semana
- Supervisores e Diretores: Visualizam resumo da equipe/geral
- Apenas workstations contam para compliance (não salas)

**Retorno baseado no cargo**:
- **Colaborador**: Status individual (dias obrigatórios, reservados, faltantes)
- **Supervisor**: Resumo da equipe (total de membros, compliant, não-compliant)
- **Diretor**: Resumo geral de todos os colaboradores

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Buscar overview de compliance de reservas semanais
 */
export type weeklyComplianceOverviewResponse200 = {
  data: WeeklyComplianceOverview200
  status: 200
}

export type weeklyComplianceOverviewResponse400 = {
  data: WeeklyComplianceOverview400
  status: 400
}

export type weeklyComplianceOverviewResponse401 = {
  data: WeeklyComplianceOverview401
  status: 401
}

export type weeklyComplianceOverviewResponse403 = {
  data: WeeklyComplianceOverview403
  status: 403
}

export type weeklyComplianceOverviewResponse500 = {
  data: WeeklyComplianceOverview500
  status: 500
}

export type weeklyComplianceOverviewResponseSuccess =
  weeklyComplianceOverviewResponse200 & {
    headers: Headers
  }
export type weeklyComplianceOverviewResponseError = (
  | weeklyComplianceOverviewResponse400
  | weeklyComplianceOverviewResponse401
  | weeklyComplianceOverviewResponse403
  | weeklyComplianceOverviewResponse500
) & {
  headers: Headers
}

export const getWeeklyComplianceOverviewUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/weekly-compliance/overview`
}

export const weeklyComplianceOverview = async (
  options?: RequestInit,
): Promise<weeklyComplianceOverviewResponseSuccess> => {
  return customFetch<weeklyComplianceOverviewResponseSuccess>(
    getWeeklyComplianceOverviewUrl(),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getWeeklyComplianceOverviewKey = () =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/weekly-compliance/overview`,
  ] as const

export type WeeklyComplianceOverviewQueryResult = NonNullable<
  Awaited<ReturnType<typeof weeklyComplianceOverview>>
>
export type WeeklyComplianceOverviewQueryError =
  | WeeklyComplianceOverview400
  | WeeklyComplianceOverview401
  | WeeklyComplianceOverview403
  | WeeklyComplianceOverview500

/**
 * @summary Buscar overview de compliance de reservas semanais
 */
export const useWeeklyComplianceOverview = <
  TError =
    | WeeklyComplianceOverview400
    | WeeklyComplianceOverview401
    | WeeklyComplianceOverview403
    | WeeklyComplianceOverview500,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof weeklyComplianceOverview>>,
    TError
  > & { swrKey?: Key; enabled?: boolean }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getWeeklyComplianceOverviewKey() : null))
  const swrFn = () => weeklyComplianceOverview(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint retorna a lista detalhada de colaboradores com status de compliance de reservas semanais.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Apenas supervisores e diretores podem acessar.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Regra de negócio**:
- Colaboradores (manager, assistant_manager, assistant) devem fazer reservas da próxima semana até quinta-feira
- Gerentes: 2 dias/semana
- Subgerentes e Assistentes: 3 dias/semana
- Apenas workstations contam para compliance (não salas)

**Retorno baseado no cargo**:
- **Supervisor**: Lista membros da sua equipe com status de compliance
- **Diretor**: Lista todos os colaboradores com status de compliance
- Outros cargos recebem erro 403 (Forbidden)

**Query params**:
- `page`: Número da página (padrão: 1)
- `pageSize`: Registros por página (padrão: 20)
- `onlyNonCompliant`: Se true, retorna apenas não-compliant (padrão: false)
- `week`: Qual semana consultar: "next" para próxima semana (padrão), "current" para semana vigente
- `supervisorName`: Filtrar por nome do supervisor (busca parcial)
- `userName`: Filtrar por nome do colaborador (busca parcial)
- `position`: Filtrar por cargo (manager, assistant_manager, assistant)

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Buscar detalhes de compliance de reservas semanais
 */
export type weeklyComplianceDetailsResponse200 = {
  data: WeeklyComplianceDetails200
  status: 200
}

export type weeklyComplianceDetailsResponse400 = {
  data: WeeklyComplianceDetails400
  status: 400
}

export type weeklyComplianceDetailsResponse401 = {
  data: WeeklyComplianceDetails401
  status: 401
}

export type weeklyComplianceDetailsResponse403 = {
  data: WeeklyComplianceDetails403
  status: 403
}

export type weeklyComplianceDetailsResponse422 = {
  data: WeeklyComplianceDetails422
  status: 422
}

export type weeklyComplianceDetailsResponse500 = {
  data: WeeklyComplianceDetails500
  status: 500
}

export type weeklyComplianceDetailsResponseSuccess =
  weeklyComplianceDetailsResponse200 & {
    headers: Headers
  }
export type weeklyComplianceDetailsResponseError = (
  | weeklyComplianceDetailsResponse400
  | weeklyComplianceDetailsResponse401
  | weeklyComplianceDetailsResponse403
  | weeklyComplianceDetailsResponse422
  | weeklyComplianceDetailsResponse500
) & {
  headers: Headers
}

export const getWeeklyComplianceDetailsUrl = (
  params?: WeeklyComplianceDetailsParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/weekly-compliance/details?${stringifiedParams}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/weekly-compliance/details`
}

export const weeklyComplianceDetails = async (
  params?: WeeklyComplianceDetailsParams,
  options?: RequestInit,
): Promise<weeklyComplianceDetailsResponseSuccess> => {
  return customFetch<weeklyComplianceDetailsResponseSuccess>(
    getWeeklyComplianceDetailsUrl(params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getWeeklyComplianceDetailsKey = (
  params?: WeeklyComplianceDetailsParams,
) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/weekly-compliance/details`,
    ...(params ? [params] : []),
  ] as const

export type WeeklyComplianceDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof weeklyComplianceDetails>>
>
export type WeeklyComplianceDetailsQueryError =
  | WeeklyComplianceDetails400
  | WeeklyComplianceDetails401
  | WeeklyComplianceDetails403
  | WeeklyComplianceDetails422
  | WeeklyComplianceDetails500

/**
 * @summary Buscar detalhes de compliance de reservas semanais
 */
export const useWeeklyComplianceDetails = <
  TError =
    | WeeklyComplianceDetails400
    | WeeklyComplianceDetails401
    | WeeklyComplianceDetails403
    | WeeklyComplianceDetails422
    | WeeklyComplianceDetails500,
>(
  params?: WeeklyComplianceDetailsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof weeklyComplianceDetails>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getWeeklyComplianceDetailsKey(params) : null))
  const swrFn = () => weeklyComplianceDetails(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint retorna um resumo de cancelamentos de reservas de workstation efetuados após o prazo de planejamento.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Apenas supervisores e diretores podem acessar.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Regra de negócio**:
- Colaboradores devem planejar reservas de workstation até quinta-feira da semana anterior
- Cancelamentos feitos após esse prazo são contabilizados neste indicador
- Supervisores: visualizam apenas cancelamentos da sua equipe
- Diretores: visualizam todos os cancelamentos

**Parâmetros opcionais**:
- `startDate`: Data inicial do período (default: início do mês atual)
- `endDate`: Data final do período (default: momento atual)

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Buscar overview de cancelamentos de reservas após o prazo
 */
export type cancelledReservationsOverviewResponse200 = {
  data: CancelledReservationsOverview200
  status: 200
}

export type cancelledReservationsOverviewResponse400 = {
  data: CancelledReservationsOverview400
  status: 400
}

export type cancelledReservationsOverviewResponse401 = {
  data: CancelledReservationsOverview401
  status: 401
}

export type cancelledReservationsOverviewResponse403 = {
  data: CancelledReservationsOverview403
  status: 403
}

export type cancelledReservationsOverviewResponse422 = {
  data: CancelledReservationsOverview422
  status: 422
}

export type cancelledReservationsOverviewResponse500 = {
  data: CancelledReservationsOverview500
  status: 500
}

export type cancelledReservationsOverviewResponseSuccess =
  cancelledReservationsOverviewResponse200 & {
    headers: Headers
  }
export type cancelledReservationsOverviewResponseError = (
  | cancelledReservationsOverviewResponse400
  | cancelledReservationsOverviewResponse401
  | cancelledReservationsOverviewResponse403
  | cancelledReservationsOverviewResponse422
  | cancelledReservationsOverviewResponse500
) & {
  headers: Headers
}

export const getCancelledReservationsOverviewUrl = (
  params?: CancelledReservationsOverviewParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/cancelled/overview?${stringifiedParams}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/cancelled/overview`
}

export const cancelledReservationsOverview = async (
  params?: CancelledReservationsOverviewParams,
  options?: RequestInit,
): Promise<cancelledReservationsOverviewResponseSuccess> => {
  return customFetch<cancelledReservationsOverviewResponseSuccess>(
    getCancelledReservationsOverviewUrl(params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getCancelledReservationsOverviewKey = (
  params?: CancelledReservationsOverviewParams,
) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/cancelled/overview`,
    ...(params ? [params] : []),
  ] as const

export type CancelledReservationsOverviewQueryResult = NonNullable<
  Awaited<ReturnType<typeof cancelledReservationsOverview>>
>
export type CancelledReservationsOverviewQueryError =
  | CancelledReservationsOverview400
  | CancelledReservationsOverview401
  | CancelledReservationsOverview403
  | CancelledReservationsOverview422
  | CancelledReservationsOverview500

/**
 * @summary Buscar overview de cancelamentos de reservas após o prazo
 */
export const useCancelledReservationsOverview = <
  TError =
    | CancelledReservationsOverview400
    | CancelledReservationsOverview401
    | CancelledReservationsOverview403
    | CancelledReservationsOverview422
    | CancelledReservationsOverview500,
>(
  params?: CancelledReservationsOverviewParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof cancelledReservationsOverview>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getCancelledReservationsOverviewKey(params) : null))
  const swrFn = () => cancelledReservationsOverview(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint retorna uma lista paginada de cancelamentos de reservas de workstation efetuados após o prazo de planejamento.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Apenas supervisores e diretores podem acessar.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Regra de negócio**:
- Colaboradores devem planejar reservas de workstation até quinta-feira da semana anterior
- Cancelamentos feitos após esse prazo são listados neste endpoint
- Supervisores: visualizam apenas cancelamentos da sua equipe
- Diretores: visualizam todos os cancelamentos

**Parâmetros opcionais**:
- `page`: Número da página (default: 1)
- `pageSize`: Itens por página (default: 10, max: 100)
- `startDate`: Data inicial do período (default: início do mês atual)
- `endDate`: Data final do período (default: momento atual)
- `userName`: Filtro por nome do colaborador
- `supervisorName`: Filtro por nome do supervisor
- `position`: Filtro por cargo (manager, assistant_manager, assistant)

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Listar cancelamentos de reservas após o prazo de planejamento
 */
export type cancelledReservationsListResponse200 = {
  data: CancelledReservationsList200
  status: 200
}

export type cancelledReservationsListResponse400 = {
  data: CancelledReservationsList400
  status: 400
}

export type cancelledReservationsListResponse401 = {
  data: CancelledReservationsList401
  status: 401
}

export type cancelledReservationsListResponse403 = {
  data: CancelledReservationsList403
  status: 403
}

export type cancelledReservationsListResponse422 = {
  data: CancelledReservationsList422
  status: 422
}

export type cancelledReservationsListResponse500 = {
  data: CancelledReservationsList500
  status: 500
}

export type cancelledReservationsListResponseSuccess =
  cancelledReservationsListResponse200 & {
    headers: Headers
  }
export type cancelledReservationsListResponseError = (
  | cancelledReservationsListResponse400
  | cancelledReservationsListResponse401
  | cancelledReservationsListResponse403
  | cancelledReservationsListResponse422
  | cancelledReservationsListResponse500
) & {
  headers: Headers
}

export const getCancelledReservationsListUrl = (
  params?: CancelledReservationsListParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/cancelled/list?${stringifiedParams}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/cancelled/list`
}

export const cancelledReservationsList = async (
  params?: CancelledReservationsListParams,
  options?: RequestInit,
): Promise<cancelledReservationsListResponseSuccess> => {
  return customFetch<cancelledReservationsListResponseSuccess>(
    getCancelledReservationsListUrl(params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getCancelledReservationsListKey = (
  params?: CancelledReservationsListParams,
) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservations/cancelled/list`,
    ...(params ? [params] : []),
  ] as const

export type CancelledReservationsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof cancelledReservationsList>>
>
export type CancelledReservationsListQueryError =
  | CancelledReservationsList400
  | CancelledReservationsList401
  | CancelledReservationsList403
  | CancelledReservationsList422
  | CancelledReservationsList500

/**
 * @summary Listar cancelamentos de reservas após o prazo de planejamento
 */
export const useCancelledReservationsList = <
  TError =
    | CancelledReservationsList400
    | CancelledReservationsList401
    | CancelledReservationsList403
    | CancelledReservationsList422
    | CancelledReservationsList500,
>(
  params?: CancelledReservationsListParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof cancelledReservationsList>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getCancelledReservationsListKey(params) : null))
  const swrFn = () => cancelledReservationsList(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
