/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'
import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  CreateRoomSlotPreReserve201,
  CreateRoomSlotPreReserve400,
  CreateRoomSlotPreReserve401,
  CreateRoomSlotPreReserve403,
  CreateRoomSlotPreReserve404,
  CreateRoomSlotPreReserve409,
  CreateRoomSlotPreReserve422,
  CreateRoomSlotPreReserve500,
  CreateRoomSlotPreReserveBody,
  DeleteRoomSlotPreReserve200,
  DeleteRoomSlotPreReserve400,
  DeleteRoomSlotPreReserve401,
  DeleteRoomSlotPreReserve403,
  DeleteRoomSlotPreReserve404,
  DeleteRoomSlotPreReserve422,
  DeleteRoomSlotPreReserve500,
  GetRoomSlotAvailability200,
  GetRoomSlotAvailability400,
  GetRoomSlotAvailability401,
  GetRoomSlotAvailability403,
  GetRoomSlotAvailability404,
  GetRoomSlotAvailability422,
  GetRoomSlotAvailability500,
  GetRoomSlotAvailabilityParams,
  ListRoomSlots200,
  ListRoomSlots400,
  ListRoomSlots401,
  ListRoomSlots403,
  ListRoomSlots422,
  ListRoomSlots500,
  ListRoomSlotsParams,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Este endpoint permite listar salas disponíveis para uma data e, opcionalmente, um horário específico, com suporte a paginação.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Regras de busca**:
  1. Quando a data é fornecida com hora zerada (00:00:00), retorna salas com pelo menos um horário livre entre 07:00 e 20:00
  2. Quando data e hora específica são fornecidos, retorna salas disponíveis nesse horário específico
  3. Apenas salas ativas (is_active = true) são consideradas
  4. Salas pré-reservadas ou reservadas para o horário solicitado são excluídas dos resultados

* **Parâmetros**:
  - datetime (obrigatório): String ISO com timezone para data/hora
  - page (opcional): Número da página para paginação, começando em 1 (padrão: 1)
  - pageSize (opcional): Quantidade de resultados por página, entre 1 e 100 (padrão: 12)

* **Exemplo de uso**:
  - Consulta por data: `GET /v1/private/room-slot/list?datetime=2025-05-22T00:00:00-03:00`
  - Consulta por horário específico: `GET /v1/private/room-slot/list?datetime=2025-05-22T14:30:00-03:00`
  - Com paginação: `GET /v1/private/room-slot/list?datetime=2025-05-22T00:00:00-03:00&page=2&pageSize=10`

* **Formato da resposta**:
  - rooms: Array de objetos representando as salas disponíveis com suas propriedades
  - totalCount: Número total de salas disponíveis
  - totalPages: Número total de páginas disponíveis
  - currentPage: Página atual sendo exibida
  - message: Mensagem de sucesso ou informação adicional

* **Notas**:
  - O parâmetro datetime deve ser uma string ISO com timezone (exemplo: "2025-05-22T00:00:00-03:00")
  - Se a hora for 00:00:00, o sistema busca salas com pelo menos um horário livre no dia
  - Se a hora for diferente de 00:00:00 (ex: 14:30:00), o sistema busca salas livres especificamente nesse horário
  - A duração padrão de cada slot é de 1 hora
  - A capacidade máxima de uma sala pode afetar sua disponibilidade
 * @summary Listar salas disponíveis por data ou horário específico
 */
export type listRoomSlotsResponse = {
  data: ListRoomSlots200
  status: number
  headers: Headers
}

export const getListRoomSlotsUrl = (params: ListRoomSlotsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/list?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/list`
}

export const listRoomSlots = async (
  params: ListRoomSlotsParams,
  options?: RequestInit,
): Promise<listRoomSlotsResponse> => {
  return customFetch<Promise<listRoomSlotsResponse>>(
    getListRoomSlotsUrl(params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getListRoomSlotsKey = (params: ListRoomSlotsParams) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/list`,
    ...(params ? [params] : []),
  ] as const

export type ListRoomSlotsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listRoomSlots>>
>
export type ListRoomSlotsQueryError =
  | ListRoomSlots400
  | ListRoomSlots401
  | ListRoomSlots403
  | ListRoomSlots422
  | ListRoomSlots500

/**
 * @summary Listar salas disponíveis por data ou horário específico
 */
export const useListRoomSlots = <
  TError =
    | ListRoomSlots400
    | ListRoomSlots401
    | ListRoomSlots403
    | ListRoomSlots422
    | ListRoomSlots500,
>(
  params: ListRoomSlotsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof listRoomSlots>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getListRoomSlotsKey(params) : null))
  const swrFn = () => listRoomSlots(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite obter informações detalhadas sobre a disponibilidade de uma sala específica em um intervalo de datas, incluindo slots reservados e pré-reservados.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Funcionalidade**:
  1. Busca detalhes completos da sala solicitada (nome, descrição, recursos, etc.)
  2. Retorna todos os slots já reservados ou pré-reservados para a sala no período solicitado
  3. Para cada slot, fornece informações do usuário que fez a pré-reserva (se houver)
  4. Permite visualização do status de cada horário ('reserved' ou 'pre_reserved')
  5. Verifica automaticamente se a sala existe e está ativa antes de retornar resultados
  6. Limita a consulta a um período máximo de 7 dias entre a data inicial e final

* **Parâmetros**:
  - roomId (obrigatório, path): Identificador UUID da sala
  - startDate (obrigatório, query): Data inicial do período no formato YYYY-MM-DD (ex: 2023-08-15)
  - endDate (obrigatório, query): Data final do período no formato YYYY-MM-DD (ex: 2023-08-20) (período máximo de 7 dias)

* **Exemplo de uso**:
  - Requisição básica: `GET /v1/private/room-slot/a1b2c3d4-e5f6-7890-abcd-1234567890ab/availability?startDate=2023-08-15&endDate=2023-08-20`
  - Buscar slots para um dia: `GET /v1/private/room-slot/a1b2c3d4-e5f6-7890-abcd-1234567890ab/availability?startDate=2023-08-15&endDate=2023-08-15`

* **Formato da resposta**:
  - room: Objeto contendo todas as informações da sala solicitada (id, nome, recursos, capacidade, etc.)
  - slots: Array de objetos representando os horários reservados ou pré-reservados no período, com:
    - id: Identificador do slot
    - date: Data do slot no formato YYYY-MM-DD
    - time: Horário do slot no formato HH:MM (24h)
    - status: Estado do slot ('reserved' ou 'pre_reserved')
    - preReservedBy: Objeto com informações do usuário que fez a pré-reserva (id, nome, email)
    - preReservedUntil: Data e hora até quando o slot está pré-reservado

* **Notas**:
  - O formato das datas deve ser estritamente YYYY-MM-DD (ano-mês-dia)
  - A data inicial não pode ser posterior à data final
  - A resposta inclui apenas slots que já existem (reservados ou pré-reservados)
  - Um slot com status 'pre_reserved' pode se tornar disponível novamente após o tempo de pré-reserva expirar
  - Apenas salas ativas podem ser consultadas neste endpoint
 * @summary Visualizar disponibilidade detalhada de uma sala específica em um período
 */
export type getRoomSlotAvailabilityResponse = {
  data: GetRoomSlotAvailability200
  status: number
  headers: Headers
}

export const getGetRoomSlotAvailabilityUrl = (
  roomId: string,
  params: GetRoomSlotAvailabilityParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/${roomId}/availability?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/${roomId}/availability`
}

export const getRoomSlotAvailability = async (
  roomId: string,
  params: GetRoomSlotAvailabilityParams,
  options?: RequestInit,
): Promise<getRoomSlotAvailabilityResponse> => {
  return customFetch<Promise<getRoomSlotAvailabilityResponse>>(
    getGetRoomSlotAvailabilityUrl(roomId, params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getGetRoomSlotAvailabilityKey = (
  roomId: string,
  params: GetRoomSlotAvailabilityParams,
) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/${roomId}/availability`,
    ...(params ? [params] : []),
  ] as const

export type GetRoomSlotAvailabilityQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRoomSlotAvailability>>
>
export type GetRoomSlotAvailabilityQueryError =
  | GetRoomSlotAvailability400
  | GetRoomSlotAvailability401
  | GetRoomSlotAvailability403
  | GetRoomSlotAvailability404
  | GetRoomSlotAvailability422
  | GetRoomSlotAvailability500

/**
 * @summary Visualizar disponibilidade detalhada de uma sala específica em um período
 */
export const useGetRoomSlotAvailability = <
  TError =
    | GetRoomSlotAvailability400
    | GetRoomSlotAvailability401
    | GetRoomSlotAvailability403
    | GetRoomSlotAvailability404
    | GetRoomSlotAvailability422
    | GetRoomSlotAvailability500,
>(
  roomId: string,
  params: GetRoomSlotAvailabilityParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof getRoomSlotAvailability>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!roomId
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetRoomSlotAvailabilityKey(roomId, params) : null))
  const swrFn = () => getRoomSlotAvailability(roomId, params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite que um usuário crie uma pré-reserva de um slot (horário) em uma sala específica.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Funcionalidade**:
  1. Cria uma pré-reserva para um slot (combinação de sala e horário específico)
  2. Define o status como 'pre_reserved'
  3. Associa o usuário atual à pré-reserva
  4. Define um tempo limite de 5 minutos para confirmação da reserva
  5. Verifica automaticamente se a sala existe e está ativa
  6. Impede pré-reservas de slots já reservados ou pré-reservados
  7. Impede pré-reservas para datas passadas

* **Fluxo de reserva**:
  1. O usuário faz uma pré-reserva (este endpoint)
  2. O sistema reserva o slot por 5 minutos para o usuário
  3. O usuário deve confirmar a reserva em até 5 minutos
  4. Caso contrário, o slot fica disponível novamente após o tempo limite

* **Parâmetros no corpo**:
  - roomId (obrigatório): Identificador UUID da sala
  - slotStart (obrigatório): Data e hora de início no formato ISO com timezone (ex: 2023-08-15T14:30:00-03:00)
  - slotEnd (obrigatório): Data e hora de término no formato ISO com timezone (ex: 2023-08-15T15:30:00-03:00)
  - status (opcional): Status da reserva, padrão 'pre_reserved'

* **Exemplo de uso**:
  - Requisição básica: `POST /v1/private/room-slot/pre-reserve` com body:
  ```json
  {
    "roomId": "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
    "slotStart": "2023-08-15T14:30:00-03:00",
    "slotEnd": "2023-08-15T15:30:00-03:00"
  }
  ```

* **Formato da resposta**:
  - slot: Objeto com todas as informações do slot pré-reservado
  - message: Mensagem informativa de sucesso

* **Notas**:
  - As datas devem estar no formato ISO com informação de timezone
  - O slot reservado tem duração de 1 hora (entre slotStart e slotEnd)
  - Uma pré-reserva expira automaticamente após 5 minutos se não for confirmada
  - Um usuário não pode pré-reservar um slot já reservado ou pré-reservado
  - Não é possível pré-reservar slots para datas passadas
  - O ID do usuário que faz a pré-reserva é automaticamente capturado do token JWT
 * @summary Criar pré-reserva de slot em uma sala
 */
export type createRoomSlotPreReserveResponse = {
  data: CreateRoomSlotPreReserve201
  status: number
  headers: Headers
}

export const getCreateRoomSlotPreReserveUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/pre-reserve`
}

export const createRoomSlotPreReserve = async (
  createRoomSlotPreReserveBody: CreateRoomSlotPreReserveBody,
  options?: RequestInit,
): Promise<createRoomSlotPreReserveResponse> => {
  return customFetch<Promise<createRoomSlotPreReserveResponse>>(
    getCreateRoomSlotPreReserveUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createRoomSlotPreReserveBody),
    },
  )
}

export const getCreateRoomSlotPreReserveMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: CreateRoomSlotPreReserveBody },
  ): Promise<createRoomSlotPreReserveResponse> => {
    return createRoomSlotPreReserve(arg, options)
  }
}
export const getCreateRoomSlotPreReserveMutationKey = () =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/pre-reserve`,
  ] as const

export type CreateRoomSlotPreReserveMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRoomSlotPreReserve>>
>
export type CreateRoomSlotPreReserveMutationError =
  | CreateRoomSlotPreReserve400
  | CreateRoomSlotPreReserve401
  | CreateRoomSlotPreReserve403
  | CreateRoomSlotPreReserve404
  | CreateRoomSlotPreReserve409
  | CreateRoomSlotPreReserve422
  | CreateRoomSlotPreReserve500

/**
 * @summary Criar pré-reserva de slot em uma sala
 */
export const useCreateRoomSlotPreReserve = <
  TError =
    | CreateRoomSlotPreReserve400
    | CreateRoomSlotPreReserve401
    | CreateRoomSlotPreReserve403
    | CreateRoomSlotPreReserve404
    | CreateRoomSlotPreReserve409
    | CreateRoomSlotPreReserve422
    | CreateRoomSlotPreReserve500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createRoomSlotPreReserve>>,
    TError,
    Key,
    CreateRoomSlotPreReserveBody,
    Awaited<ReturnType<typeof createRoomSlotPreReserve>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateRoomSlotPreReserveMutationKey()
  const swrFn = getCreateRoomSlotPreReserveMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite que um usuário delete uma pré-reserva de um slot (horário) em uma sala específica.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a qualquer usuário autenticado, com verificação de propriedade ou privilégio administrativo.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Funcionalidade**:
  1. Deleta uma pré-reserva existente para um slot (horário em uma sala)
  2. Remove completamente o registro do slot do banco de dados
  3. Libera o horário para que outros usuários possam reservá-lo
  4. Apenas o usuário que fez a pré-reserva ou administradores podem deletá-la

* **Fluxo de deleção**:
  1. O usuário solicita a deleção de uma pré-reserva específica através do ID do slot
  2. O sistema extrai automaticamente o ID e perfil do usuário do token JWT
  3. O sistema verifica se o slot existe e está no estado 'pre_reserved'
  4. O sistema verifica se o usuário tem permissão para deletar (é o dono da reserva ou tem perfil admin/dev)
  5. O sistema remove o registro da pré-reserva e libera o horário

* **Parâmetros na rota**:
  - slotId (obrigatório): Identificador UUID do slot pré-reservado

* **Exemplo de uso**:
  - Requisição básica: `DELETE /v1/private/room-slot/a1b2c3d4-e5f6-7890-abcd-1234567890ab/pre-reserve`

* **Formato da resposta**:
  - message: Mensagem informativa de sucesso
  - deletedSlotId: UUID do slot que foi deletado

* **Notas**:
  - A deleção é definitiva e não pode ser desfeita
  - Apenas o proprietário da pré-reserva ou usuários com perfil 'admin' ou 'dev' podem deletar
  - Caso o slot já tenha sido completamente reservado (status 'reserved'), este endpoint não funcionará
  - Caso o slot não exista ou já tenha sido deletado, retorna erro 404 (não encontrado)
  - A operação é idempotente (chamar duas vezes não causa erro, mas retorna 404 na segunda vez)
 * @summary Deletar pré-reserva de slot em uma sala
 */
export type deleteRoomSlotPreReserveResponse = {
  data: DeleteRoomSlotPreReserve200
  status: number
  headers: Headers
}

export const getDeleteRoomSlotPreReserveUrl = (slotId: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/${slotId}/pre-reserve`
}

export const deleteRoomSlotPreReserve = async (
  slotId: string,
  options?: RequestInit,
): Promise<deleteRoomSlotPreReserveResponse> => {
  return customFetch<Promise<deleteRoomSlotPreReserveResponse>>(
    getDeleteRoomSlotPreReserveUrl(slotId),
    {
      ...options,
      method: 'DELETE',
    },
  )
}

export const getDeleteRoomSlotPreReserveMutationFetcher = (
  slotId: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    __: { arg: Arguments },
  ): Promise<deleteRoomSlotPreReserveResponse> => {
    return deleteRoomSlotPreReserve(slotId, options)
  }
}
export const getDeleteRoomSlotPreReserveMutationKey = (slotId: string) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/${slotId}/pre-reserve`,
  ] as const

export type DeleteRoomSlotPreReserveMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRoomSlotPreReserve>>
>
export type DeleteRoomSlotPreReserveMutationError =
  | DeleteRoomSlotPreReserve400
  | DeleteRoomSlotPreReserve401
  | DeleteRoomSlotPreReserve403
  | DeleteRoomSlotPreReserve404
  | DeleteRoomSlotPreReserve422
  | DeleteRoomSlotPreReserve500

/**
 * @summary Deletar pré-reserva de slot em uma sala
 */
export const useDeleteRoomSlotPreReserve = <
  TError =
    | DeleteRoomSlotPreReserve400
    | DeleteRoomSlotPreReserve401
    | DeleteRoomSlotPreReserve403
    | DeleteRoomSlotPreReserve404
    | DeleteRoomSlotPreReserve422
    | DeleteRoomSlotPreReserve500,
>(
  slotId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteRoomSlotPreReserve>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteRoomSlotPreReserve>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey =
    swrOptions?.swrKey ?? getDeleteRoomSlotPreReserveMutationKey(slotId)
  const swrFn = getDeleteRoomSlotPreReserveMutationFetcher(
    slotId,
    requestOptions,
  )

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
