/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  ListRoomSlots200,
  ListRoomSlots400,
  ListRoomSlots401,
  ListRoomSlots403,
  ListRoomSlots422,
  ListRoomSlots500,
  ListRoomSlotsParams,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Este endpoint permite listar salas disponíveis para uma data e, opcionalmente, um horário específico, com suporte a paginação.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Regras de busca**:
  1. Quando apenas a data é fornecida, retorna salas com pelo menos um horário livre entre 07:00 e 20:00
  2. Quando data e hora são fornecidos, retorna salas disponíveis nesse horário específico
  3. Apenas salas ativas (is_active = true) são consideradas
  4. Salas pré-reservadas ou reservadas para o horário solicitado são excluídas dos resultados

* **Parâmetros**:
  - date (obrigatório): Data no formato YYYY-MM-DD (ex: 2023-08-15)
  - hour (opcional): Hora no formato HH:MM (ex: 14:30)
  - page (opcional): Número da página para paginação, começando em 1 (padrão: 1)
  - pageSize (opcional): Quantidade de resultados por página, entre 1 e 100 (padrão: 12)

* **Exemplo de uso**:
  - Requisição básica: `GET /v1/private/room-slot/list?date=2023-08-15`
  - Com hora específica: `GET /v1/private/room-slot/list?date=2023-08-15&hour=14:30`
  - Com paginação: `GET /v1/private/room-slot/list?date=2023-08-15&page=2&pageSize=10`

* **Formato da resposta**:
  - rooms: Array de objetos representando as salas disponíveis com suas propriedades
  - totalCount: Número total de salas disponíveis
  - totalPages: Número total de páginas disponíveis
  - currentPage: Página atual sendo exibida
  - message: Mensagem de sucesso ou informação adicional

* **Notas**:
  - O formato da data deve ser estritamente YYYY-MM-DD (ano-mês-dia)
  - O formato da hora deve ser estritamente HH:MM (hora:minuto) no formato 24h
  - O sistema valida automaticamente se a data e hora são válidas
  - A capacidade máxima de uma sala pode afetar sua disponibilidade
 * @summary Listar salas disponíveis por data e hora
 */
export type listRoomSlotsResponse = {
  data: ListRoomSlots200
  status: number
  headers: Headers
}

export const getListRoomSlotsUrl = (params: ListRoomSlotsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/list?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/list`
}

export const listRoomSlots = async (
  params: ListRoomSlotsParams,
  options?: RequestInit,
): Promise<listRoomSlotsResponse> => {
  return customFetch<Promise<listRoomSlotsResponse>>(
    getListRoomSlotsUrl(params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getListRoomSlotsKey = (params: ListRoomSlotsParams) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room-slot/list`,
    ...(params ? [params] : []),
  ] as const

export type ListRoomSlotsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listRoomSlots>>
>
export type ListRoomSlotsQueryError =
  | ListRoomSlots400
  | ListRoomSlots401
  | ListRoomSlots403
  | ListRoomSlots422
  | ListRoomSlots500

/**
 * @summary Listar salas disponíveis por data e hora
 */
export const useListRoomSlots = <
  TError =
    | ListRoomSlots400
    | ListRoomSlots401
    | ListRoomSlots403
    | ListRoomSlots422
    | ListRoomSlots500,
>(
  params: ListRoomSlotsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof listRoomSlots>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getListRoomSlotsKey(params) : null))
  const swrFn = () => listRoomSlots(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
