/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'
import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  JustifyEarlyCheckoutOccurrence200,
  JustifyEarlyCheckoutOccurrence400,
  JustifyEarlyCheckoutOccurrence401,
  JustifyEarlyCheckoutOccurrence403,
  JustifyEarlyCheckoutOccurrence404,
  JustifyEarlyCheckoutOccurrence422,
  JustifyEarlyCheckoutOccurrence500,
  JustifyEarlyCheckoutOccurrenceBody,
  ListEarlyCheckoutOccurrences200,
  ListEarlyCheckoutOccurrences400,
  ListEarlyCheckoutOccurrences401,
  ListEarlyCheckoutOccurrences403,
  ListEarlyCheckoutOccurrences422,
  ListEarlyCheckoutOccurrences500,
  ListEarlyCheckoutOccurrencesParams,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Este endpoint retorna a lista de ocorrências de checkout antecipado em workstations.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Baseada na role do sistema E na position do team:
  - Admin/Dev (roles do sistema) → podem ver todas as ocorrências
  - Director (position no team) → pode ver todas as ocorrências
  - Supervisor (position no team) → pode ver apenas ocorrências da sua equipe
  - Demais usuários → não têm acesso
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Regras de negócio**:
- Sempre busca da pendência mais antiga até hoje (sem filtro de data)
- Retorna indicadores totalizadores (total, pendentes, justificadas, desconsideradas)
- Retorna período consultado (data mais antiga de pendência até hoje)
- Lista paginada de ocorrências com dados do colaborador e supervisor

**Filtros disponíveis**:
- `status`: 'pending', 'justified', 'dismissed', 'all'
- `supervisorName`: Busca parcial por nome do supervisor
- `userName`: Busca parcial por nome do colaborador
- `userEmail`: Busca parcial por email do colaborador
- `position`: 'manager', 'assistant_manager', 'assistant'

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Listar ocorrências de checkout antecipado
 */
export type listEarlyCheckoutOccurrencesResponse = {
  data: ListEarlyCheckoutOccurrences200
  status: number
  headers: Headers
}

export const getListEarlyCheckoutOccurrencesUrl = (
  params?: ListEarlyCheckoutOccurrencesParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/occurrences/early-checkout?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/occurrences/early-checkout`
}

export const listEarlyCheckoutOccurrences = async (
  params?: ListEarlyCheckoutOccurrencesParams,
  options?: RequestInit,
): Promise<listEarlyCheckoutOccurrencesResponse> => {
  return customFetch<Promise<listEarlyCheckoutOccurrencesResponse>>(
    getListEarlyCheckoutOccurrencesUrl(params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getListEarlyCheckoutOccurrencesKey = (
  params?: ListEarlyCheckoutOccurrencesParams,
) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/occurrences/early-checkout`,
    ...(params ? [params] : []),
  ] as const

export type ListEarlyCheckoutOccurrencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listEarlyCheckoutOccurrences>>
>
export type ListEarlyCheckoutOccurrencesQueryError =
  | ListEarlyCheckoutOccurrences400
  | ListEarlyCheckoutOccurrences401
  | ListEarlyCheckoutOccurrences403
  | ListEarlyCheckoutOccurrences422
  | ListEarlyCheckoutOccurrences500

/**
 * @summary Listar ocorrências de checkout antecipado
 */
export const useListEarlyCheckoutOccurrences = <
  TError =
    | ListEarlyCheckoutOccurrences400
    | ListEarlyCheckoutOccurrences401
    | ListEarlyCheckoutOccurrences403
    | ListEarlyCheckoutOccurrences422
    | ListEarlyCheckoutOccurrences500,
>(
  params?: ListEarlyCheckoutOccurrencesParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof listEarlyCheckoutOccurrences>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getListEarlyCheckoutOccurrencesKey(params) : null))
  const swrFn = () => listEarlyCheckoutOccurrences(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite justificar ou descartar uma ocorrência de checkout antecipado.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Baseada na role do sistema E na position do team:
  - Admin/Dev (roles do sistema) → podem justificar qualquer ocorrência
  - Director (position no team) → pode justificar qualquer ocorrência
  - Supervisor (position no team) → pode justificar apenas ocorrências da sua equipe
  - Demais usuários → não têm permissão
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Regras de negócio**:
- A ocorrência deve existir e estar com status 'pending'
- Quando action = 'justified', o campo justification é obrigatório (mínimo 10 caracteres)
- Quando action = 'dismissed', a justificativa é opcional

**Ações disponíveis**:
- `justified`: Justifica a ocorrência com um texto explicativo
- `dismissed`: Descarta a ocorrência (erro de registro, por exemplo)

 * @summary Justificar ou descartar ocorrência de checkout antecipado
 */
export type justifyEarlyCheckoutOccurrenceResponse = {
  data: JustifyEarlyCheckoutOccurrence200
  status: number
  headers: Headers
}

export const getJustifyEarlyCheckoutOccurrenceUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/occurrences/early-checkout/${id}/justify`
}

export const justifyEarlyCheckoutOccurrence = async (
  id: string,
  justifyEarlyCheckoutOccurrenceBody: JustifyEarlyCheckoutOccurrenceBody,
  options?: RequestInit,
): Promise<justifyEarlyCheckoutOccurrenceResponse> => {
  return customFetch<Promise<justifyEarlyCheckoutOccurrenceResponse>>(
    getJustifyEarlyCheckoutOccurrenceUrl(id),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(justifyEarlyCheckoutOccurrenceBody),
    },
  )
}

export const getJustifyEarlyCheckoutOccurrenceMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: JustifyEarlyCheckoutOccurrenceBody },
  ): Promise<justifyEarlyCheckoutOccurrenceResponse> => {
    return justifyEarlyCheckoutOccurrence(id, arg, options)
  }
}
export const getJustifyEarlyCheckoutOccurrenceMutationKey = (id: string) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/occurrences/early-checkout/${id}/justify`,
  ] as const

export type JustifyEarlyCheckoutOccurrenceMutationResult = NonNullable<
  Awaited<ReturnType<typeof justifyEarlyCheckoutOccurrence>>
>
export type JustifyEarlyCheckoutOccurrenceMutationError =
  | JustifyEarlyCheckoutOccurrence400
  | JustifyEarlyCheckoutOccurrence401
  | JustifyEarlyCheckoutOccurrence403
  | JustifyEarlyCheckoutOccurrence404
  | JustifyEarlyCheckoutOccurrence422
  | JustifyEarlyCheckoutOccurrence500

/**
 * @summary Justificar ou descartar ocorrência de checkout antecipado
 */
export const useJustifyEarlyCheckoutOccurrence = <
  TError =
    | JustifyEarlyCheckoutOccurrence400
    | JustifyEarlyCheckoutOccurrence401
    | JustifyEarlyCheckoutOccurrence403
    | JustifyEarlyCheckoutOccurrence404
    | JustifyEarlyCheckoutOccurrence422
    | JustifyEarlyCheckoutOccurrence500,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof justifyEarlyCheckoutOccurrence>>,
      TError,
      Key,
      JustifyEarlyCheckoutOccurrenceBody,
      Awaited<ReturnType<typeof justifyEarlyCheckoutOccurrence>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey =
    swrOptions?.swrKey ?? getJustifyEarlyCheckoutOccurrenceMutationKey(id)
  const swrFn = getJustifyEarlyCheckoutOccurrenceMutationFetcher(
    id,
    requestOptions,
  )

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
