/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'
import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  CreateUser201,
  CreateUser400,
  CreateUser401,
  CreateUser403,
  CreateUser409,
  CreateUser422,
  CreateUser500,
  CreateUserBody,
  DeleteUser200,
  DeleteUser400,
  DeleteUser401,
  DeleteUser403,
  DeleteUser404,
  DeleteUser409,
  DeleteUser422,
  DeleteUser500,
  GetUser200,
  GetUser400,
  GetUser401,
  GetUser403,
  GetUser404,
  GetUser422,
  GetUser500,
  ListUsers201,
  ListUsers400,
  ListUsers401,
  ListUsers403,
  ListUsers422,
  ListUsers500,
  ListUsersParams,
  UpdateUser200,
  UpdateUser400,
  UpdateUser401,
  UpdateUser403,
  UpdateUser404,
  UpdateUser409,
  UpdateUser422,
  UpdateUser500,
  UpdateUserBody,
  UserMe201,
  UserMe400,
  UserMe401,
  UserMe403,
  UserMe500,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Este endpoint recupera os dados completos do usuário atualmente autenticado.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autenticação**: Requer token JWT válido no cabeçalho de autorização.
* **Validação de conta**: Verifica se a conta do usuário está ativa e não requer reset de senha.
* **Dados retornados**:
  - Identificador único (UUID)
  - Nome completo e apelido
  - Endereço de e-mail
  - URL do avatar
  - Função no sistema (admin, user, dev)
  - Status da conta
  - Indicador de necessidade de redefinição de senha
  - Telefone
  - Status de autorização do calendário

* **Códigos de erro**:
  - 401: Token JWT inválido ou expirado
  - 403: Acesso proibido
  - 400: Requisição mal formatada
  - 500: Erro interno do servidor

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário está ativa
 * @summary Obter dados do usuário autenticado
 */
export type userMeResponse = {
  data: UserMe201
  status: number
  headers: Headers
}

export const getUserMeUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/me`
}

export const userMe = async (
  options?: RequestInit,
): Promise<userMeResponse> => {
  return customFetch<Promise<userMeResponse>>(getUserMeUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getUserMeKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/me`] as const

export type UserMeQueryResult = NonNullable<Awaited<ReturnType<typeof userMe>>>
export type UserMeQueryError = UserMe400 | UserMe401 | UserMe403 | UserMe500

/**
 * @summary Obter dados do usuário autenticado
 */
export const useUserMe = <
  TError = UserMe400 | UserMe401 | UserMe403 | UserMe500,
>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof userMe>>, TError> & {
    swrKey?: Key
    enabled?: boolean
  }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getUserMeKey() : null))
  const swrFn = () => userMe(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite criar um novo usuário no sistema com as seguintes características:

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo de criação**:
  1. Verifica se já existe um usuário com o email fornecido
  2. Cria o registro de usuário com nome, email e perfil definido
  3. Configura uma conta Google associada ao usuário
* **Resposta**: Retorna o usuário criado com seu ID e perfil, incluindo status da conta

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Criar um novo usuário
 */
export type createUserResponse = {
  data: CreateUser201
  status: number
  headers: Headers
}

export const getCreateUserUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`
}

export const createUser = async (
  createUserBody: CreateUserBody,
  options?: RequestInit,
): Promise<createUserResponse> => {
  return customFetch<Promise<createUserResponse>>(getCreateUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUserBody),
  })
}

export const getCreateUserMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: CreateUserBody },
  ): Promise<createUserResponse> => {
    return createUser(arg, options)
  }
}
export const getCreateUserMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`] as const

export type CreateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUser>>
>
export type CreateUserMutationError =
  | CreateUser400
  | CreateUser401
  | CreateUser403
  | CreateUser409
  | CreateUser422
  | CreateUser500

/**
 * @summary Criar um novo usuário
 */
export const useCreateUser = <
  TError =
    | CreateUser400
    | CreateUser401
    | CreateUser403
    | CreateUser409
    | CreateUser422
    | CreateUser500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createUser>>,
    TError,
    Key,
    CreateUserBody,
    Awaited<ReturnType<typeof createUser>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateUserMutationKey()
  const swrFn = getCreateUserMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite listar os usuários do sistema com recursos avançados de consulta.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Recursos de consulta**:
  1. **Paginação**: Controle o número de resultados por página e a página atual
  2. **Ordenação**: Ordene por diferentes campos (nome, email, data de criação)
  3. **Filtragem**: Filtre usuários por papel, status da conta ou termos de busca
  4. **Busca**: Pesquise por nome, email ou outros campos relevantes

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Listar todos os usuários
 */
export type listUsersResponse = {
  data: ListUsers201
  status: number
  headers: Headers
}

export const getListUsersUrl = (params?: ListUsersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`
}

export const listUsers = async (
  params?: ListUsersParams,
  options?: RequestInit,
): Promise<listUsersResponse> => {
  return customFetch<Promise<listUsersResponse>>(getListUsersUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getListUsersKey = (params?: ListUsersParams) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`,
    ...(params ? [params] : []),
  ] as const

export type ListUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUsers>>
>
export type ListUsersQueryError =
  | ListUsers400
  | ListUsers401
  | ListUsers403
  | ListUsers422
  | ListUsers500

/**
 * @summary Listar todos os usuários
 */
export const useListUsers = <
  TError =
    | ListUsers400
    | ListUsers401
    | ListUsers403
    | ListUsers422
    | ListUsers500,
>(
  params?: ListUsersParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof listUsers>>, TError> & {
      swrKey?: Key
      enabled?: boolean
    }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getListUsersKey(params) : null))
  const swrFn = () => listUsers(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite excluir permanentemente um usuário específico do sistema.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Restrições**:
  1. Um usuário não pode excluir sua própria conta
  2. Apenas usuários com perfil 'admin' ou 'dev' podem excluir usuários
* **Processo de exclusão**:
  1. Valida o ID do usuário a ser excluído
  2. Exclui as sessões ativas do usuário
  3. Remove contas vinculadas (Google, etc.)
  4. Remove o registro do usuário do banco de dados

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Excluir um usuário
 */
export type deleteUserResponse = {
  data: DeleteUser200
  status: number
  headers: Headers
}

export const getDeleteUserUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`
}

export const deleteUser = async (
  id: string,
  options?: RequestInit,
): Promise<deleteUserResponse> => {
  return customFetch<Promise<deleteUserResponse>>(getDeleteUserUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteUserMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<deleteUserResponse> => {
    return deleteUser(id, options)
  }
}
export const getDeleteUserMutationKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`] as const

export type DeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>
export type DeleteUserMutationError =
  | DeleteUser400
  | DeleteUser401
  | DeleteUser403
  | DeleteUser404
  | DeleteUser409
  | DeleteUser422
  | DeleteUser500

/**
 * @summary Excluir um usuário
 */
export const useDeleteUser = <
  TError =
    | DeleteUser400
    | DeleteUser401
    | DeleteUser403
    | DeleteUser404
    | DeleteUser409
    | DeleteUser422
    | DeleteUser500,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteUser>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteUserMutationKey(id)
  const swrFn = getDeleteUserMutationFetcher(id, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint retorna os detalhes completos de um usuário específico identificado pelo ID.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo**:
  1. Valida o ID do usuário solicitado
  2. Busca informações detalhadas do usuário no banco de dados
  3. Retorna dados completos do perfil do usuário

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Obter detalhes de um usuário
 */
export type getUserResponse = {
  data: GetUser200
  status: number
  headers: Headers
}

export const getGetUserUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`
}

export const getUser = async (
  id: string,
  options?: RequestInit,
): Promise<getUserResponse> => {
  return customFetch<Promise<getUserResponse>>(getGetUserUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetUserKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`] as const

export type GetUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUser>>
>
export type GetUserQueryError =
  | GetUser400
  | GetUser401
  | GetUser403
  | GetUser404
  | GetUser422
  | GetUser500

/**
 * @summary Obter detalhes de um usuário
 */
export const useGetUser = <
  TError =
    | GetUser400
    | GetUser401
    | GetUser403
    | GetUser404
    | GetUser422
    | GetUser500,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getUser>>, TError> & {
      swrKey?: Key
      enabled?: boolean
    }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!id
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetUserKey(id) : null))
  const swrFn = () => getUser(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite atualizar parcialmente os dados de um usuário específico por meio de um PATCH.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Atualização parcial**: Implementa o conceito de PATCH, atualizando apenas os campos enviados na requisição.
* **Processo**:
  1. Valida o ID do usuário a ser atualizado
  2. Verifica se o usuário existe no banco de dados
  3. Aplica apenas as alterações enviadas no corpo da requisição
  4. Retorna o usuário com os dados atualizados

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Atualizar dados parciais de um usuário
 */
export type updateUserResponse = {
  data: UpdateUser200
  status: number
  headers: Headers
}

export const getUpdateUserUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`
}

export const updateUser = async (
  id: string,
  updateUserBody: UpdateUserBody,
  options?: RequestInit,
): Promise<updateUserResponse> => {
  return customFetch<Promise<updateUserResponse>>(getUpdateUserUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserBody),
  })
}

export const getUpdateUserMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: UpdateUserBody },
  ): Promise<updateUserResponse> => {
    return updateUser(id, arg, options)
  }
}
export const getUpdateUserMutationKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`] as const

export type UpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>
export type UpdateUserMutationError =
  | UpdateUser400
  | UpdateUser401
  | UpdateUser403
  | UpdateUser404
  | UpdateUser409
  | UpdateUser422
  | UpdateUser500

/**
 * @summary Atualizar dados parciais de um usuário
 */
export const useUpdateUser = <
  TError =
    | UpdateUser400
    | UpdateUser401
    | UpdateUser403
    | UpdateUser404
    | UpdateUser409
    | UpdateUser422
    | UpdateUser500,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof updateUser>>,
      TError,
      Key,
      UpdateUserBody,
      Awaited<ReturnType<typeof updateUser>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateUserMutationKey(id)
  const swrFn = getUpdateUserMutationFetcher(id, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
