/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'

import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'

import type {
  DeleteUser200,
  DeleteUser400,
  DeleteUser401,
  DeleteUser403,
  DeleteUser404,
  DeleteUser409,
  DeleteUser422,
  DeleteUser500,
  GrantBookingException200,
  GrantBookingException400,
  GrantBookingException401,
  GrantBookingException403,
  GrantBookingException404,
  GrantBookingException422,
  GrantBookingException500,
  GrantBookingExceptionBody,
  ListUserAbsences200,
  ListUserAbsences400,
  ListUserAbsences401,
  ListUserAbsences403,
  ListUserAbsences422,
  ListUserAbsences500,
  ListUserAbsencesParams,
  SetUserAbsence200,
  SetUserAbsence400,
  SetUserAbsence401,
  SetUserAbsence403,
  SetUserAbsence404,
  SetUserAbsence422,
  SetUserAbsence500,
  SetUserAbsenceBody,
  UserCreate201,
  UserCreate400,
  UserCreate401,
  UserCreate403,
  UserCreate409,
  UserCreate422,
  UserCreate500,
  UserCreateBody,
  UserGet200,
  UserGet400,
  UserGet401,
  UserGet403,
  UserGet404,
  UserGet422,
  UserGet500,
  UserList200,
  UserList400,
  UserList401,
  UserList403,
  UserList422,
  UserList500,
  UserListParams,
  UserMe200,
  UserMe400,
  UserMe401,
  UserMe403,
  UserMe500,
  UserUpdate200,
  UserUpdate400,
  UserUpdate401,
  UserUpdate403,
  UserUpdate404,
  UserUpdate409,
  UserUpdate422,
  UserUpdate500,
  UserUpdateBody,
} from '../bBZAppBackendAPI.schemas'

import { customFetch } from '../../mutator/custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Este endpoint recupera os dados completos do usuário atualmente autenticado.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com conta ativa.
* **Validação de conta**: Verifica se a conta do usuário está ativa e não requer reset de senha.
* **Processo**:
  1. Valida a autenticação do usuário via token JWT
  2. Verifica se a conta do usuário está ativa
  3. Recupera os dados completos do usuário
  4. Verifica se o usuário autorizou integração com calendário Google

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário está ativa
 * @summary Obter dados do usuário autenticado
 */
export type userMeResponse200 = {
  data: UserMe200
  status: 200
}

export type userMeResponse400 = {
  data: UserMe400
  status: 400
}

export type userMeResponse401 = {
  data: UserMe401
  status: 401
}

export type userMeResponse403 = {
  data: UserMe403
  status: 403
}

export type userMeResponse500 = {
  data: UserMe500
  status: 500
}

export type userMeResponseSuccess = userMeResponse200 & {
  headers: Headers
}
export type userMeResponseError = (
  userMeResponse400 | userMeResponse401 | userMeResponse403 | userMeResponse500
) & {
  headers: Headers
}

export const getUserMeUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/me`
}

export const userMe = async (
  options?: RequestInit,
): Promise<userMeResponseSuccess> => {
  return customFetch<userMeResponseSuccess>(getUserMeUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getUserMeKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/me`] as const

export type UserMeQueryResult = NonNullable<Awaited<ReturnType<typeof userMe>>>
export type UserMeQueryError = UserMe400 | UserMe401 | UserMe403 | UserMe500

/**
 * @summary Obter dados do usuário autenticado
 */
export const useUserMe = <
  TError = UserMe400 | UserMe401 | UserMe403 | UserMe500,
>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof userMe>>, TError> & {
    swrKey?: Key
    enabled?: boolean
  }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getUserMeKey() : null))
  const swrFn = () => userMe(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite criar um novo usuário no sistema com as seguintes características:

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo**:
  1. Verifica se já existe um usuário com o email fornecido
  2. Cria o registro de usuário com nome, email, cpf e perfil definido
  3. Configura uma conta Google associada ao usuário
  4. Retorna o usuário criado com seu ID e perfil, incluindo status da conta

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Criar um novo usuário
 */
export type userCreateResponse201 = {
  data: UserCreate201
  status: 201
}

export type userCreateResponse400 = {
  data: UserCreate400
  status: 400
}

export type userCreateResponse401 = {
  data: UserCreate401
  status: 401
}

export type userCreateResponse403 = {
  data: UserCreate403
  status: 403
}

export type userCreateResponse409 = {
  data: UserCreate409
  status: 409
}

export type userCreateResponse422 = {
  data: UserCreate422
  status: 422
}

export type userCreateResponse500 = {
  data: UserCreate500
  status: 500
}

export type userCreateResponseSuccess = userCreateResponse201 & {
  headers: Headers
}
export type userCreateResponseError = (
  | userCreateResponse400
  | userCreateResponse401
  | userCreateResponse403
  | userCreateResponse409
  | userCreateResponse422
  | userCreateResponse500
) & {
  headers: Headers
}

export const getUserCreateUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`
}

export const userCreate = async (
  userCreateBody: UserCreateBody,
  options?: RequestInit,
): Promise<userCreateResponseSuccess> => {
  return customFetch<userCreateResponseSuccess>(getUserCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userCreateBody),
  })
}

export const getUserCreateMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: UserCreateBody }) => {
    return userCreate(arg, options)
  }
}
export const getUserCreateMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`] as const

export type UserCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userCreate>>
>
export type UserCreateMutationError =
  | UserCreate400
  | UserCreate401
  | UserCreate403
  | UserCreate409
  | UserCreate422
  | UserCreate500

/**
 * @summary Criar um novo usuário
 */
export const useUserCreate = <
  TError =
    | UserCreate400
    | UserCreate401
    | UserCreate403
    | UserCreate409
    | UserCreate422
    | UserCreate500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof userCreate>>,
    TError,
    Key,
    UserCreateBody,
    Awaited<ReturnType<typeof userCreate>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUserCreateMutationKey()
  const swrFn = getUserCreateMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite listar os usuários do sistema com recursos avançados de consulta.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Recursos de consulta**:
  1. **Paginação**: Controle o número de resultados por página e a página atual
  2. **Ordenação**: Ordene por diferentes campos (nome, email, data de criação)
  3. **Filtragem**: Filtre usuários por papel, status da conta ou termos de busca
  4. **Busca**: Pesquise por nome, email ou outros campos relevantes

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Listar todos os usuários
 */
export type userListResponse200 = {
  data: UserList200
  status: 200
}

export type userListResponse400 = {
  data: UserList400
  status: 400
}

export type userListResponse401 = {
  data: UserList401
  status: 401
}

export type userListResponse403 = {
  data: UserList403
  status: 403
}

export type userListResponse422 = {
  data: UserList422
  status: 422
}

export type userListResponse500 = {
  data: UserList500
  status: 500
}

export type userListResponseSuccess = userListResponse200 & {
  headers: Headers
}
export type userListResponseError = (
  | userListResponse400
  | userListResponse401
  | userListResponse403
  | userListResponse422
  | userListResponse500
) & {
  headers: Headers
}

export const getUserListUrl = (params?: UserListParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user?${stringifiedParams}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`
}

export const userList = async (
  params?: UserListParams,
  options?: RequestInit,
): Promise<userListResponseSuccess> => {
  return customFetch<userListResponseSuccess>(getUserListUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getUserListKey = (params?: UserListParams) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`,
    ...(params ? [params] : []),
  ] as const

export type UserListQueryResult = NonNullable<
  Awaited<ReturnType<typeof userList>>
>
export type UserListQueryError =
  UserList400 | UserList401 | UserList403 | UserList422 | UserList500

/**
 * @summary Listar todos os usuários
 */
export const useUserList = <
  TError = UserList400 | UserList401 | UserList403 | UserList422 | UserList500,
>(
  params?: UserListParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof userList>>, TError> & {
      swrKey?: Key
      enabled?: boolean
    }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getUserListKey(params) : null))
  const swrFn = () => userList(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite excluir permanentemente um usuário específico do sistema.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Restrições**:
  1. Um usuário não pode excluir sua própria conta
  2. Apenas usuários com perfil 'admin' ou 'dev' podem excluir usuários
* **Processo de exclusão**:
  1. Valida o ID do usuário a ser excluído
  2. Exclui as sessões ativas do usuário
  3. Remove contas vinculadas (Google, etc.)
  4. Remove o registro do usuário do banco de dados

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Excluir um usuário
 */
export type deleteUserResponse200 = {
  data: DeleteUser200
  status: 200
}

export type deleteUserResponse400 = {
  data: DeleteUser400
  status: 400
}

export type deleteUserResponse401 = {
  data: DeleteUser401
  status: 401
}

export type deleteUserResponse403 = {
  data: DeleteUser403
  status: 403
}

export type deleteUserResponse404 = {
  data: DeleteUser404
  status: 404
}

export type deleteUserResponse409 = {
  data: DeleteUser409
  status: 409
}

export type deleteUserResponse422 = {
  data: DeleteUser422
  status: 422
}

export type deleteUserResponse500 = {
  data: DeleteUser500
  status: 500
}

export type deleteUserResponseSuccess = deleteUserResponse200 & {
  headers: Headers
}
export type deleteUserResponseError = (
  | deleteUserResponse400
  | deleteUserResponse401
  | deleteUserResponse403
  | deleteUserResponse404
  | deleteUserResponse409
  | deleteUserResponse422
  | deleteUserResponse500
) & {
  headers: Headers
}

export const getDeleteUserUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`
}

export const deleteUser = async (
  id: string,
  options?: RequestInit,
): Promise<deleteUserResponseSuccess> => {
  return customFetch<deleteUserResponseSuccess>(getDeleteUserUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteUserMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteUser(id, options)
  }
}
export const getDeleteUserMutationKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`] as const

export type DeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>
export type DeleteUserMutationError =
  | DeleteUser400
  | DeleteUser401
  | DeleteUser403
  | DeleteUser404
  | DeleteUser409
  | DeleteUser422
  | DeleteUser500

/**
 * @summary Excluir um usuário
 */
export const useDeleteUser = <
  TError =
    | DeleteUser400
    | DeleteUser401
    | DeleteUser403
    | DeleteUser404
    | DeleteUser409
    | DeleteUser422
    | DeleteUser500,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteUser>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteUserMutationKey(id)
  const swrFn = getDeleteUserMutationFetcher(id, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint retorna os detalhes completos de um usuário específico identificado pelo ID.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo**:
  1. Valida o ID do usuário solicitado
  2. Busca informações detalhadas do usuário no banco de dados
  3. Retorna dados completos do perfil do usuário

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Obter detalhes de um usuário
 */
export type userGetResponse200 = {
  data: UserGet200
  status: 200
}

export type userGetResponse400 = {
  data: UserGet400
  status: 400
}

export type userGetResponse401 = {
  data: UserGet401
  status: 401
}

export type userGetResponse403 = {
  data: UserGet403
  status: 403
}

export type userGetResponse404 = {
  data: UserGet404
  status: 404
}

export type userGetResponse422 = {
  data: UserGet422
  status: 422
}

export type userGetResponse500 = {
  data: UserGet500
  status: 500
}

export type userGetResponseSuccess = userGetResponse200 & {
  headers: Headers
}
export type userGetResponseError = (
  | userGetResponse400
  | userGetResponse401
  | userGetResponse403
  | userGetResponse404
  | userGetResponse422
  | userGetResponse500
) & {
  headers: Headers
}

export const getUserGetUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`
}

export const userGet = async (
  id: string,
  options?: RequestInit,
): Promise<userGetResponseSuccess> => {
  return customFetch<userGetResponseSuccess>(getUserGetUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getUserGetKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`] as const

export type UserGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof userGet>>
>
export type UserGetQueryError =
  UserGet400 | UserGet401 | UserGet403 | UserGet404 | UserGet422 | UserGet500

/**
 * @summary Obter detalhes de um usuário
 */
export const useUserGet = <
  TError =
    UserGet400 | UserGet401 | UserGet403 | UserGet404 | UserGet422 | UserGet500,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof userGet>>, TError> & {
      swrKey?: Key
      enabled?: boolean
    }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!id
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getUserGetKey(id) : null))
  const swrFn = () => userGet(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite atualizar parcialmente os dados de um usuário específico por meio de um PATCH.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Atualização parcial**: Implementa o conceito de PATCH, atualizando apenas os campos enviados na requisição.
* **Processo**:
  1. Valida o ID do usuário a ser atualizado
  2. Verifica se o usuário existe no banco de dados
  3. Aplica apenas as alterações enviadas no corpo da requisição
  4. Retorna o usuário com os dados atualizados

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Atualizar dados parciais de um usuário
 */
export type userUpdateResponse200 = {
  data: UserUpdate200
  status: 200
}

export type userUpdateResponse400 = {
  data: UserUpdate400
  status: 400
}

export type userUpdateResponse401 = {
  data: UserUpdate401
  status: 401
}

export type userUpdateResponse403 = {
  data: UserUpdate403
  status: 403
}

export type userUpdateResponse404 = {
  data: UserUpdate404
  status: 404
}

export type userUpdateResponse409 = {
  data: UserUpdate409
  status: 409
}

export type userUpdateResponse422 = {
  data: UserUpdate422
  status: 422
}

export type userUpdateResponse500 = {
  data: UserUpdate500
  status: 500
}

export type userUpdateResponseSuccess = userUpdateResponse200 & {
  headers: Headers
}
export type userUpdateResponseError = (
  | userUpdateResponse400
  | userUpdateResponse401
  | userUpdateResponse403
  | userUpdateResponse404
  | userUpdateResponse409
  | userUpdateResponse422
  | userUpdateResponse500
) & {
  headers: Headers
}

export const getUserUpdateUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`
}

export const userUpdate = async (
  id: string,
  userUpdateBody: UserUpdateBody,
  options?: RequestInit,
): Promise<userUpdateResponseSuccess> => {
  return customFetch<userUpdateResponseSuccess>(getUserUpdateUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdateBody),
  })
}

export const getUserUpdateMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: UserUpdateBody }) => {
    return userUpdate(id, arg, options)
  }
}
export const getUserUpdateMutationKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`] as const

export type UserUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userUpdate>>
>
export type UserUpdateMutationError =
  | UserUpdate400
  | UserUpdate401
  | UserUpdate403
  | UserUpdate404
  | UserUpdate409
  | UserUpdate422
  | UserUpdate500

/**
 * @summary Atualizar dados parciais de um usuário
 */
export const useUserUpdate = <
  TError =
    | UserUpdate400
    | UserUpdate401
    | UserUpdate403
    | UserUpdate404
    | UserUpdate409
    | UserUpdate422
    | UserUpdate500,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof userUpdate>>,
      TError,
      Key,
      UserUpdateBody,
      Awaited<ReturnType<typeof userUpdate>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUserUpdateMutationKey(id)
  const swrFn = getUserUpdateMutationFetcher(id, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite conceder ou revogar uma exceção temporária de prazo para reservas de um colaborador.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**:
  - Admin/Dev: Pode conceder para qualquer usuário com posição em time
  - Diretor: Pode conceder para qualquer usuário com posição em time
  - Supervisor: Apenas para membros da própria equipe
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**O que a exceção libera (semana vigente)**:
- Fazer reserva na sexta-feira
- Fazer reserva na semana atual
- Ignora limite de dias (2-3 por cargo)
- Ignora segunda/sexta obrigatória
- MANTÉM validação de uma reserva de workstation por dia

**Comportamento**:
- `active: true`: Seta exceção até sábado da semana (23:59:59)
- `active: false`: Remove a exceção (seta NULL)

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Conceder ou revogar exceção de prazo para reservas
 */
export type grantBookingExceptionResponse200 = {
  data: GrantBookingException200
  status: 200
}

export type grantBookingExceptionResponse400 = {
  data: GrantBookingException400
  status: 400
}

export type grantBookingExceptionResponse401 = {
  data: GrantBookingException401
  status: 401
}

export type grantBookingExceptionResponse403 = {
  data: GrantBookingException403
  status: 403
}

export type grantBookingExceptionResponse404 = {
  data: GrantBookingException404
  status: 404
}

export type grantBookingExceptionResponse422 = {
  data: GrantBookingException422
  status: 422
}

export type grantBookingExceptionResponse500 = {
  data: GrantBookingException500
  status: 500
}

export type grantBookingExceptionResponseSuccess =
  grantBookingExceptionResponse200 & {
    headers: Headers
  }
export type grantBookingExceptionResponseError = (
  | grantBookingExceptionResponse400
  | grantBookingExceptionResponse401
  | grantBookingExceptionResponse403
  | grantBookingExceptionResponse404
  | grantBookingExceptionResponse422
  | grantBookingExceptionResponse500
) & {
  headers: Headers
}

export const getGrantBookingExceptionUrl = (userId: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${userId}/booking-exception`
}

export const grantBookingException = async (
  userId: string,
  grantBookingExceptionBody: GrantBookingExceptionBody,
  options?: RequestInit,
): Promise<grantBookingExceptionResponseSuccess> => {
  return customFetch<grantBookingExceptionResponseSuccess>(
    getGrantBookingExceptionUrl(userId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(grantBookingExceptionBody),
    },
  )
}

export const getGrantBookingExceptionMutationFetcher = (
  userId: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: GrantBookingExceptionBody }) => {
    return grantBookingException(userId, arg, options)
  }
}
export const getGrantBookingExceptionMutationKey = (userId: string) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${userId}/booking-exception`,
  ] as const

export type GrantBookingExceptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof grantBookingException>>
>
export type GrantBookingExceptionMutationError =
  | GrantBookingException400
  | GrantBookingException401
  | GrantBookingException403
  | GrantBookingException404
  | GrantBookingException422
  | GrantBookingException500

/**
 * @summary Conceder ou revogar exceção de prazo para reservas
 */
export const useGrantBookingException = <
  TError =
    | GrantBookingException400
    | GrantBookingException401
    | GrantBookingException403
    | GrantBookingException404
    | GrantBookingException422
    | GrantBookingException500,
>(
  userId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof grantBookingException>>,
      TError,
      Key,
      GrantBookingExceptionBody,
      Awaited<ReturnType<typeof grantBookingException>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey =
    swrOptions?.swrKey ?? getGrantBookingExceptionMutationKey(userId)
  const swrFn = getGrantBookingExceptionMutationFetcher(userId, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite definir ou remover o período de afastamento de um usuário (férias, licença, etc.).

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**:
  - Admin/Dev: Pode definir para qualquer usuário
  - Diretor: Pode definir para qualquer usuário
  - Supervisor: Apenas para membros da própria equipe
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Efeitos do afastamento**:
- Usuário não pode fazer novas reservas de WORKSTATION durante o período
- Usuário é REMOVIDO de todos os indicadores de compliance:
  - Compliance semanal (não conta como não-compliant)
  - Checkout antecipado (ocorrências não aparecem)
  - Cancelamentos fora do prazo (não conta nos indicadores)
- Ao logar, usuário vê alerta informando o afastamento

**Comportamento**:
- Enviar startDate e endDate: Define o período de afastamento
- Enviar startDate e endDate como null: Remove o afastamento
 * @summary Definir ou remover afastamento de usuário
 */
export type setUserAbsenceResponse200 = {
  data: SetUserAbsence200
  status: 200
}

export type setUserAbsenceResponse400 = {
  data: SetUserAbsence400
  status: 400
}

export type setUserAbsenceResponse401 = {
  data: SetUserAbsence401
  status: 401
}

export type setUserAbsenceResponse403 = {
  data: SetUserAbsence403
  status: 403
}

export type setUserAbsenceResponse404 = {
  data: SetUserAbsence404
  status: 404
}

export type setUserAbsenceResponse422 = {
  data: SetUserAbsence422
  status: 422
}

export type setUserAbsenceResponse500 = {
  data: SetUserAbsence500
  status: 500
}

export type setUserAbsenceResponseSuccess = setUserAbsenceResponse200 & {
  headers: Headers
}
export type setUserAbsenceResponseError = (
  | setUserAbsenceResponse400
  | setUserAbsenceResponse401
  | setUserAbsenceResponse403
  | setUserAbsenceResponse404
  | setUserAbsenceResponse422
  | setUserAbsenceResponse500
) & {
  headers: Headers
}

export const getSetUserAbsenceUrl = (userId: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${userId}/absence`
}

export const setUserAbsence = async (
  userId: string,
  setUserAbsenceBody: SetUserAbsenceBody,
  options?: RequestInit,
): Promise<setUserAbsenceResponseSuccess> => {
  return customFetch<setUserAbsenceResponseSuccess>(
    getSetUserAbsenceUrl(userId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(setUserAbsenceBody),
    },
  )
}

export const getSetUserAbsenceMutationFetcher = (
  userId: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: SetUserAbsenceBody }) => {
    return setUserAbsence(userId, arg, options)
  }
}
export const getSetUserAbsenceMutationKey = (userId: string) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${userId}/absence`,
  ] as const

export type SetUserAbsenceMutationResult = NonNullable<
  Awaited<ReturnType<typeof setUserAbsence>>
>
export type SetUserAbsenceMutationError =
  | SetUserAbsence400
  | SetUserAbsence401
  | SetUserAbsence403
  | SetUserAbsence404
  | SetUserAbsence422
  | SetUserAbsence500

/**
 * @summary Definir ou remover afastamento de usuário
 */
export const useSetUserAbsence = <
  TError =
    | SetUserAbsence400
    | SetUserAbsence401
    | SetUserAbsence403
    | SetUserAbsence404
    | SetUserAbsence422
    | SetUserAbsence500,
>(
  userId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof setUserAbsence>>,
      TError,
      Key,
      SetUserAbsenceBody,
      Awaited<ReturnType<typeof setUserAbsence>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSetUserAbsenceMutationKey(userId)
  const swrFn = getSetUserAbsenceMutationFetcher(userId, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint lista todos os usuários com afastamento definido.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**:
  - Admin/Dev: Veem todos os afastamentos
  - Diretor: Vê todos os afastamentos
  - Supervisor: Vê apenas afastamentos da própria equipe
* **Paginação**: Suporta paginação via query params (page, pageSize)
* **Filtros**:
  - includeExpired: Se true, inclui afastamentos já expirados (padrão: false)
 * @summary Listar usuários afastados
 */
export type listUserAbsencesResponse200 = {
  data: ListUserAbsences200
  status: 200
}

export type listUserAbsencesResponse400 = {
  data: ListUserAbsences400
  status: 400
}

export type listUserAbsencesResponse401 = {
  data: ListUserAbsences401
  status: 401
}

export type listUserAbsencesResponse403 = {
  data: ListUserAbsences403
  status: 403
}

export type listUserAbsencesResponse422 = {
  data: ListUserAbsences422
  status: 422
}

export type listUserAbsencesResponse500 = {
  data: ListUserAbsences500
  status: 500
}

export type listUserAbsencesResponseSuccess = listUserAbsencesResponse200 & {
  headers: Headers
}
export type listUserAbsencesResponseError = (
  | listUserAbsencesResponse400
  | listUserAbsencesResponse401
  | listUserAbsencesResponse403
  | listUserAbsencesResponse422
  | listUserAbsencesResponse500
) & {
  headers: Headers
}

export const getListUserAbsencesUrl = (params?: ListUserAbsencesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/absences?${stringifiedParams}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/absences`
}

export const listUserAbsences = async (
  params?: ListUserAbsencesParams,
  options?: RequestInit,
): Promise<listUserAbsencesResponseSuccess> => {
  return customFetch<listUserAbsencesResponseSuccess>(
    getListUserAbsencesUrl(params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getListUserAbsencesKey = (params?: ListUserAbsencesParams) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/absences`,
    ...(params ? [params] : []),
  ] as const

export type ListUserAbsencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUserAbsences>>
>
export type ListUserAbsencesQueryError =
  | ListUserAbsences400
  | ListUserAbsences401
  | ListUserAbsences403
  | ListUserAbsences422
  | ListUserAbsences500

/**
 * @summary Listar usuários afastados
 */
export const useListUserAbsences = <
  TError =
    | ListUserAbsences400
    | ListUserAbsences401
    | ListUserAbsences403
    | ListUserAbsences422
    | ListUserAbsences500,
>(
  params?: ListUserAbsencesParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof listUserAbsences>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getListUserAbsencesKey(params) : null))
  const swrFn = () => listUserAbsences(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
