/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'
import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  DeleteUser200,
  DeleteUser400,
  DeleteUser401,
  DeleteUser403,
  DeleteUser404,
  DeleteUser409,
  DeleteUser422,
  DeleteUser500,
  GrantBookingException200,
  GrantBookingException400,
  GrantBookingException401,
  GrantBookingException403,
  GrantBookingException404,
  GrantBookingException422,
  GrantBookingException500,
  GrantBookingExceptionBody,
  ListUserAbsences200,
  ListUserAbsences400,
  ListUserAbsences401,
  ListUserAbsences403,
  ListUserAbsences422,
  ListUserAbsences500,
  ListUserAbsencesParams,
  SetUserAbsence200,
  SetUserAbsence400,
  SetUserAbsence401,
  SetUserAbsence403,
  SetUserAbsence404,
  SetUserAbsence422,
  SetUserAbsence500,
  SetUserAbsenceBody,
  UserCreate201,
  UserCreate400,
  UserCreate401,
  UserCreate403,
  UserCreate409,
  UserCreate422,
  UserCreate500,
  UserCreateBody,
  UserGet200,
  UserGet400,
  UserGet401,
  UserGet403,
  UserGet404,
  UserGet422,
  UserGet500,
  UserList200,
  UserList400,
  UserList401,
  UserList403,
  UserList422,
  UserList500,
  UserListParams,
  UserMe200,
  UserMe400,
  UserMe401,
  UserMe403,
  UserMe500,
  UserUpdate200,
  UserUpdate400,
  UserUpdate401,
  UserUpdate403,
  UserUpdate404,
  UserUpdate409,
  UserUpdate422,
  UserUpdate500,
  UserUpdateBody,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Este endpoint recupera os dados completos do usuário atualmente autenticado.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com conta ativa.
* **Validação de conta**: Verifica se a conta do usuário está ativa e não requer reset de senha.
* **Processo**:
  1. Valida a autenticação do usuário via token JWT
  2. Verifica se a conta do usuário está ativa
  3. Recupera os dados completos do usuário
  4. Verifica se o usuário autorizou integração com calendário Google

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário está ativa
 * @summary Obter dados do usuário autenticado
 */
export type userMeResponse = {
  data: UserMe200
  status: number
  headers: Headers
}

export const getUserMeUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/me`
}

export const userMe = async (
  options?: RequestInit,
): Promise<userMeResponse> => {
  return customFetch<Promise<userMeResponse>>(getUserMeUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getUserMeKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/me`] as const

export type UserMeQueryResult = NonNullable<Awaited<ReturnType<typeof userMe>>>
export type UserMeQueryError = UserMe400 | UserMe401 | UserMe403 | UserMe500

/**
 * @summary Obter dados do usuário autenticado
 */
export const useUserMe = <
  TError = UserMe400 | UserMe401 | UserMe403 | UserMe500,
>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof userMe>>, TError> & {
    swrKey?: Key
    enabled?: boolean
  }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getUserMeKey() : null))
  const swrFn = () => userMe(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite criar um novo usuário no sistema com as seguintes características:

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo**:
  1. Verifica se já existe um usuário com o email fornecido
  2. Cria o registro de usuário com nome, email, cpf e perfil definido
  3. Configura uma conta Google associada ao usuário
  4. Retorna o usuário criado com seu ID e perfil, incluindo status da conta

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Criar um novo usuário
 */
export type userCreateResponse = {
  data: UserCreate201
  status: number
  headers: Headers
}

export const getUserCreateUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`
}

export const userCreate = async (
  userCreateBody: UserCreateBody,
  options?: RequestInit,
): Promise<userCreateResponse> => {
  return customFetch<Promise<userCreateResponse>>(getUserCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userCreateBody),
  })
}

export const getUserCreateMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: UserCreateBody },
  ): Promise<userCreateResponse> => {
    return userCreate(arg, options)
  }
}
export const getUserCreateMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`] as const

export type UserCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userCreate>>
>
export type UserCreateMutationError =
  | UserCreate400
  | UserCreate401
  | UserCreate403
  | UserCreate409
  | UserCreate422
  | UserCreate500

/**
 * @summary Criar um novo usuário
 */
export const useUserCreate = <
  TError =
    | UserCreate400
    | UserCreate401
    | UserCreate403
    | UserCreate409
    | UserCreate422
    | UserCreate500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof userCreate>>,
    TError,
    Key,
    UserCreateBody,
    Awaited<ReturnType<typeof userCreate>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUserCreateMutationKey()
  const swrFn = getUserCreateMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite listar os usuários do sistema com recursos avançados de consulta.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Recursos de consulta**:
  1. **Paginação**: Controle o número de resultados por página e a página atual
  2. **Ordenação**: Ordene por diferentes campos (nome, email, data de criação)
  3. **Filtragem**: Filtre usuários por papel, status da conta ou termos de busca
  4. **Busca**: Pesquise por nome, email ou outros campos relevantes

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Listar todos os usuários
 */
export type userListResponse = {
  data: UserList200
  status: number
  headers: Headers
}

export const getUserListUrl = (params?: UserListParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`
}

export const userList = async (
  params?: UserListParams,
  options?: RequestInit,
): Promise<userListResponse> => {
  return customFetch<Promise<userListResponse>>(getUserListUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getUserListKey = (params?: UserListParams) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user`,
    ...(params ? [params] : []),
  ] as const

export type UserListQueryResult = NonNullable<
  Awaited<ReturnType<typeof userList>>
>
export type UserListQueryError =
  | UserList400
  | UserList401
  | UserList403
  | UserList422
  | UserList500

/**
 * @summary Listar todos os usuários
 */
export const useUserList = <
  TError = UserList400 | UserList401 | UserList403 | UserList422 | UserList500,
>(
  params?: UserListParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof userList>>, TError> & {
      swrKey?: Key
      enabled?: boolean
    }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getUserListKey(params) : null))
  const swrFn = () => userList(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite excluir permanentemente um usuário específico do sistema.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Restrições**:
  1. Um usuário não pode excluir sua própria conta
  2. Apenas usuários com perfil 'admin' ou 'dev' podem excluir usuários
* **Processo de exclusão**:
  1. Valida o ID do usuário a ser excluído
  2. Exclui as sessões ativas do usuário
  3. Remove contas vinculadas (Google, etc.)
  4. Remove o registro do usuário do banco de dados

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Excluir um usuário
 */
export type deleteUserResponse = {
  data: DeleteUser200
  status: number
  headers: Headers
}

export const getDeleteUserUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`
}

export const deleteUser = async (
  id: string,
  options?: RequestInit,
): Promise<deleteUserResponse> => {
  return customFetch<Promise<deleteUserResponse>>(getDeleteUserUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteUserMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<deleteUserResponse> => {
    return deleteUser(id, options)
  }
}
export const getDeleteUserMutationKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`] as const

export type DeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>
export type DeleteUserMutationError =
  | DeleteUser400
  | DeleteUser401
  | DeleteUser403
  | DeleteUser404
  | DeleteUser409
  | DeleteUser422
  | DeleteUser500

/**
 * @summary Excluir um usuário
 */
export const useDeleteUser = <
  TError =
    | DeleteUser400
    | DeleteUser401
    | DeleteUser403
    | DeleteUser404
    | DeleteUser409
    | DeleteUser422
    | DeleteUser500,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteUser>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteUserMutationKey(id)
  const swrFn = getDeleteUserMutationFetcher(id, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint retorna os detalhes completos de um usuário específico identificado pelo ID.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo**:
  1. Valida o ID do usuário solicitado
  2. Busca informações detalhadas do usuário no banco de dados
  3. Retorna dados completos do perfil do usuário

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Obter detalhes de um usuário
 */
export type userGetResponse = {
  data: UserGet200
  status: number
  headers: Headers
}

export const getUserGetUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`
}

export const userGet = async (
  id: string,
  options?: RequestInit,
): Promise<userGetResponse> => {
  return customFetch<Promise<userGetResponse>>(getUserGetUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getUserGetKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`] as const

export type UserGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof userGet>>
>
export type UserGetQueryError =
  | UserGet400
  | UserGet401
  | UserGet403
  | UserGet404
  | UserGet422
  | UserGet500

/**
 * @summary Obter detalhes de um usuário
 */
export const useUserGet = <
  TError =
    | UserGet400
    | UserGet401
    | UserGet403
    | UserGet404
    | UserGet422
    | UserGet500,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof userGet>>, TError> & {
      swrKey?: Key
      enabled?: boolean
    }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!id
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getUserGetKey(id) : null))
  const swrFn = () => userGet(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite atualizar parcialmente os dados de um usuário específico por meio de um PATCH.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Atualização parcial**: Implementa o conceito de PATCH, atualizando apenas os campos enviados na requisição.
* **Processo**:
  1. Valida o ID do usuário a ser atualizado
  2. Verifica se o usuário existe no banco de dados
  3. Aplica apenas as alterações enviadas no corpo da requisição
  4. Retorna o usuário com os dados atualizados

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Atualizar dados parciais de um usuário
 */
export type userUpdateResponse = {
  data: UserUpdate200
  status: number
  headers: Headers
}

export const getUserUpdateUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`
}

export const userUpdate = async (
  id: string,
  userUpdateBody: UserUpdateBody,
  options?: RequestInit,
): Promise<userUpdateResponse> => {
  return customFetch<Promise<userUpdateResponse>>(getUserUpdateUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdateBody),
  })
}

export const getUserUpdateMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: UserUpdateBody },
  ): Promise<userUpdateResponse> => {
    return userUpdate(id, arg, options)
  }
}
export const getUserUpdateMutationKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${id}`] as const

export type UserUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userUpdate>>
>
export type UserUpdateMutationError =
  | UserUpdate400
  | UserUpdate401
  | UserUpdate403
  | UserUpdate404
  | UserUpdate409
  | UserUpdate422
  | UserUpdate500

/**
 * @summary Atualizar dados parciais de um usuário
 */
export const useUserUpdate = <
  TError =
    | UserUpdate400
    | UserUpdate401
    | UserUpdate403
    | UserUpdate404
    | UserUpdate409
    | UserUpdate422
    | UserUpdate500,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof userUpdate>>,
      TError,
      Key,
      UserUpdateBody,
      Awaited<ReturnType<typeof userUpdate>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUserUpdateMutationKey(id)
  const swrFn = getUserUpdateMutationFetcher(id, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite conceder ou revogar uma exceção temporária de prazo para reservas de um colaborador.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: 
  - Admin/Dev: Pode conceder para qualquer usuário com posição em time
  - Diretor: Pode conceder para qualquer usuário com posição em time  
  - Supervisor: Apenas para membros da própria equipe
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**O que a exceção libera (semana vigente)**:
- Fazer reserva na sexta-feira
- Fazer reserva na semana atual
- Ignora limite de dias (2-3 por cargo)
- Ignora segunda/sexta obrigatória
- MANTÉM validação de uma reserva de workstation por dia

**Comportamento**:
- `active: true`: Seta exceção até sábado da semana (23:59:59)
- `active: false`: Remove a exceção (seta NULL)

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Conceder ou revogar exceção de prazo para reservas
 */
export type grantBookingExceptionResponse = {
  data: GrantBookingException200
  status: number
  headers: Headers
}

export const getGrantBookingExceptionUrl = (userId: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${userId}/booking-exception`
}

export const grantBookingException = async (
  userId: string,
  grantBookingExceptionBody: GrantBookingExceptionBody,
  options?: RequestInit,
): Promise<grantBookingExceptionResponse> => {
  return customFetch<Promise<grantBookingExceptionResponse>>(
    getGrantBookingExceptionUrl(userId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(grantBookingExceptionBody),
    },
  )
}

export const getGrantBookingExceptionMutationFetcher = (
  userId: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: GrantBookingExceptionBody },
  ): Promise<grantBookingExceptionResponse> => {
    return grantBookingException(userId, arg, options)
  }
}
export const getGrantBookingExceptionMutationKey = (userId: string) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${userId}/booking-exception`,
  ] as const

export type GrantBookingExceptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof grantBookingException>>
>
export type GrantBookingExceptionMutationError =
  | GrantBookingException400
  | GrantBookingException401
  | GrantBookingException403
  | GrantBookingException404
  | GrantBookingException422
  | GrantBookingException500

/**
 * @summary Conceder ou revogar exceção de prazo para reservas
 */
export const useGrantBookingException = <
  TError =
    | GrantBookingException400
    | GrantBookingException401
    | GrantBookingException403
    | GrantBookingException404
    | GrantBookingException422
    | GrantBookingException500,
>(
  userId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof grantBookingException>>,
      TError,
      Key,
      GrantBookingExceptionBody,
      Awaited<ReturnType<typeof grantBookingException>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey =
    swrOptions?.swrKey ?? getGrantBookingExceptionMutationKey(userId)
  const swrFn = getGrantBookingExceptionMutationFetcher(userId, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite definir ou remover o período de afastamento de um usuário (férias, licença, etc.).

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: 
  - Admin/Dev: Pode definir para qualquer usuário
  - Diretor: Pode definir para qualquer usuário
  - Supervisor: Apenas para membros da própria equipe
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Efeitos do afastamento**:
- Usuário não pode fazer novas reservas de WORKSTATION durante o período
- Usuário é REMOVIDO de todos os indicadores de compliance:
  - Compliance semanal (não conta como não-compliant)
  - Checkout antecipado (ocorrências não aparecem)
  - Cancelamentos fora do prazo (não conta nos indicadores)
- Ao logar, usuário vê alerta informando o afastamento

**Comportamento**:
- Enviar startDate e endDate: Define o período de afastamento
- Enviar startDate e endDate como null: Remove o afastamento
 * @summary Definir ou remover afastamento de usuário
 */
export type setUserAbsenceResponse = {
  data: SetUserAbsence200
  status: number
  headers: Headers
}

export const getSetUserAbsenceUrl = (userId: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${userId}/absence`
}

export const setUserAbsence = async (
  userId: string,
  setUserAbsenceBody: SetUserAbsenceBody,
  options?: RequestInit,
): Promise<setUserAbsenceResponse> => {
  return customFetch<Promise<setUserAbsenceResponse>>(
    getSetUserAbsenceUrl(userId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(setUserAbsenceBody),
    },
  )
}

export const getSetUserAbsenceMutationFetcher = (
  userId: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: SetUserAbsenceBody },
  ): Promise<setUserAbsenceResponse> => {
    return setUserAbsence(userId, arg, options)
  }
}
export const getSetUserAbsenceMutationKey = (userId: string) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/${userId}/absence`,
  ] as const

export type SetUserAbsenceMutationResult = NonNullable<
  Awaited<ReturnType<typeof setUserAbsence>>
>
export type SetUserAbsenceMutationError =
  | SetUserAbsence400
  | SetUserAbsence401
  | SetUserAbsence403
  | SetUserAbsence404
  | SetUserAbsence422
  | SetUserAbsence500

/**
 * @summary Definir ou remover afastamento de usuário
 */
export const useSetUserAbsence = <
  TError =
    | SetUserAbsence400
    | SetUserAbsence401
    | SetUserAbsence403
    | SetUserAbsence404
    | SetUserAbsence422
    | SetUserAbsence500,
>(
  userId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof setUserAbsence>>,
      TError,
      Key,
      SetUserAbsenceBody,
      Awaited<ReturnType<typeof setUserAbsence>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSetUserAbsenceMutationKey(userId)
  const swrFn = getSetUserAbsenceMutationFetcher(userId, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint lista todos os usuários com afastamento definido.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: 
  - Admin/Dev: Veem todos os afastamentos
  - Diretor: Vê todos os afastamentos
  - Supervisor: Vê apenas afastamentos da própria equipe
* **Paginação**: Suporta paginação via query params (page, pageSize)
* **Filtros**: 
  - includeExpired: Se true, inclui afastamentos já expirados (padrão: false)
 * @summary Listar usuários afastados
 */
export type listUserAbsencesResponse = {
  data: ListUserAbsences200
  status: number
  headers: Headers
}

export const getListUserAbsencesUrl = (params?: ListUserAbsencesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/absences?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/absences`
}

export const listUserAbsences = async (
  params?: ListUserAbsencesParams,
  options?: RequestInit,
): Promise<listUserAbsencesResponse> => {
  return customFetch<Promise<listUserAbsencesResponse>>(
    getListUserAbsencesUrl(params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getListUserAbsencesKey = (params?: ListUserAbsencesParams) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/user/absences`,
    ...(params ? [params] : []),
  ] as const

export type ListUserAbsencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUserAbsences>>
>
export type ListUserAbsencesQueryError =
  | ListUserAbsences400
  | ListUserAbsences401
  | ListUserAbsences403
  | ListUserAbsences422
  | ListUserAbsences500

/**
 * @summary Listar usuários afastados
 */
export const useListUserAbsences = <
  TError =
    | ListUserAbsences400
    | ListUserAbsences401
    | ListUserAbsences403
    | ListUserAbsences422
    | ListUserAbsences500,
>(
  params?: ListUserAbsencesParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof listUserAbsences>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getListUserAbsencesKey(params) : null))
  const swrFn = () => listUserAbsences(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
