/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Key } from 'swr'
import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  CancelRoomReservation200,
  CancelRoomReservation400,
  CancelRoomReservation401,
  CancelRoomReservation403,
  CancelRoomReservation404,
  CancelRoomReservation422,
  CancelRoomReservation500,
  CancelRoomReservationBody,
  CloseRoomReservation200,
  CloseRoomReservation400,
  CloseRoomReservation401,
  CloseRoomReservation403,
  CloseRoomReservation404,
  CloseRoomReservation422,
  CloseRoomReservation500,
  CloseRoomReservationBody,
  CreateRoomReservation201,
  CreateRoomReservation400,
  CreateRoomReservation401,
  CreateRoomReservation403,
  CreateRoomReservation404,
  CreateRoomReservation409,
  CreateRoomReservation422,
  CreateRoomReservation500,
  CreateRoomReservationBody,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Este endpoint permite que um usuário crie uma ou mais reservas de sala a partir de slots pré-reservados.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Funcionalidade**:
  1. Converte uma ou mais pré-reservas (slots) em reservas confirmadas
  2. Registra os detalhes adicionais da reserva (colaboradores, convidados externos, etc.)
  3. Associa o usuário atual às reservas
  4. Verifica automaticamente se cada slot existe e está pré-reservado pelo mesmo usuário
  5. Cada slot deve estar dentro do período de pré-reserva (5 minutos)

* **Fluxo de reserva**:
  1. O usuário faz uma ou mais pré-reservas (via endpoint de pré-reserva)
  2. O sistema reserva os slots por 5 minutos para o usuário
  3. O usuário confirma as reservas com este endpoint, fornecendo detalhes adicionais
  4. O sistema confirma as reservas e atualiza o status dos slots para 'reserved'

* **Parâmetros no corpo**:
  - roomId (obrigatório): Identificador UUID da sala
  - roomSlotId (obrigatório): Lista de identificadores UUID dos slots pré-reservados
  - bbzCollaborators (opcional): Lista de colaboradores da BBZ que participarão da reunião
  - externalGuests (opcional): Lista de convidados externos que participarão da reunião
  - needsCopeira (opcional): Indica se a reserva necessita de serviço de copeira (padrão: false)

* **Exemplo de uso**:
  - Requisição básica: `POST /v1/private/reservation` com body:
  ```json
  {
    "roomId": "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
    "roomSlotId": ["b2c3d4e5-f6a7-8901-bcde-2345678901cd", "c3d4e5f6-a789-0123-cdef-3456789012de"],
    "bbzCollaborators": ["João Silva", "Maria Oliveira"],
    "externalGuests": ["Carlos Santos - Empresa XYZ"],
    "needsCopeira": true
  }
  ```

* **Formato da resposta**:
  - reservations: Array de objetos com todas as informações das reservas criadas
  - message: Mensagem informativa de sucesso

* **Notas**:
  - O ID do usuário que faz a reserva é automaticamente capturado do token JWT
  - As reservas só podem ser criadas a partir de slots que já estejam pré-reservados pelo mesmo usuário
  - Cada pré-reserva deve estar dentro do período válido de 5 minutos
  - O status das reservas criadas será definido como 'reserved'
 * @summary Criar uma reserva de sala
 */
export type createRoomReservationResponse = {
  data: CreateRoomReservation201
  status: number
  headers: Headers
}

export const getCreateRoomReservationUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation`
}

export const createRoomReservation = async (
  createRoomReservationBody: CreateRoomReservationBody,
  options?: RequestInit,
): Promise<createRoomReservationResponse> => {
  return customFetch<Promise<createRoomReservationResponse>>(
    getCreateRoomReservationUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createRoomReservationBody),
    },
  )
}

export const getCreateRoomReservationMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: CreateRoomReservationBody },
  ): Promise<createRoomReservationResponse> => {
    return createRoomReservation(arg, options)
  }
}
export const getCreateRoomReservationMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation`] as const

export type CreateRoomReservationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRoomReservation>>
>
export type CreateRoomReservationMutationError =
  | CreateRoomReservation400
  | CreateRoomReservation401
  | CreateRoomReservation403
  | CreateRoomReservation404
  | CreateRoomReservation409
  | CreateRoomReservation422
  | CreateRoomReservation500

/**
 * @summary Criar uma reserva de sala
 */
export const useCreateRoomReservation = <
  TError =
    | CreateRoomReservation400
    | CreateRoomReservation401
    | CreateRoomReservation403
    | CreateRoomReservation404
    | CreateRoomReservation409
    | CreateRoomReservation422
    | CreateRoomReservation500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createRoomReservation>>,
    TError,
    Key,
    CreateRoomReservationBody,
    Awaited<ReturnType<typeof createRoomReservation>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateRoomReservationMutationKey()
  const swrFn = getCreateRoomReservationMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite que um usuário feche uma reserva de sala que ele criou.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Funcionalidade**:
  1. Fecha uma reserva existente no status 'reserved'
  2. Atualiza o status para 'closed'
  3. Registra a data e hora de fechamento

* **Regras de negócio**:
  1. Apenas o criador da reserva pode fechá-la
  2. A reserva deve estar no status 'reserved' (não pode estar já fechada ou cancelada)
  3. O fechamento é definitivo e não pode ser desfeito

* **Parâmetros da URL**:
  - id (obrigatório): Identificador UUID da reserva a ser fechada

* **Corpo da requisição**:
  - Um objeto JSON vazio é necessário (seguindo o padrão REST para PATCH)

* **Exemplo de uso**:
  - Requisição básica: `PATCH /v1/private/reservation/close` com corpo JSON `{ "id": "a1b2c3d4-e5f6-7890-abcd-1234567890ab" }`

* **Formato da resposta**:
  - reservation: Objeto com todas as informações da reserva fechada
  - message: Mensagem informativa de sucesso

* **Notas**:
  - O ID do usuário que fecha a reserva é automaticamente capturado do token JWT
  - O status da reserva será atualizado para 'closed'
  - A data e hora de fechamento (closedAt) serão registradas automaticamente
 * @summary Fechar uma reserva de sala
 */
export type closeRoomReservationResponse = {
  data: CloseRoomReservation200
  status: number
  headers: Headers
}

export const getCloseRoomReservationUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/close`
}

export const closeRoomReservation = async (
  closeRoomReservationBody: CloseRoomReservationBody,
  options?: RequestInit,
): Promise<closeRoomReservationResponse> => {
  return customFetch<Promise<closeRoomReservationResponse>>(
    getCloseRoomReservationUrl(),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(closeRoomReservationBody),
    },
  )
}

export const getCloseRoomReservationMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: CloseRoomReservationBody },
  ): Promise<closeRoomReservationResponse> => {
    return closeRoomReservation(arg, options)
  }
}
export const getCloseRoomReservationMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/close`] as const

export type CloseRoomReservationMutationResult = NonNullable<
  Awaited<ReturnType<typeof closeRoomReservation>>
>
export type CloseRoomReservationMutationError =
  | CloseRoomReservation400
  | CloseRoomReservation401
  | CloseRoomReservation403
  | CloseRoomReservation404
  | CloseRoomReservation422
  | CloseRoomReservation500

/**
 * @summary Fechar uma reserva de sala
 */
export const useCloseRoomReservation = <
  TError =
    | CloseRoomReservation400
    | CloseRoomReservation401
    | CloseRoomReservation403
    | CloseRoomReservation404
    | CloseRoomReservation422
    | CloseRoomReservation500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof closeRoomReservation>>,
    TError,
    Key,
    CloseRoomReservationBody,
    Awaited<ReturnType<typeof closeRoomReservation>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCloseRoomReservationMutationKey()
  const swrFn = getCloseRoomReservationMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite que um administrador ou desenvolvedor cancele uma reserva de sala.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível APENAS a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Funcionalidade**:
  1. Cancela uma reserva existente no status 'reserved'
  2. Atualiza o status para 'cancelled'
  3. Registra a data e hora de cancelamento
  4. Armazena o motivo do cancelamento
  5. Registra o usuário que realizou o cancelamento

* **Regras de negócio**:
  1. Apenas usuários administradores ou desenvolvedores podem cancelar reservas
  2. A reserva deve estar no status 'reserved' (não pode estar já fechada ou cancelada)
  3. Um motivo de cancelamento deve ser fornecido
  4. O cancelamento é definitivo e não pode ser desfeito

* **Corpo da requisição**:
  - id (obrigatório): Identificador UUID da reserva a ser cancelada
  - cancelReason (obrigatório): Motivo do cancelamento (3 a 500 caracteres)

* **Exemplo de uso**:
  - Requisição básica: `PATCH /v1/private/reservation/cancel` com corpo JSON:
  ```json
  {
    "id": "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
    "cancelReason": "Sala em manutenção emergencial"
  }
  ```

* **Formato da resposta**:
  - reservation: Objeto com todas as informações da reserva cancelada
  - message: Mensagem informativa de sucesso

* **Notas**:
  - O ID do usuário que cancela a reserva é automaticamente capturado do token JWT
  - O status da reserva será atualizado para 'cancelled'
  - A data e hora de cancelamento (cancelledAt) serão registradas automaticamente
 * @summary Cancelar uma reserva de sala
 */
export type cancelRoomReservationResponse = {
  data: CancelRoomReservation200
  status: number
  headers: Headers
}

export const getCancelRoomReservationUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/cancel`
}

export const cancelRoomReservation = async (
  cancelRoomReservationBody: CancelRoomReservationBody,
  options?: RequestInit,
): Promise<cancelRoomReservationResponse> => {
  return customFetch<Promise<cancelRoomReservationResponse>>(
    getCancelRoomReservationUrl(),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(cancelRoomReservationBody),
    },
  )
}

export const getCancelRoomReservationMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: CancelRoomReservationBody },
  ): Promise<cancelRoomReservationResponse> => {
    return cancelRoomReservation(arg, options)
  }
}
export const getCancelRoomReservationMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/cancel`] as const

export type CancelRoomReservationMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelRoomReservation>>
>
export type CancelRoomReservationMutationError =
  | CancelRoomReservation400
  | CancelRoomReservation401
  | CancelRoomReservation403
  | CancelRoomReservation404
  | CancelRoomReservation422
  | CancelRoomReservation500

/**
 * @summary Cancelar uma reserva de sala
 */
export const useCancelRoomReservation = <
  TError =
    | CancelRoomReservation400
    | CancelRoomReservation401
    | CancelRoomReservation403
    | CancelRoomReservation404
    | CancelRoomReservation422
    | CancelRoomReservation500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof cancelRoomReservation>>,
    TError,
    Key,
    CancelRoomReservationBody,
    Awaited<ReturnType<typeof cancelRoomReservation>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCancelRoomReservationMutationKey()
  const swrFn = getCancelRoomReservationMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
