/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'
import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  CancelSpaceReservation200,
  CancelSpaceReservation400,
  CancelSpaceReservation401,
  CancelSpaceReservation403,
  CancelSpaceReservation404,
  CancelSpaceReservation422,
  CancelSpaceReservation500,
  CancelSpaceReservationBody,
  CloseSpaceReservation200,
  CloseSpaceReservation400,
  CloseSpaceReservation401,
  CloseSpaceReservation403,
  CloseSpaceReservation404,
  CloseSpaceReservation422,
  CloseSpaceReservation500,
  CloseSpaceReservationBody,
  CreateSpaceReservation201,
  CreateSpaceReservation400,
  CreateSpaceReservation401,
  CreateSpaceReservation403,
  CreateSpaceReservation404,
  CreateSpaceReservation409,
  CreateSpaceReservation422,
  CreateSpaceReservation500,
  CreateSpaceReservationBody,
  GetSpaceReservationStats200,
  GetSpaceReservationStats400,
  GetSpaceReservationStats401,
  GetSpaceReservationStats403,
  GetSpaceReservationStats500,
  ListSpaceReservations200,
  ListSpaceReservations400,
  ListSpaceReservations401,
  ListSpaceReservations403,
  ListSpaceReservations404,
  ListSpaceReservations422,
  ListSpaceReservations500,
  ListSpaceReservationsParams,
  ReservationCheckInOut200,
  ReservationCheckInOut400,
  ReservationCheckInOut401,
  ReservationCheckInOut403,
  ReservationCheckInOut404,
  ReservationCheckInOut422,
  ReservationCheckInOut500,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Este endpoint permite que um usuário crie uma reserva de espaço a partir de slots pré-reservados.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Novo modelo de reservas**:
  - Cada reserva agora possui somente uma linha na tabela independente de quantos slots estejam associados a ela
  - Slots sequenciais (ex: de 08:00 até às 12:00) serão considerados uma única reserva
  - Todos os IDs dos slots são armazenados em um array JSONB na reserva

* **Funcionalidade**:
  1. Converte um conjunto de pré-reservas (slots) em uma única reserva confirmada
  2. Registra os detalhes adicionais da reserva (colaboradores, convidados externos, etc.)
  3. Associa o usuário atual à reserva
  4. Verifica automaticamente se cada slot existe e está pré-reservado pelo mesmo usuário
  5. Cada slot deve estar dentro do período de pré-reserva (5 minutos)

* **Fluxo de reserva**:
  1. O usuário faz uma ou mais pré-reservas (via endpoint de pré-reserva)
  2. O sistema reserva os slots por 5 minutos para o usuário
  3. O usuário confirma a reserva com este endpoint, fornecendo detalhes adicionais
  4. O sistema confirma a reserva e atualiza o status dos slots para 'reserved'

* **Parâmetros no corpo**:
  - spaceId (obrigatório): Identificador UUID do espaço
  - spaceSlotIds (obrigatório): Lista de identificadores UUID dos slots pré-reservados
  - bbzCollaborators (opcional): Lista de colaboradores da BBZ que participarão da reunião
  - externalGuests (opcional): Lista de convidados externos que participarão da reunião
  - needsCopeira (opcional): Indica se a reserva necessita de serviço de copeira (padrão: false)

* **Exemplo de uso**:
  - Requisição básica: `POST /v1/private/reservation` com body:
  ```json
  {
    "spaceId": "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
    "spaceSlotIds": ["b2c3d4e5-f6a7-8901-bcde-2345678901cd", "c3d4e5f6-a789-0123-cdef-3456789012de"],
    "bbzCollaborators": ["João Silva", "Maria Oliveira"],
    "externalGuests": ["Carlos Santos - Empresa XYZ"],
    "needsCopeira": true
  }
  ```

* **Formato da resposta**:
  - reservations: Array de objetos com todas as informações das reservas criadas
  - message: Mensagem informativa de sucesso

* **Notas**:
  - O ID do usuário que faz a reserva é automaticamente capturado do token JWT
  - As reservas só podem ser criadas a partir de slots que já estejam pré-reservados pelo mesmo usuário
  - Cada pré-reserva deve estar dentro do período válido de 5 minutos
  - O status das reservas criadas será definido como 'reserved'
  - Mesmo que sejam fornecidos múltiplos slots, será criada apenas UMA reserva contendo todos esses slots
  - O slot_range armazenará o intervalo completo da reserva (hora inicial até hora final)
 * @summary Criar uma reserva de espaço
 */
export type createSpaceReservationResponse = {
  data: CreateSpaceReservation201
  status: number
  headers: Headers
}

export const getCreateSpaceReservationUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation`
}

export const createSpaceReservation = async (
  createSpaceReservationBody: CreateSpaceReservationBody,
  options?: RequestInit,
): Promise<createSpaceReservationResponse> => {
  return customFetch<Promise<createSpaceReservationResponse>>(
    getCreateSpaceReservationUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createSpaceReservationBody),
    },
  )
}

export const getCreateSpaceReservationMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: CreateSpaceReservationBody },
  ): Promise<createSpaceReservationResponse> => {
    return createSpaceReservation(arg, options)
  }
}
export const getCreateSpaceReservationMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation`] as const

export type CreateSpaceReservationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSpaceReservation>>
>
export type CreateSpaceReservationMutationError =
  | CreateSpaceReservation400
  | CreateSpaceReservation401
  | CreateSpaceReservation403
  | CreateSpaceReservation404
  | CreateSpaceReservation409
  | CreateSpaceReservation422
  | CreateSpaceReservation500

/**
 * @summary Criar uma reserva de espaço
 */
export const useCreateSpaceReservation = <
  TError =
    | CreateSpaceReservation400
    | CreateSpaceReservation401
    | CreateSpaceReservation403
    | CreateSpaceReservation404
    | CreateSpaceReservation409
    | CreateSpaceReservation422
    | CreateSpaceReservation500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createSpaceReservation>>,
    TError,
    Key,
    CreateSpaceReservationBody,
    Awaited<ReturnType<typeof createSpaceReservation>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateSpaceReservationMutationKey()
  const swrFn = getCreateSpaceReservationMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite que um usuário feche uma reserva de espaço que ele criou.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Funcionalidade**:
  1. Fecha uma reserva existente no status 'reserved'
  2. Atualiza o status para 'closed'
  3. Registra a data e hora de fechamento
  4. Remove os slots de espaço associados (se ainda existirem)

* **Regras de negócio**:
  1. Apenas o criador da reserva pode fechá-la
  2. A reserva deve estar no status 'reserved' (não pode estar já fechada ou cancelada)
  3. O fechamento é definitivo e não pode ser desfeito
  4. Os slots de espaço associados serão excluídos se ainda existirem (podem ter sido removidos por um job agendado)

* **Parâmetros da requisição**:
  - id (opcional): Identificador UUID da reserva a ser fechada
  - spaceSlotIds (opcional): Array de identificadores UUID dos slots associados à reserva

* **Exemplo de uso**:
  - Requisição básica: `PATCH /v1/private/reservation/close` com corpo JSON `{ "id": "a1b2c3d4-e5f6-7890-abcd-1234567890ab" }`
  - Alternativa: `PATCH /v1/private/reservation/close` com corpo JSON `{ "spaceSlotIds": ["a1b2c3d4-e5f6-7890-abcd-1234567890ab"] }`

* **Formato da resposta**:
  - reservation: Objeto com todas as informações da reserva fechada
  - message: Mensagem informativa de sucesso

* **Notas**:
  - O ID do usuário que fecha a reserva é automaticamente capturado do token JWT
  - O status da reserva será atualizado para 'closed'
  - A data e hora de fechamento (closedAt) serão registradas automaticamente
  - Os slots de espaço serão excluídos apenas se ainda existirem no sistema
 * @summary Fechar uma reserva de espaço
 */
export type closeSpaceReservationResponse = {
  data: CloseSpaceReservation200
  status: number
  headers: Headers
}

export const getCloseSpaceReservationUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/close`
}

export const closeSpaceReservation = async (
  closeSpaceReservationBody: CloseSpaceReservationBody,
  options?: RequestInit,
): Promise<closeSpaceReservationResponse> => {
  return customFetch<Promise<closeSpaceReservationResponse>>(
    getCloseSpaceReservationUrl(),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(closeSpaceReservationBody),
    },
  )
}

export const getCloseSpaceReservationMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: CloseSpaceReservationBody },
  ): Promise<closeSpaceReservationResponse> => {
    return closeSpaceReservation(arg, options)
  }
}
export const getCloseSpaceReservationMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/close`] as const

export type CloseSpaceReservationMutationResult = NonNullable<
  Awaited<ReturnType<typeof closeSpaceReservation>>
>
export type CloseSpaceReservationMutationError =
  | CloseSpaceReservation400
  | CloseSpaceReservation401
  | CloseSpaceReservation403
  | CloseSpaceReservation404
  | CloseSpaceReservation422
  | CloseSpaceReservation500

/**
 * @summary Fechar uma reserva de espaço
 */
export const useCloseSpaceReservation = <
  TError =
    | CloseSpaceReservation400
    | CloseSpaceReservation401
    | CloseSpaceReservation403
    | CloseSpaceReservation404
    | CloseSpaceReservation422
    | CloseSpaceReservation500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof closeSpaceReservation>>,
    TError,
    Key,
    CloseSpaceReservationBody,
    Awaited<ReturnType<typeof closeSpaceReservation>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCloseSpaceReservationMutationKey()
  const swrFn = getCloseSpaceReservationMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite que um administrador ou desenvolvedor cancele uma reserva de espaço.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível APENAS a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Funcionalidade**:
  1. Cancela uma reserva existente no status 'reserved'
  2. Atualiza o status para 'cancelled'
  3. Registra a data e hora de cancelamento
  4. Armazena o motivo do cancelamento
  5. Registra o usuário que realizou o cancelamento
  6. Remove os slots de espaço associados (se ainda existirem)

* **Regras de negócio**:
  1. Apenas usuários administradores ou desenvolvedores podem cancelar reservas
  2. A reserva deve estar no status 'reserved' (não pode estar já fechada ou cancelada)
  3. Um motivo de cancelamento deve ser fornecido
  4. O cancelamento é definitivo e não pode ser desfeito
  5. Os slots de espaço associados serão excluídos se ainda existirem (podem ter sido removidos por um job agendado)

* **Parâmetros da requisição**:
  - id (opcional): Identificador UUID da reserva a ser cancelada
  - spaceSlotIds (opcional): Array de identificadores UUID dos slots associados à reserva
  - cancelReason (obrigatório): Motivo do cancelamento (3 a 500 caracteres)

* **Exemplo de uso**:
  - Requisição usando ID: `PATCH /v1/private/reservation/cancel` com corpo JSON:
  ```json
  {
    "id": "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
    "cancelReason": "Espaço em manutenção emergencial"
  }
  ```
  - Alternativa: `PATCH /v1/private/reservation/cancel` com corpo JSON:
  ```json
  {
    "spaceSlotIds": ["a1b2c3d4-e5f6-7890-abcd-1234567890ab"],
    "cancelReason": "Espaço em manutenção emergencial"
  }
  ```

* **Formato da resposta**:
  - reservation: Objeto com todas as informações da reserva cancelada
  - message: Mensagem informativa de sucesso

* **Notas**:
  - O ID do usuário que cancela a reserva é automaticamente capturado do token JWT
  - O status da reserva será atualizado para 'cancelled'
  - A data e hora de cancelamento (cancelledAt) serão registradas automaticamente
  - Os slots de espaço serão excluídos apenas se ainda existirem no sistema
 * @summary Cancelar uma reserva de espaço
 */
export type cancelSpaceReservationResponse = {
  data: CancelSpaceReservation200
  status: number
  headers: Headers
}

export const getCancelSpaceReservationUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/cancel`
}

export const cancelSpaceReservation = async (
  cancelSpaceReservationBody: CancelSpaceReservationBody,
  options?: RequestInit,
): Promise<cancelSpaceReservationResponse> => {
  return customFetch<Promise<cancelSpaceReservationResponse>>(
    getCancelSpaceReservationUrl(),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(cancelSpaceReservationBody),
    },
  )
}

export const getCancelSpaceReservationMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: CancelSpaceReservationBody },
  ): Promise<cancelSpaceReservationResponse> => {
    return cancelSpaceReservation(arg, options)
  }
}
export const getCancelSpaceReservationMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/cancel`] as const

export type CancelSpaceReservationMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelSpaceReservation>>
>
export type CancelSpaceReservationMutationError =
  | CancelSpaceReservation400
  | CancelSpaceReservation401
  | CancelSpaceReservation403
  | CancelSpaceReservation404
  | CancelSpaceReservation422
  | CancelSpaceReservation500

/**
 * @summary Cancelar uma reserva de espaço
 */
export const useCancelSpaceReservation = <
  TError =
    | CancelSpaceReservation400
    | CancelSpaceReservation401
    | CancelSpaceReservation403
    | CancelSpaceReservation404
    | CancelSpaceReservation422
    | CancelSpaceReservation500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof cancelSpaceReservation>>,
    TError,
    Key,
    CancelSpaceReservationBody,
    Awaited<ReturnType<typeof cancelSpaceReservation>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCancelSpaceReservationMutationKey()
  const swrFn = getCancelSpaceReservationMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite listar reservas de espaço, com opção de filtrar por usuário.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários autenticados com conta ativa.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Funcionalidade**:
  1. Retorna reservas com paginação
  2. Permite definir parâmetros de paginação (page e pageSize)
  3. Traz informações detalhadas de cada reserva, incluindo dados do espaço e lista de IDs dos slots
  4. Permite filtrar por usuário específico (opcional)
  5. Permite incluir reservas onde o usuário é convidado (email está em bbz_collaborators ou external_guests)

* **Parâmetros de query**:
  - page (opcional): Número da página para paginação, começando em 1 (padrão: 1)
  - pageSize (opcional): Quantidade de resultados por página, entre 1 e 10000 (padrão: 10000)
  - userId (opcional): ID do usuário para filtrar reservas específicas
  - includeUserAsGuest (opcional): Se "true", inclui reservas onde o usuário é convidado

* **Exemplo de uso**:
  - Requisição básica: `GET /v1/private/reservation/list` (retorna todas as reservas)
  - Com paginação: `GET /v1/private/reservation/list?page=2&pageSize=15`
  - Filtrar por usuário: `GET /v1/private/reservation/list?userId=123e4567-e89b-12d3-a456-426614174000`
  - Filtrar por usuário incluindo convites: `GET /v1/private/reservation/list?userId=123e4567-e89b-12d3-a456-426614174000&includeUserAsGuest=true`

* **Formato da resposta**:
  - reservations: Array com detalhes completos de cada reserva, incluindo array spaceSlotIds
  - totalCount: Número total de reservas encontradas
  - totalPages: Número total de páginas disponíveis
  - currentPage: Número da página atual

* **Notas**:
  - Sem o parâmetro userId, o endpoint retorna TODAS as reservas do sistema
  - Com o parâmetro userId, retorna apenas as reservas do usuário especificado
  - Com userId e includeUserAsGuest=true, também retorna reservas onde o usuário é convidado
  - As reservas são ordenadas da mais recente para a mais antiga
  - Cada reserva agora contém um array spaceSlotIds com os IDs dos slots reservados
 * @summary Listar reservas de espaço
 */
export type listSpaceReservationsResponse = {
  data: ListSpaceReservations200
  status: number
  headers: Headers
}

export const getListSpaceReservationsUrl = (
  params?: ListSpaceReservationsParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/list?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/list`
}

export const listSpaceReservations = async (
  params?: ListSpaceReservationsParams,
  options?: RequestInit,
): Promise<listSpaceReservationsResponse> => {
  return customFetch<Promise<listSpaceReservationsResponse>>(
    getListSpaceReservationsUrl(params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getListSpaceReservationsKey = (
  params?: ListSpaceReservationsParams,
) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/list`,
    ...(params ? [params] : []),
  ] as const

export type ListSpaceReservationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listSpaceReservations>>
>
export type ListSpaceReservationsQueryError =
  | ListSpaceReservations400
  | ListSpaceReservations401
  | ListSpaceReservations403
  | ListSpaceReservations404
  | ListSpaceReservations422
  | ListSpaceReservations500

/**
 * @summary Listar reservas de espaço
 */
export const useListSpaceReservations = <
  TError =
    | ListSpaceReservations400
    | ListSpaceReservations401
    | ListSpaceReservations403
    | ListSpaceReservations404
    | ListSpaceReservations422
    | ListSpaceReservations500,
>(
  params?: ListSpaceReservationsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof listSpaceReservations>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getListSpaceReservationsKey(params) : null))
  const swrFn = () => listSpaceReservations(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint retorna estatísticas de reservas do usuário autenticado.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários autenticados com conta ativa.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.

* **Funcionalidade**:
  1. Retorna o total de reservas do usuário
  2. Retorna a próxima reserva futura (data/hora de início mais próxima)
  3. Retorna os três horários de início mais usados pelo usuário para reservas

* **Formato da resposta**:
  - total: número total de reservas
  - nextReservation: data/hora da próxima reserva no formato 'dd/MM/yyyy às HH:mm' ou null
  - mostUsedStartTimes: array com os três horários de início mais usados (formato HH:mm, do menor para o maior)

* **Exemplo de resposta**:
  {
    "total": 12,
    "nextReservation": "01/06/2025 às 10:00",
    "mostUsedStartTimes": ["10:00", "14:00", "16:00"]
  }

* **Notas**:
  - O userId é extraído do JWT do usuário autenticado
  - Se o usuário não tiver reservas futuras, nextReservation será null
  - Se o usuário tiver menos de três horários distintos, o array será preenchido com '00:00' até ter três itens

 * @summary Get reservation stats for the logged user
 */
export type getSpaceReservationStatsResponse = {
  data: GetSpaceReservationStats200
  status: number
  headers: Headers
}

export const getGetSpaceReservationStatsUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/stats`
}

export const getSpaceReservationStats = async (
  options?: RequestInit,
): Promise<getSpaceReservationStatsResponse> => {
  return customFetch<Promise<getSpaceReservationStatsResponse>>(
    getGetSpaceReservationStatsUrl(),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getGetSpaceReservationStatsKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/stats`] as const

export type GetSpaceReservationStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSpaceReservationStats>>
>
export type GetSpaceReservationStatsQueryError =
  | GetSpaceReservationStats400
  | GetSpaceReservationStats401
  | GetSpaceReservationStats403
  | GetSpaceReservationStats500

/**
 * @summary Get reservation stats for the logged user
 */
export const useGetSpaceReservationStats = <
  TError =
    | GetSpaceReservationStats400
    | GetSpaceReservationStats401
    | GetSpaceReservationStats403
    | GetSpaceReservationStats500,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getSpaceReservationStats>>,
    TError
  > & { swrKey?: Key; enabled?: boolean }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetSpaceReservationStatsKey() : null))
  const swrFn = () => getSpaceReservationStats(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Endpoint para realizar check-in ou check-out em uma reserva existente.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin', 'dev', 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo**:
  1. Verifica se a reserva existe e pertence ao usuário atual
  2. Determina automaticamente se deve realizar check-in ou check-out
  3. Valida regras de negócio (ex: check-in apenas 15 minutos antes do início)
  4. Atualiza o registro da reserva com a data e hora da operação
  5. Retorna os detalhes da reserva atualizada

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis especificados
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Realizar check-in ou check-out em uma reserva
 */
export type reservationCheckInOutResponse = {
  data: ReservationCheckInOut200
  status: number
  headers: Headers
}

export const getReservationCheckInOutUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/check-in-out/${id}`
}

export const reservationCheckInOut = async (
  id: string,
  options?: RequestInit,
): Promise<reservationCheckInOutResponse> => {
  return customFetch<Promise<reservationCheckInOutResponse>>(
    getReservationCheckInOutUrl(id),
    {
      ...options,
      method: 'PATCH',
    },
  )
}

export const getReservationCheckInOutMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    __: { arg: Arguments },
  ): Promise<reservationCheckInOutResponse> => {
    return reservationCheckInOut(id, options)
  }
}
export const getReservationCheckInOutMutationKey = (id: string) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/reservation/check-in-out/${id}`,
  ] as const

export type ReservationCheckInOutMutationResult = NonNullable<
  Awaited<ReturnType<typeof reservationCheckInOut>>
>
export type ReservationCheckInOutMutationError =
  | ReservationCheckInOut400
  | ReservationCheckInOut401
  | ReservationCheckInOut403
  | ReservationCheckInOut404
  | ReservationCheckInOut422
  | ReservationCheckInOut500

/**
 * @summary Realizar check-in ou check-out em uma reserva
 */
export const useReservationCheckInOut = <
  TError =
    | ReservationCheckInOut400
    | ReservationCheckInOut401
    | ReservationCheckInOut403
    | ReservationCheckInOut404
    | ReservationCheckInOut422
    | ReservationCheckInOut500,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof reservationCheckInOut>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof reservationCheckInOut>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getReservationCheckInOutMutationKey(id)
  const swrFn = getReservationCheckInOutMutationFetcher(id, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
