/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Key } from 'swr'

import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'

import type {
  DeleteImage200,
  DeleteImage400,
  DeleteImage401,
  DeleteImage403,
  DeleteImage422,
  DeleteImage500,
  DeleteImageBody,
  UploadImage201,
  UploadImage400,
  UploadImage401,
  UploadImage403,
  UploadImage422,
  UploadImage500,
  UploadImageBody,
  UploadImageParams,
} from '../bBZAppBackendAPI.schemas'

import { customFetch } from '../../mutator/custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Este endpoint permite que usuários autenticados façam upload de uma imagem para o armazenamento. A imagem deve ser enviada usando multipart/form-data com o campo "file".

        ## Parâmetros de consulta:
        - group (obrigatório): O grupo do ativo (ex: "avatar", "logo", "produto"). Indica o tipo ou categoria da imagem.
        - subtitle (opcional): Subtítulo para o ativo (ex: "perfil", "og", "bebida"). Quando fornecido, será concatenado com o grupo para formar o nome do arquivo.
        - folder (opcional): Pasta personalizada para armazenar a imagem. Se não fornecido, o arquivo será armazenado diretamente na pasta images.

        ## Como funciona:
        1. O sistema recebe a imagem via upload multipart/form-data
        2. Realiza validação de autenticação e permissões do usuário
        3. Processa os parâmetros de consulta (group, subtitle, folder)
        4. Gera um nome de arquivo único com timestamp
        5. Faz upload para o bucket S3 com a estrutura de pastas adequada
        6. Retorna o caminho completo da imagem salva

        ## Estrutura do caminho do arquivo:
        - Com folder: images/<folder>/<group>-<subtitle>-<timestamp>.webp
        - Sem folder: images/<group>-<subtitle>-<timestamp>.webp

        Onde:
        - folder: pasta personalizada (opcional)
        - group: categoria obrigatória da imagem
        - subtitle: subtipo opcional da imagem
        - timestamp: gerado no momento do upload em formato compacto (sem caracteres especiais)

        ## Exemplos de uso:
        POST /v1/private/image/s3/upload?folder=salas&group=sala&subtitle=presidencia
        POST /v1/private/image/s3/upload?group=produto

        ## Observações:
        - Todas as imagens são convertidas para o formato WebP para otimização
        - Este endpoint trata apenas o upload e retorna o caminho do arquivo
        - A atualização do banco de dados com o novo caminho da imagem (ex: mudar o avatar do usuário) deve ser tratada por outro endpoint
        - Requer autenticação via token JWT no header Authorization
 * @summary Fazer upload de imagem
 */
export type uploadImageResponse201 = {
  data: UploadImage201
  status: 201
}

export type uploadImageResponse400 = {
  data: UploadImage400
  status: 400
}

export type uploadImageResponse401 = {
  data: UploadImage401
  status: 401
}

export type uploadImageResponse403 = {
  data: UploadImage403
  status: 403
}

export type uploadImageResponse422 = {
  data: UploadImage422
  status: 422
}

export type uploadImageResponse500 = {
  data: UploadImage500
  status: 500
}

export type uploadImageResponseSuccess = uploadImageResponse201 & {
  headers: Headers
}
export type uploadImageResponseError = (
  | uploadImageResponse400
  | uploadImageResponse401
  | uploadImageResponse403
  | uploadImageResponse422
  | uploadImageResponse500
) & {
  headers: Headers
}

export const getUploadImageUrl = (params: UploadImageParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/image/s3/upload?${stringifiedParams}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/image/s3/upload`
}

export const uploadImage = async (
  uploadImageBody: UploadImageBody,
  params: UploadImageParams,
  options?: RequestInit,
): Promise<uploadImageResponseSuccess> => {
  const formData = new FormData()
  formData.append(`file`, uploadImageBody.file)

  return customFetch<uploadImageResponseSuccess>(getUploadImageUrl(params), {
    ...options,
    method: 'POST',
    body: formData,
  })
}

export const getUploadImageMutationFetcher = (
  params: UploadImageParams,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: UploadImageBody }) => {
    return uploadImage(arg, params, options)
  }
}
export const getUploadImageMutationKey = (params: UploadImageParams) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/image/s3/upload`,
    ...(params ? [params] : []),
  ] as const

export type UploadImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadImage>>
>
export type UploadImageMutationError =
  | UploadImage400
  | UploadImage401
  | UploadImage403
  | UploadImage422
  | UploadImage500

/**
 * @summary Fazer upload de imagem
 */
export const useUploadImage = <
  TError =
    | UploadImage400
    | UploadImage401
    | UploadImage403
    | UploadImage422
    | UploadImage500,
>(
  params: UploadImageParams,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof uploadImage>>,
      TError,
      Key,
      UploadImageBody,
      Awaited<ReturnType<typeof uploadImage>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUploadImageMutationKey(params)
  const swrFn = getUploadImageMutationFetcher(params, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite que usuários autenticados excluam uma imagem do armazenamento. O caminho completo da imagem deve ser enviado no corpo da requisição.

        ## Como funciona:
        1. O sistema recebe o caminho da imagem a ser excluída via corpo da requisição
        2. Realiza validação de autenticação e permissões do usuário
        3. Localiza a imagem no bucket S3 pelo caminho fornecido
        4. Remove o arquivo do armazenamento
        5. Retorna uma confirmação de sucesso

        ## Estrutura do corpo da requisição:
        ```json
        {
          "imagePath": "images/grupo-subtitulo-timestamp.webp"
        }
        ```

        ## Exemplos de uso:
        DELETE /v1/private/image/s3/delete
        Body: { "imagePath": "images/espacos/sala-presidencia-20250512123045.webp" }

        DELETE /v1/private/image/s3/delete
        Body: { "imagePath": "images/produto-bebida-20250512123045.webp" }

        ## Observações:
        - O caminho da imagem (imagePath) deve ser o caminho completo retornado pelo endpoint de upload
        - Dependendo de como o arquivo foi criado, o caminho pode incluir ou não uma pasta intermediária
        - Este endpoint apenas exclui o arquivo físico do armazenamento
        - A atualização de referências no banco de dados deve ser feita por endpoints específicos
        - Requer autenticação via token JWT no header Authorization
        - Não é possível desfazer esta operação depois de confirmada
 * @summary Excluir uma imagem
 */
export type deleteImageResponse200 = {
  data: DeleteImage200
  status: 200
}

export type deleteImageResponse400 = {
  data: DeleteImage400
  status: 400
}

export type deleteImageResponse401 = {
  data: DeleteImage401
  status: 401
}

export type deleteImageResponse403 = {
  data: DeleteImage403
  status: 403
}

export type deleteImageResponse422 = {
  data: DeleteImage422
  status: 422
}

export type deleteImageResponse500 = {
  data: DeleteImage500
  status: 500
}

export type deleteImageResponseSuccess = deleteImageResponse200 & {
  headers: Headers
}
export type deleteImageResponseError = (
  | deleteImageResponse400
  | deleteImageResponse401
  | deleteImageResponse403
  | deleteImageResponse422
  | deleteImageResponse500
) & {
  headers: Headers
}

export const getDeleteImageUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/image/s3/delete`
}

export const deleteImage = async (
  deleteImageBody: DeleteImageBody,
  options?: RequestInit,
): Promise<deleteImageResponseSuccess> => {
  return customFetch<deleteImageResponseSuccess>(getDeleteImageUrl(), {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteImageBody),
  })
}

export const getDeleteImageMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: DeleteImageBody }) => {
    return deleteImage(arg, options)
  }
}
export const getDeleteImageMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/image/s3/delete`] as const

export type DeleteImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteImage>>
>
export type DeleteImageMutationError =
  | DeleteImage400
  | DeleteImage401
  | DeleteImage403
  | DeleteImage422
  | DeleteImage500

/**
 * @summary Excluir uma imagem
 */
export const useDeleteImage = <
  TError =
    | DeleteImage400
    | DeleteImage401
    | DeleteImage403
    | DeleteImage422
    | DeleteImage500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof deleteImage>>,
    TError,
    Key,
    DeleteImageBody,
    Awaited<ReturnType<typeof deleteImage>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteImageMutationKey()
  const swrFn = getDeleteImageMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
