/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'
import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  AuthLoginCredential200,
  AuthLoginCredential400,
  AuthLoginCredential401,
  AuthLoginCredential403,
  AuthLoginCredential422,
  AuthLoginCredential500,
  AuthLoginCredentialBody,
  LoginUserGoogle302,
  LoginUserGoogle500,
  LoginUserGoogleCallback302,
  LoginUserGoogleCallback422,
  LoginUserGoogleCallback500,
  LoginUserGoogleCallbackParams,
  LogoutUser200,
  LogoutUser400,
  LogoutUser401,
  LogoutUser403,
  LogoutUser500,
  RefreshUserSession201,
  RefreshUserSession400,
  RefreshUserSession401,
  RefreshUserSession403,
  RefreshUserSession500,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Redireciona o usuário para a página de login do Google com escopos de Calendar
 * @summary Iniciar autenticação com Google
 */
export type loginUserGoogleResponse = {
  data: unknown
  status: number
  headers: Headers
}

export const getLoginUserGoogleUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/public/auth/login/google`
}

export const loginUserGoogle = async (
  options?: RequestInit,
): Promise<loginUserGoogleResponse> => {
  return customFetch<Promise<loginUserGoogleResponse>>(
    getLoginUserGoogleUrl(),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getLoginUserGoogleKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/public/auth/login/google`] as const

export type LoginUserGoogleQueryResult = NonNullable<
  Awaited<ReturnType<typeof loginUserGoogle>>
>
export type LoginUserGoogleQueryError = LoginUserGoogle302 | LoginUserGoogle500

/**
 * @summary Iniciar autenticação com Google
 */
export const useLoginUserGoogle = <
  TError = LoginUserGoogle302 | LoginUserGoogle500,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof loginUserGoogle>>,
    TError
  > & { swrKey?: Key; enabled?: boolean }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getLoginUserGoogleKey() : null))
  const swrFn = () => loginUserGoogle(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * 
          Este endpoint trata o callback de autenticação via Google OAuth2. Ele recebe, por query string, o código de autorização fornecido pelo Google, faz a troca por tokens de acesso e refresh, e em seguida busca os dados de perfil do usuário (nome, e-mail, foto e status de e-mail verificado).

          Se o usuário já existir no banco, seus dados serão atualizados com as informações mais recentes do Google; caso contrário, um erro será retornado informando que a conta não foi encontrada. Depois, o repositório de contas (accounts) também é atualizado, armazenando os tokens para chamadas futuras à API Calendar.

          Em seguida, a aplicação gera seus próprios tokens de sessão (JWT e refresh token), configura os cookies de autenticação no cliente e persiste a sessão no banco, removendo registros expirados. Por fim, redireciona o usuário de volta ao frontend com status 302, levando em conta falhas (código ausente, conta não encontrada ou erros internos) e incluindo, em caso de erro, parâmetros de nome, mensagem, ação e código HTTP para que o frontend exiba a notificação adequada ao usuário.
        
 * @summary Callback para autenticação com Google
 */
export type loginUserGoogleCallbackResponse = {
  data: unknown
  status: number
  headers: Headers
}

export const getLoginUserGoogleCallbackUrl = (
  params?: LoginUserGoogleCallbackParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/public/auth/login/google/callback?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/public/auth/login/google/callback`
}

export const loginUserGoogleCallback = async (
  params?: LoginUserGoogleCallbackParams,
  options?: RequestInit,
): Promise<loginUserGoogleCallbackResponse> => {
  return customFetch<Promise<loginUserGoogleCallbackResponse>>(
    getLoginUserGoogleCallbackUrl(params),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getLoginUserGoogleCallbackKey = (
  params?: LoginUserGoogleCallbackParams,
) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/public/auth/login/google/callback`,
    ...(params ? [params] : []),
  ] as const

export type LoginUserGoogleCallbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof loginUserGoogleCallback>>
>
export type LoginUserGoogleCallbackQueryError =
  | LoginUserGoogleCallback302
  | LoginUserGoogleCallback422
  | LoginUserGoogleCallback500

/**
 * @summary Callback para autenticação com Google
 */
export const useLoginUserGoogleCallback = <
  TError =
    | LoginUserGoogleCallback302
    | LoginUserGoogleCallback422
    | LoginUserGoogleCallback500,
>(
  params?: LoginUserGoogleCallbackParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof loginUserGoogleCallback>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getLoginUserGoogleCallbackKey(params) : null))
  const swrFn = () => loginUserGoogleCallback(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Endpoint para autenticação de usuários com email e senha.

* **Segurança**: Endpoint público, não requer autenticação prévia.
* **Processo**:
  1. Valida os dados de entrada (email e senha)
  2. Verifica se o usuário existe e se a senha está correta
  3. Cria uma sessão para o usuário e retorna os dados do usuário autenticado

**Dados de entrada**:
- Email do usuário (obrigatório)
- Senha do usuário (obrigatório)

**Resposta**:
- Dados do usuário autenticado
- Mensagem de confirmação
 * @summary Autenticação com credenciais (email e senha)
 */
export type authLoginCredentialResponse = {
  data: AuthLoginCredential200
  status: number
  headers: Headers
}

export const getAuthLoginCredentialUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/public/auth/login/credential`
}

export const authLoginCredential = async (
  authLoginCredentialBody: AuthLoginCredentialBody,
  options?: RequestInit,
): Promise<authLoginCredentialResponse> => {
  return customFetch<Promise<authLoginCredentialResponse>>(
    getAuthLoginCredentialUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(authLoginCredentialBody),
    },
  )
}

export const getAuthLoginCredentialMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: AuthLoginCredentialBody },
  ): Promise<authLoginCredentialResponse> => {
    return authLoginCredential(arg, options)
  }
}
export const getAuthLoginCredentialMutationKey = () =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/public/auth/login/credential`,
  ] as const

export type AuthLoginCredentialMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLoginCredential>>
>
export type AuthLoginCredentialMutationError =
  | AuthLoginCredential400
  | AuthLoginCredential401
  | AuthLoginCredential403
  | AuthLoginCredential422
  | AuthLoginCredential500

/**
 * @summary Autenticação com credenciais (email e senha)
 */
export const useAuthLoginCredential = <
  TError =
    | AuthLoginCredential400
    | AuthLoginCredential401
    | AuthLoginCredential403
    | AuthLoginCredential422
    | AuthLoginCredential500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authLoginCredential>>,
    TError,
    Key,
    AuthLoginCredentialBody,
    Awaited<ReturnType<typeof authLoginCredential>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAuthLoginCredentialMutationKey()
  const swrFn = getAuthLoginCredentialMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint realiza o logout do usuário ao encerrar sua sessão atual. Quando acionado, o sistema identifica a sessão do usuário atual através do token de atualização (refresh token), remove esta sessão específica do banco de dados e limpa todos os cookies de autenticação no navegador do usuário.

Processo de execução:

 - Validação de Segurança: Confirma a identidade do usuário através do token JWT de atualização e verifica se o token CSRF está presente e é válido.

 - Encerramento de Sessão: Remove apenas a sessão atual do banco de dados, mantendo outras sessões ativas do mesmo usuário em outros dispositivos.

 - Limpeza de Cookies: Remove os cookies de autenticação (token de sessão, token de atualização e token CSRF) do navegador do usuário, definindo-os como expirados.

Após o logout bem-sucedido, o usuário precisará se autenticar novamente para acessar recursos protegidos da aplicação. O endpoint retorna uma mensagem de confirmação quando o logout é concluído com sucesso.
 * @summary Desconectar usuário
 */
export type logoutUserResponse = {
  data: LogoutUser200
  status: number
  headers: Headers
}

export const getLogoutUserUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/auth/logout/user`
}

export const logoutUser = async (
  options?: RequestInit,
): Promise<logoutUserResponse> => {
  return customFetch<Promise<logoutUserResponse>>(getLogoutUserUrl(), {
    ...options,
    method: 'PATCH',
  })
}

export const getLogoutUserMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<logoutUserResponse> => {
    return logoutUser(options)
  }
}
export const getLogoutUserMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/auth/logout/user`] as const

export type LogoutUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutUser>>
>
export type LogoutUserMutationError =
  | LogoutUser400
  | LogoutUser401
  | LogoutUser403
  | LogoutUser500

/**
 * @summary Desconectar usuário
 */
export const useLogoutUser = <
  TError = LogoutUser400 | LogoutUser401 | LogoutUser403 | LogoutUser500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof logoutUser>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getLogoutUserMutationKey()
  const swrFn = getLogoutUserMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint renova automaticamente a sessão de um usuário que já está autenticado, permitindo que ele permaneça conectado sem necessidade de fazer login novamente quando sua sessão atual estiver expirando.

* **Segurança**: Protegido por autenticação JWT Refresh (token de atualização) e CSRF via cookie/header.
* **Autorização**: Disponível para usuários autenticados com qualquer perfil.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo**:
  1. Valida o token de atualização (refresh token) e confirma a validade do token CSRF
  2. Verifica se a sessão existe no banco de dados e corresponde ao usuário autenticado
  3. Gera novos tokens de autenticação e atualização
  4. Atualiza a sessão existente no banco de dados
  5. Retorna os dados atualizados do usuário e o ID da sessão renovada

**Middlewares aplicados**:
- `verifyJWTRefresh`: Valida o token de atualização JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Atualizar sessão do usuário
 */
export type refreshUserSessionResponse = {
  data: RefreshUserSession201
  status: number
  headers: Headers
}

export const getRefreshUserSessionUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/auth/refresh/user/session`
}

export const refreshUserSession = async (
  options?: RequestInit,
): Promise<refreshUserSessionResponse> => {
  return customFetch<Promise<refreshUserSessionResponse>>(
    getRefreshUserSessionUrl(),
    {
      ...options,
      method: 'PATCH',
    },
  )
}

export const getRefreshUserSessionMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    __: { arg: Arguments },
  ): Promise<refreshUserSessionResponse> => {
    return refreshUserSession(options)
  }
}
export const getRefreshUserSessionMutationKey = () =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/auth/refresh/user/session`,
  ] as const

export type RefreshUserSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof refreshUserSession>>
>
export type RefreshUserSessionMutationError =
  | RefreshUserSession400
  | RefreshUserSession401
  | RefreshUserSession403
  | RefreshUserSession500

/**
 * @summary Atualizar sessão do usuário
 */
export const useRefreshUserSession = <
  TError =
    | RefreshUserSession400
    | RefreshUserSession401
    | RefreshUserSession403
    | RefreshUserSession500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof refreshUserSession>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof refreshUserSession>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRefreshUserSessionMutationKey()
  const swrFn = getRefreshUserSessionMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
