/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  ServerHealthCheck200,
  ServerHealthCheck500,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * This endpoint performs a simple health check on the server. When a GET request is made to '/v1/public/infra/server/health', the server responds with a 200 status code and a message indicating that it is healthy and operational.

This endpoint is primarily used for monitoring and testing purposes, such as verifying that the API server is running and responsive. It provides a minimal response structure containing a single message field, making it an ideal solution for automated health checks and system monitoring.
 * @summary Check if the server is healthy
 */
export type serverHealthCheckResponse = {
  data: ServerHealthCheck200
  status: number
  headers: Headers
}

export const getServerHealthCheckUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/public/infra/server/health`
}

export const serverHealthCheck = async (
  options?: RequestInit,
): Promise<serverHealthCheckResponse> => {
  return customFetch<Promise<serverHealthCheckResponse>>(
    getServerHealthCheckUrl(),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getServerHealthCheckKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/public/infra/server/health`] as const

export type ServerHealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof serverHealthCheck>>
>
export type ServerHealthCheckQueryError = ServerHealthCheck500

/**
 * @summary Check if the server is healthy
 */
export const useServerHealthCheck = <TError = ServerHealthCheck500>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof serverHealthCheck>>,
    TError
  > & { swrKey?: Key; enabled?: boolean }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getServerHealthCheckKey() : null))
  const swrFn = () => serverHealthCheck(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
