/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'
import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  CreatePosition201,
  CreatePosition400,
  CreatePosition401,
  CreatePosition403,
  CreatePosition404,
  CreatePosition409,
  CreatePosition422,
  CreatePosition500,
  CreatePositionBody,
  GetOrganogram200,
  GetOrganogram400,
  GetOrganogram401,
  GetOrganogram403,
  GetOrganogram500,
  GetPosition200,
  GetPosition400,
  GetPosition401,
  GetPosition403,
  GetPosition422,
  GetPosition500,
  ListPositions200,
  ListPositions400,
  ListPositions401,
  ListPositions403,
  ListPositions422,
  ListPositions500,
  RemovePosition200,
  RemovePosition400,
  RemovePosition401,
  RemovePosition403,
  RemovePosition404,
  RemovePosition422,
  RemovePosition500,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Este endpoint permite nomear um usuário para uma posição na equipe de atendimento.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Baseada na hierarquia da equipe:
  - Admin/Dev → pode nomear Director
  - Director → pode nomear Supervisor
  - Supervisor → pode nomear Manager
  - Manager → pode nomear Assistant Manager e Assistant
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Posições disponíveis**:
- `director`: Diretor (nível 1) - Apenas 1
- `supervisor`: Supervisor (nível 2) - Máximo 7
- `manager`: Gerente (nível 3) - Máximo 56
- `assistant_manager`: Subgerente (nível 4) - Máximo 20
- `assistant`: Assistente (nível 5) - Máximo 54

**Regras de negócio**:
1. Verificação de permissão baseada na hierarquia
2. O usuário deve existir no sistema (busca por email)
3. O usuário deve ter conta ativa
4. O usuário não pode ter perfil 'dev'
5. O usuário não pode já possuir uma posição na equipe

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Nomear um membro para uma posição na equipe de atendimento
 */
export type createPositionResponse = {
  data: CreatePosition201
  status: number
  headers: Headers
}

export const getCreatePositionUrl = (
  position:
    | 'director'
    | 'supervisor'
    | 'manager'
    | 'assistant_manager'
    | 'assistant',
) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/team/positions/${position}`
}

export const createPosition = async (
  position:
    | 'director'
    | 'supervisor'
    | 'manager'
    | 'assistant_manager'
    | 'assistant',
  createPositionBody: CreatePositionBody,
  options?: RequestInit,
): Promise<createPositionResponse> => {
  return customFetch<Promise<createPositionResponse>>(
    getCreatePositionUrl(position),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createPositionBody),
    },
  )
}

export const getCreatePositionMutationFetcher = (
  position:
    | 'director'
    | 'supervisor'
    | 'manager'
    | 'assistant_manager'
    | 'assistant',
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: CreatePositionBody },
  ): Promise<createPositionResponse> => {
    return createPosition(position, arg, options)
  }
}
export const getCreatePositionMutationKey = (
  position:
    | 'director'
    | 'supervisor'
    | 'manager'
    | 'assistant_manager'
    | 'assistant',
) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/team/positions/${position}`,
  ] as const

export type CreatePositionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPosition>>
>
export type CreatePositionMutationError =
  | CreatePosition400
  | CreatePosition401
  | CreatePosition403
  | CreatePosition404
  | CreatePosition409
  | CreatePosition422
  | CreatePosition500

/**
 * @summary Nomear um membro para uma posição na equipe de atendimento
 */
export const useCreatePosition = <
  TError =
    | CreatePosition400
    | CreatePosition401
    | CreatePosition403
    | CreatePosition404
    | CreatePosition409
    | CreatePosition422
    | CreatePosition500,
>(
  position:
    | 'director'
    | 'supervisor'
    | 'manager'
    | 'assistant_manager'
    | 'assistant',
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof createPosition>>,
      TError,
      Key,
      CreatePositionBody,
      Awaited<ReturnType<typeof createPosition>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreatePositionMutationKey(position)
  const swrFn = getCreatePositionMutationFetcher(position, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint retorna a lista de todos os membros de uma posição específica na equipe de atendimento.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Baseada na hierarquia da equipe:
  - Admin/Dev → pode listar todas as posições
  - Director → pode listar todas as posições
  - Supervisor → pode listar Manager, Assistant Manager e Assistant
  - Manager → pode listar Assistant Manager e Assistant
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Posições disponíveis**:
- `director`: Diretores
- `supervisor`: Supervisores
- `manager`: Gerentes
- `assistant_manager`: Subgerentes
- `assistant`: Assistentes

**Retorno**:
- Lista de membros com dados do usuário (nome, email, avatar)
- Informações de quem nomeou cada membro
- Data de nomeação
- Nível hierárquico

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Listar todos os membros de uma posição na equipe
 */
export type listPositionsResponse = {
  data: ListPositions200
  status: number
  headers: Headers
}

export const getListPositionsUrl = (
  position:
    | 'director'
    | 'supervisor'
    | 'manager'
    | 'assistant_manager'
    | 'assistant',
) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/team/positions/${position}`
}

export const listPositions = async (
  position:
    | 'director'
    | 'supervisor'
    | 'manager'
    | 'assistant_manager'
    | 'assistant',
  options?: RequestInit,
): Promise<listPositionsResponse> => {
  return customFetch<Promise<listPositionsResponse>>(
    getListPositionsUrl(position),
    {
      ...options,
      method: 'GET',
    },
  )
}

export const getListPositionsKey = (
  position:
    | 'director'
    | 'supervisor'
    | 'manager'
    | 'assistant_manager'
    | 'assistant',
) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/team/positions/${position}`,
  ] as const

export type ListPositionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPositions>>
>
export type ListPositionsQueryError =
  | ListPositions400
  | ListPositions401
  | ListPositions403
  | ListPositions422
  | ListPositions500

/**
 * @summary Listar todos os membros de uma posição na equipe
 */
export const useListPositions = <
  TError =
    | ListPositions400
    | ListPositions401
    | ListPositions403
    | ListPositions422
    | ListPositions500,
>(
  position:
    | 'director'
    | 'supervisor'
    | 'manager'
    | 'assistant_manager'
    | 'assistant',
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof listPositions>>,
      TError
    > & { swrKey?: Key; enabled?: boolean }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!position
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getListPositionsKey(position) : null))
  const swrFn = () => listPositions(position, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint retorna a posição de um usuário específico na equipe de atendimento.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Qualquer usuário autenticado pode consultar.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Retorno**:
- Dados da posição do usuário (ou null se não tiver posição)
- Tipo da posição
- Nível hierárquico
- Informações de quem nomeou
- Data de nomeação

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Buscar a posição de um usuário específico
 */
export type getPositionResponse = {
  data: GetPosition200
  status: number
  headers: Headers
}

export const getGetPositionUrl = (userId: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/team/positions/user/${userId}`
}

export const getPosition = async (
  userId: string,
  options?: RequestInit,
): Promise<getPositionResponse> => {
  return customFetch<Promise<getPositionResponse>>(getGetPositionUrl(userId), {
    ...options,
    method: 'GET',
  })
}

export const getGetPositionKey = (userId: string) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/team/positions/user/${userId}`,
  ] as const

export type GetPositionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPosition>>
>
export type GetPositionQueryError =
  | GetPosition400
  | GetPosition401
  | GetPosition403
  | GetPosition422
  | GetPosition500

/**
 * @summary Buscar a posição de um usuário específico
 */
export const useGetPosition = <
  TError =
    | GetPosition400
    | GetPosition401
    | GetPosition403
    | GetPosition422
    | GetPosition500,
>(
  userId: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getPosition>>, TError> & {
      swrKey?: Key
      enabled?: boolean
    }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!userId
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetPositionKey(userId) : null))
  const swrFn = () => getPosition(userId, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite remover a posição de um usuário na equipe de atendimento.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Baseada na hierarquia da equipe:
  - Admin/Dev → pode remover qualquer posição
  - Quem nomeou → pode remover quem nomeou
  - Superiores → podem remover inferiores na hierarquia
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Regras de negócio**:
1. Verificação de permissão baseada na hierarquia
2. O usuário deve possuir uma posição na equipe
3. Ao remover, o usuário volta a ser um usuário comum (sem posição)
4. Não é mantido histórico da remoção

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Remover a posição de um membro da equipe
 */
export type removePositionResponse = {
  data: RemovePosition200
  status: number
  headers: Headers
}

export const getRemovePositionUrl = (userId: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/team/positions/${userId}`
}

export const removePosition = async (
  userId: string,
  options?: RequestInit,
): Promise<removePositionResponse> => {
  return customFetch<Promise<removePositionResponse>>(
    getRemovePositionUrl(userId),
    {
      ...options,
      method: 'DELETE',
    },
  )
}

export const getRemovePositionMutationFetcher = (
  userId: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<removePositionResponse> => {
    return removePosition(userId, options)
  }
}
export const getRemovePositionMutationKey = (userId: string) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/team/positions/${userId}`,
  ] as const

export type RemovePositionMutationResult = NonNullable<
  Awaited<ReturnType<typeof removePosition>>
>
export type RemovePositionMutationError =
  | RemovePosition400
  | RemovePosition401
  | RemovePosition403
  | RemovePosition404
  | RemovePosition422
  | RemovePosition500

/**
 * @summary Remover a posição de um membro da equipe
 */
export const useRemovePosition = <
  TError =
    | RemovePosition400
    | RemovePosition401
    | RemovePosition403
    | RemovePosition404
    | RemovePosition422
    | RemovePosition500,
>(
  userId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof removePosition>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof removePosition>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRemovePositionMutationKey(userId)
  const swrFn = getRemovePositionMutationFetcher(userId, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint retorna a árvore hierárquica completa da equipe de atendimento.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Qualquer usuário autenticado pode visualizar o organograma.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa.

**Estrutura da resposta**:
- `tree`: Árvore hierárquica começando pelos diretores
  - Cada nó possui `subordinates` com seus subordinados diretos
- `stats`: Estatísticas com total e quantidade por posição

**Hierarquia**:
1. Director (nível 1) → nomeia Supervisors
2. Supervisor (nível 2) → nomeia Managers
3. Manager (nível 3) → nomeia Assistant Managers e Assistants
4. Assistant Manager (nível 4) → nomeia Assistants
5. Assistant (nível 5) → base da equipe

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Buscar o organograma completo da equipe
 */
export type getOrganogramResponse = {
  data: GetOrganogram200
  status: number
  headers: Headers
}

export const getGetOrganogramUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/team/organogram`
}

export const getOrganogram = async (
  options?: RequestInit,
): Promise<getOrganogramResponse> => {
  return customFetch<Promise<getOrganogramResponse>>(getGetOrganogramUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetOrganogramKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/team/organogram`] as const

export type GetOrganogramQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrganogram>>
>
export type GetOrganogramQueryError =
  | GetOrganogram400
  | GetOrganogram401
  | GetOrganogram403
  | GetOrganogram500

/**
 * @summary Buscar o organograma completo da equipe
 */
export const useGetOrganogram = <
  TError =
    | GetOrganogram400
    | GetOrganogram401
    | GetOrganogram403
    | GetOrganogram500,
>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getOrganogram>>, TError> & {
    swrKey?: Key
    enabled?: boolean
  }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetOrganogramKey() : null))
  const swrFn = () => getOrganogram(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
