/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
/**
 * Código de status HTTP 500.
 */
export type UpdateRoom500StatusCode =
  (typeof UpdateRoom500StatusCode)[keyof typeof UpdateRoom500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateRoom500Name =
  (typeof UpdateRoom500Name)[keyof typeof UpdateRoom500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type UpdateRoom500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateRoom500Name
  /** Código de status HTTP 500. */
  status_code: UpdateRoom500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type UpdateRoom422StatusCode =
  (typeof UpdateRoom422StatusCode)[keyof typeof UpdateRoom422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateRoom422Name =
  (typeof UpdateRoom422Name)[keyof typeof UpdateRoom422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type UpdateRoom422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type UpdateRoom422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: UpdateRoom422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateRoom422Name
  /** Código de status HTTP 422. */
  status_code: UpdateRoom422StatusCode
}

/**
 * Código de status HTTP 404.
 */
export type UpdateRoom404StatusCode =
  (typeof UpdateRoom404StatusCode)[keyof typeof UpdateRoom404StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom404StatusCode = {
  NUMBER_404: 404,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateRoom404Name =
  (typeof UpdateRoom404Name)[keyof typeof UpdateRoom404Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom404Name = {
  NotFoundError: 'NotFoundError',
} as const

/**
 * Schema to represent Not Found errors (HTTP 404)
 */
export type UpdateRoom404 = {
  /** Ação recomendada para o recurso não encontrado. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o recurso não foi encontrado. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateRoom404Name
  /** Código de status HTTP 404. */
  status_code: UpdateRoom404StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type UpdateRoom403StatusCode =
  (typeof UpdateRoom403StatusCode)[keyof typeof UpdateRoom403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateRoom403Name =
  (typeof UpdateRoom403Name)[keyof typeof UpdateRoom403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type UpdateRoom403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateRoom403Name
  /** Código de status HTTP 403. */
  status_code: UpdateRoom403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type UpdateRoom401StatusCode =
  (typeof UpdateRoom401StatusCode)[keyof typeof UpdateRoom401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateRoom401Name =
  (typeof UpdateRoom401Name)[keyof typeof UpdateRoom401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type UpdateRoom401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateRoom401Name
  /** Código de status HTTP 401. */
  status_code: UpdateRoom401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type UpdateRoom400StatusCode =
  (typeof UpdateRoom400StatusCode)[keyof typeof UpdateRoom400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateRoom400Name =
  (typeof UpdateRoom400Name)[keyof typeof UpdateRoom400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoom400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type UpdateRoom400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateRoom400Name
  /** Código de status HTTP 400. */
  status_code: UpdateRoom400StatusCode
}

export type UpdateRoom200Room = {
  capacidade: number
  createdAt: string
  /** @nullable */
  description: string | null
  id: string
  imagens: string[]
  isActive: boolean
  name: string
  recursos: string[]
  updatedAt: string
  userId: string
}

/**
 * Sala atualizada com sucesso
 */
export type UpdateRoom200 = {
  message: string
  room: UpdateRoom200Room
}

export type UpdateRoomBody = {
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  capacidade?: number
  /**
   * @maxLength 500
   * @nullable
   */
  description?: string | null
  /** @maxItems 5 */
  imagens?: string[]
  isActive?: boolean
  /**
   * @minLength 3
   * @maxLength 100
   */
  name?: string
  recursos?: string[]
}

/**
 * Código de status HTTP 500.
 */
export type GetRoom500StatusCode =
  (typeof GetRoom500StatusCode)[keyof typeof GetRoom500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type GetRoom500Name =
  (typeof GetRoom500Name)[keyof typeof GetRoom500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type GetRoom500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: GetRoom500Name
  /** Código de status HTTP 500. */
  status_code: GetRoom500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type GetRoom422StatusCode =
  (typeof GetRoom422StatusCode)[keyof typeof GetRoom422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type GetRoom422Name =
  (typeof GetRoom422Name)[keyof typeof GetRoom422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type GetRoom422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type GetRoom422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: GetRoom422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: GetRoom422Name
  /** Código de status HTTP 422. */
  status_code: GetRoom422StatusCode
}

/**
 * Código de status HTTP 404.
 */
export type GetRoom404StatusCode =
  (typeof GetRoom404StatusCode)[keyof typeof GetRoom404StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom404StatusCode = {
  NUMBER_404: 404,
} as const

/**
 * Nome fixo do erro.
 */
export type GetRoom404Name =
  (typeof GetRoom404Name)[keyof typeof GetRoom404Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom404Name = {
  NotFoundError: 'NotFoundError',
} as const

/**
 * Schema to represent Not Found errors (HTTP 404)
 */
export type GetRoom404 = {
  /** Ação recomendada para o recurso não encontrado. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o recurso não foi encontrado. */
  message: string
  /** Nome fixo do erro. */
  name: GetRoom404Name
  /** Código de status HTTP 404. */
  status_code: GetRoom404StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type GetRoom403StatusCode =
  (typeof GetRoom403StatusCode)[keyof typeof GetRoom403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type GetRoom403Name =
  (typeof GetRoom403Name)[keyof typeof GetRoom403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type GetRoom403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: GetRoom403Name
  /** Código de status HTTP 403. */
  status_code: GetRoom403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type GetRoom401StatusCode =
  (typeof GetRoom401StatusCode)[keyof typeof GetRoom401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type GetRoom401Name =
  (typeof GetRoom401Name)[keyof typeof GetRoom401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type GetRoom401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: GetRoom401Name
  /** Código de status HTTP 401. */
  status_code: GetRoom401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type GetRoom400StatusCode =
  (typeof GetRoom400StatusCode)[keyof typeof GetRoom400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type GetRoom400Name =
  (typeof GetRoom400Name)[keyof typeof GetRoom400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoom400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type GetRoom400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: GetRoom400Name
  /** Código de status HTTP 400. */
  status_code: GetRoom400StatusCode
}

export type GetRoom200Room = {
  capacidade: number
  createdAt: string
  /** @nullable */
  description: string | null
  id: string
  imagens: string[]
  isActive: boolean
  name: string
  recursos: string[]
  updatedAt: string
  userId: string
  userName: string
}

/**
 * Detalhes da sala
 */
export type GetRoom200 = {
  room: GetRoom200Room
}

/**
 * Código de status HTTP 500.
 */
export type DeleteRoom500StatusCode =
  (typeof DeleteRoom500StatusCode)[keyof typeof DeleteRoom500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteRoom500Name =
  (typeof DeleteRoom500Name)[keyof typeof DeleteRoom500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type DeleteRoom500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteRoom500Name
  /** Código de status HTTP 500. */
  status_code: DeleteRoom500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type DeleteRoom422StatusCode =
  (typeof DeleteRoom422StatusCode)[keyof typeof DeleteRoom422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteRoom422Name =
  (typeof DeleteRoom422Name)[keyof typeof DeleteRoom422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type DeleteRoom422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type DeleteRoom422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: DeleteRoom422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteRoom422Name
  /** Código de status HTTP 422. */
  status_code: DeleteRoom422StatusCode
}

/**
 * Código de status HTTP 404.
 */
export type DeleteRoom404StatusCode =
  (typeof DeleteRoom404StatusCode)[keyof typeof DeleteRoom404StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom404StatusCode = {
  NUMBER_404: 404,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteRoom404Name =
  (typeof DeleteRoom404Name)[keyof typeof DeleteRoom404Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom404Name = {
  NotFoundError: 'NotFoundError',
} as const

/**
 * Schema to represent Not Found errors (HTTP 404)
 */
export type DeleteRoom404 = {
  /** Ação recomendada para o recurso não encontrado. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o recurso não foi encontrado. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteRoom404Name
  /** Código de status HTTP 404. */
  status_code: DeleteRoom404StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type DeleteRoom403StatusCode =
  (typeof DeleteRoom403StatusCode)[keyof typeof DeleteRoom403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteRoom403Name =
  (typeof DeleteRoom403Name)[keyof typeof DeleteRoom403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type DeleteRoom403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteRoom403Name
  /** Código de status HTTP 403. */
  status_code: DeleteRoom403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type DeleteRoom401StatusCode =
  (typeof DeleteRoom401StatusCode)[keyof typeof DeleteRoom401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteRoom401Name =
  (typeof DeleteRoom401Name)[keyof typeof DeleteRoom401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type DeleteRoom401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteRoom401Name
  /** Código de status HTTP 401. */
  status_code: DeleteRoom401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type DeleteRoom400StatusCode =
  (typeof DeleteRoom400StatusCode)[keyof typeof DeleteRoom400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteRoom400Name =
  (typeof DeleteRoom400Name)[keyof typeof DeleteRoom400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteRoom400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type DeleteRoom400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteRoom400Name
  /** Código de status HTTP 400. */
  status_code: DeleteRoom400StatusCode
}

/**
 * Sala excluída com sucesso
 */
export type DeleteRoom200 = {
  message: string
}

/**
 * Código de status HTTP 500.
 */
export type ListRooms500StatusCode =
  (typeof ListRooms500StatusCode)[keyof typeof ListRooms500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRooms500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type ListRooms500Name =
  (typeof ListRooms500Name)[keyof typeof ListRooms500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRooms500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type ListRooms500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: ListRooms500Name
  /** Código de status HTTP 500. */
  status_code: ListRooms500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type ListRooms422StatusCode =
  (typeof ListRooms422StatusCode)[keyof typeof ListRooms422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRooms422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type ListRooms422Name =
  (typeof ListRooms422Name)[keyof typeof ListRooms422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRooms422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type ListRooms422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type ListRooms422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: ListRooms422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: ListRooms422Name
  /** Código de status HTTP 422. */
  status_code: ListRooms422StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type ListRooms403StatusCode =
  (typeof ListRooms403StatusCode)[keyof typeof ListRooms403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRooms403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type ListRooms403Name =
  (typeof ListRooms403Name)[keyof typeof ListRooms403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRooms403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type ListRooms403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: ListRooms403Name
  /** Código de status HTTP 403. */
  status_code: ListRooms403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type ListRooms401StatusCode =
  (typeof ListRooms401StatusCode)[keyof typeof ListRooms401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRooms401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type ListRooms401Name =
  (typeof ListRooms401Name)[keyof typeof ListRooms401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRooms401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type ListRooms401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: ListRooms401Name
  /** Código de status HTTP 401. */
  status_code: ListRooms401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type ListRooms400StatusCode =
  (typeof ListRooms400StatusCode)[keyof typeof ListRooms400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRooms400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type ListRooms400Name =
  (typeof ListRooms400Name)[keyof typeof ListRooms400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRooms400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type ListRooms400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: ListRooms400Name
  /** Código de status HTTP 400. */
  status_code: ListRooms400StatusCode
}

export type ListRooms200RoomsItem = {
  capacidade: number
  createdAt: string
  /** @nullable */
  description: string | null
  id: string
  imagens: string[]
  isActive: boolean
  name: string
  recursos: string[]
  updatedAt: string
  userId: string
  userName: string
}

/**
 * Lista de salas
 */
export type ListRooms200 = {
  currentPage: number
  rooms: ListRooms200RoomsItem[]
  totalCount: number
  totalPages: number
}

export type ListRoomsParams = {
  page?: string
  pageSize?: string
  searchTerm?: string
  isActive?: string
  capacidade?: string
  includeDeleted?: string
}

/**
 * Código de status HTTP 500.
 */
export type CreateRoom500StatusCode =
  (typeof CreateRoom500StatusCode)[keyof typeof CreateRoom500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateRoom500Name =
  (typeof CreateRoom500Name)[keyof typeof CreateRoom500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type CreateRoom500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: CreateRoom500Name
  /** Código de status HTTP 500. */
  status_code: CreateRoom500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type CreateRoom422StatusCode =
  (typeof CreateRoom422StatusCode)[keyof typeof CreateRoom422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateRoom422Name =
  (typeof CreateRoom422Name)[keyof typeof CreateRoom422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type CreateRoom422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type CreateRoom422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: CreateRoom422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: CreateRoom422Name
  /** Código de status HTTP 422. */
  status_code: CreateRoom422StatusCode
}

/**
 * Código de status HTTP 409.
 */
export type CreateRoom409StatusCode =
  (typeof CreateRoom409StatusCode)[keyof typeof CreateRoom409StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom409StatusCode = {
  NUMBER_409: 409,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateRoom409Name =
  (typeof CreateRoom409Name)[keyof typeof CreateRoom409Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom409Name = {
  ConflictError: 'ConflictError',
} as const

/**
 * Schema to represent Conflict errors (HTTP 409)
 */
export type CreateRoom409 = {
  /** Ação recomendada para resolver o conflito. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que houve um conflito. */
  message: string
  /** Nome fixo do erro. */
  name: CreateRoom409Name
  /** Código de status HTTP 409. */
  status_code: CreateRoom409StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type CreateRoom403StatusCode =
  (typeof CreateRoom403StatusCode)[keyof typeof CreateRoom403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateRoom403Name =
  (typeof CreateRoom403Name)[keyof typeof CreateRoom403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type CreateRoom403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: CreateRoom403Name
  /** Código de status HTTP 403. */
  status_code: CreateRoom403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type CreateRoom401StatusCode =
  (typeof CreateRoom401StatusCode)[keyof typeof CreateRoom401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateRoom401Name =
  (typeof CreateRoom401Name)[keyof typeof CreateRoom401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type CreateRoom401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: CreateRoom401Name
  /** Código de status HTTP 401. */
  status_code: CreateRoom401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type CreateRoom400StatusCode =
  (typeof CreateRoom400StatusCode)[keyof typeof CreateRoom400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateRoom400Name =
  (typeof CreateRoom400Name)[keyof typeof CreateRoom400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoom400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type CreateRoom400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: CreateRoom400Name
  /** Código de status HTTP 400. */
  status_code: CreateRoom400StatusCode
}

export type CreateRoom201Room = {
  capacidade: number
  createdAt: string
  /** @nullable */
  description: string | null
  id: string
  imagens: string[]
  isActive: boolean
  name: string
  recursos: string[]
  updatedAt: string
  userId: string
  userName: string
}

/**
 * Sala criada com sucesso
 */
export type CreateRoom201 = {
  message: string
  room: CreateRoom201Room
}

export type CreateRoomBody = {
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  capacidade: number
  /**
   * @maxLength 500
   * @nullable
   */
  description?: string | null
  /** @maxItems 5 */
  imagens?: string[]
  isActive?: boolean
  /**
   * @minLength 3
   * @maxLength 100
   */
  name: string
  recursos?: string[]
}

/**
 * Código de status HTTP 500.
 */
export type DeleteImage500StatusCode =
  (typeof DeleteImage500StatusCode)[keyof typeof DeleteImage500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteImage500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteImage500Name =
  (typeof DeleteImage500Name)[keyof typeof DeleteImage500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteImage500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type DeleteImage500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteImage500Name
  /** Código de status HTTP 500. */
  status_code: DeleteImage500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type DeleteImage422StatusCode =
  (typeof DeleteImage422StatusCode)[keyof typeof DeleteImage422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteImage422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteImage422Name =
  (typeof DeleteImage422Name)[keyof typeof DeleteImage422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteImage422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type DeleteImage422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type DeleteImage422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: DeleteImage422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteImage422Name
  /** Código de status HTTP 422. */
  status_code: DeleteImage422StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type DeleteImage403StatusCode =
  (typeof DeleteImage403StatusCode)[keyof typeof DeleteImage403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteImage403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteImage403Name =
  (typeof DeleteImage403Name)[keyof typeof DeleteImage403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteImage403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type DeleteImage403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteImage403Name
  /** Código de status HTTP 403. */
  status_code: DeleteImage403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type DeleteImage401StatusCode =
  (typeof DeleteImage401StatusCode)[keyof typeof DeleteImage401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteImage401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteImage401Name =
  (typeof DeleteImage401Name)[keyof typeof DeleteImage401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteImage401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type DeleteImage401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteImage401Name
  /** Código de status HTTP 401. */
  status_code: DeleteImage401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type DeleteImage400StatusCode =
  (typeof DeleteImage400StatusCode)[keyof typeof DeleteImage400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteImage400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteImage400Name =
  (typeof DeleteImage400Name)[keyof typeof DeleteImage400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteImage400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type DeleteImage400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteImage400Name
  /** Código de status HTTP 400. */
  status_code: DeleteImage400StatusCode
}

/**
 * Image deleted successfully
 */
export type DeleteImage200 = {
  message: string
}

export type DeleteImageBody = {
  file: Blob
}

/**
 * Código de status HTTP 500.
 */
export type UploadImage500StatusCode =
  (typeof UploadImage500StatusCode)[keyof typeof UploadImage500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadImage500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type UploadImage500Name =
  (typeof UploadImage500Name)[keyof typeof UploadImage500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadImage500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type UploadImage500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: UploadImage500Name
  /** Código de status HTTP 500. */
  status_code: UploadImage500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type UploadImage422StatusCode =
  (typeof UploadImage422StatusCode)[keyof typeof UploadImage422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadImage422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type UploadImage422Name =
  (typeof UploadImage422Name)[keyof typeof UploadImage422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadImage422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type UploadImage422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type UploadImage422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: UploadImage422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: UploadImage422Name
  /** Código de status HTTP 422. */
  status_code: UploadImage422StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type UploadImage403StatusCode =
  (typeof UploadImage403StatusCode)[keyof typeof UploadImage403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadImage403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type UploadImage403Name =
  (typeof UploadImage403Name)[keyof typeof UploadImage403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadImage403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type UploadImage403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: UploadImage403Name
  /** Código de status HTTP 403. */
  status_code: UploadImage403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type UploadImage401StatusCode =
  (typeof UploadImage401StatusCode)[keyof typeof UploadImage401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadImage401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type UploadImage401Name =
  (typeof UploadImage401Name)[keyof typeof UploadImage401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadImage401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type UploadImage401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: UploadImage401Name
  /** Código de status HTTP 401. */
  status_code: UploadImage401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type UploadImage400StatusCode =
  (typeof UploadImage400StatusCode)[keyof typeof UploadImage400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadImage400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type UploadImage400Name =
  (typeof UploadImage400Name)[keyof typeof UploadImage400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadImage400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type UploadImage400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: UploadImage400Name
  /** Código de status HTTP 400. */
  status_code: UploadImage400StatusCode
}

/**
 * Image uploaded successfully
 */
export type UploadImage201 = {
  imagePath: string
  message: string
}

export type UploadImageBody = {
  file: Blob
}

export type UploadImageParams = {
  /**
   * Group of asset. Ex: 'avatar', 'logo', 'product'
   */
  group: string
  /**
   * Subtitle of asset. Ex: 'profile', 'og', 'drink'
   */
  subtitle?: string
  /**
   * Custom folder to store the image. Default: userId
   */
  folder?: string
}

/**
 * Código de status HTTP 500.
 */
export type UpdateUser500StatusCode =
  (typeof UpdateUser500StatusCode)[keyof typeof UpdateUser500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateUser500Name =
  (typeof UpdateUser500Name)[keyof typeof UpdateUser500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type UpdateUser500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateUser500Name
  /** Código de status HTTP 500. */
  status_code: UpdateUser500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type UpdateUser422StatusCode =
  (typeof UpdateUser422StatusCode)[keyof typeof UpdateUser422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateUser422Name =
  (typeof UpdateUser422Name)[keyof typeof UpdateUser422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type UpdateUser422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type UpdateUser422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: UpdateUser422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateUser422Name
  /** Código de status HTTP 422. */
  status_code: UpdateUser422StatusCode
}

/**
 * Código de status HTTP 404.
 */
export type UpdateUser404StatusCode =
  (typeof UpdateUser404StatusCode)[keyof typeof UpdateUser404StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser404StatusCode = {
  NUMBER_404: 404,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateUser404Name =
  (typeof UpdateUser404Name)[keyof typeof UpdateUser404Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser404Name = {
  NotFoundError: 'NotFoundError',
} as const

/**
 * Schema to represent Not Found errors (HTTP 404)
 */
export type UpdateUser404 = {
  /** Ação recomendada para o recurso não encontrado. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o recurso não foi encontrado. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateUser404Name
  /** Código de status HTTP 404. */
  status_code: UpdateUser404StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type UpdateUser403StatusCode =
  (typeof UpdateUser403StatusCode)[keyof typeof UpdateUser403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateUser403Name =
  (typeof UpdateUser403Name)[keyof typeof UpdateUser403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type UpdateUser403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateUser403Name
  /** Código de status HTTP 403. */
  status_code: UpdateUser403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type UpdateUser401StatusCode =
  (typeof UpdateUser401StatusCode)[keyof typeof UpdateUser401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateUser401Name =
  (typeof UpdateUser401Name)[keyof typeof UpdateUser401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type UpdateUser401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateUser401Name
  /** Código de status HTTP 401. */
  status_code: UpdateUser401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type UpdateUser400StatusCode =
  (typeof UpdateUser400StatusCode)[keyof typeof UpdateUser400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type UpdateUser400Name =
  (typeof UpdateUser400Name)[keyof typeof UpdateUser400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type UpdateUser400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: UpdateUser400Name
  /** Código de status HTTP 400. */
  status_code: UpdateUser400StatusCode
}

export type UpdateUser200UserRole =
  (typeof UpdateUser200UserRole)[keyof typeof UpdateUser200UserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUser200UserRole = {
  admin: 'admin',
  user: 'user',
  dev: 'dev',
} as const

export type UpdateUser200User = {
  accountStatus: boolean
  /** @nullable */
  avatar: string | null
  email: string
  id: string
  /** @nullable */
  name: string | null
  /** @nullable */
  nickName: string | null
  passwordResetRequired: boolean
  /** @nullable */
  phone: string | null
  role: UpdateUser200UserRole
}

/**
 * Usuário atualizado com sucesso
 */
export type UpdateUser200 = {
  message: string
  user: UpdateUser200User
}

export type UpdateUserBodyRole =
  (typeof UpdateUserBodyRole)[keyof typeof UpdateUserBodyRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserBodyRole = {
  admin: 'admin',
  user: 'user',
  dev: 'dev',
} as const

export type UpdateUserBody = {
  accountStatus?: boolean
  /** @nullable */
  avatar?: string | null
  /**
   * @minLength 3
   * @maxLength 254
   */
  email?: string
  /**
   * @minLength 2
   * @maxLength 100
   * @pattern ^\S+\s+\S+
   */
  name?: string
  /** @nullable */
  nickName?: string | null
  passwordResetRequired?: boolean
  /** @nullable */
  phone?: string | null
  role?: UpdateUserBodyRole
}

/**
 * Código de status HTTP 500.
 */
export type GetUser500StatusCode =
  (typeof GetUser500StatusCode)[keyof typeof GetUser500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type GetUser500Name =
  (typeof GetUser500Name)[keyof typeof GetUser500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type GetUser500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: GetUser500Name
  /** Código de status HTTP 500. */
  status_code: GetUser500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type GetUser422StatusCode =
  (typeof GetUser422StatusCode)[keyof typeof GetUser422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type GetUser422Name =
  (typeof GetUser422Name)[keyof typeof GetUser422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type GetUser422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type GetUser422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: GetUser422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: GetUser422Name
  /** Código de status HTTP 422. */
  status_code: GetUser422StatusCode
}

/**
 * Código de status HTTP 404.
 */
export type GetUser404StatusCode =
  (typeof GetUser404StatusCode)[keyof typeof GetUser404StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser404StatusCode = {
  NUMBER_404: 404,
} as const

/**
 * Nome fixo do erro.
 */
export type GetUser404Name =
  (typeof GetUser404Name)[keyof typeof GetUser404Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser404Name = {
  NotFoundError: 'NotFoundError',
} as const

/**
 * Schema to represent Not Found errors (HTTP 404)
 */
export type GetUser404 = {
  /** Ação recomendada para o recurso não encontrado. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o recurso não foi encontrado. */
  message: string
  /** Nome fixo do erro. */
  name: GetUser404Name
  /** Código de status HTTP 404. */
  status_code: GetUser404StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type GetUser403StatusCode =
  (typeof GetUser403StatusCode)[keyof typeof GetUser403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type GetUser403Name =
  (typeof GetUser403Name)[keyof typeof GetUser403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type GetUser403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: GetUser403Name
  /** Código de status HTTP 403. */
  status_code: GetUser403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type GetUser401StatusCode =
  (typeof GetUser401StatusCode)[keyof typeof GetUser401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type GetUser401Name =
  (typeof GetUser401Name)[keyof typeof GetUser401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type GetUser401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: GetUser401Name
  /** Código de status HTTP 401. */
  status_code: GetUser401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type GetUser400StatusCode =
  (typeof GetUser400StatusCode)[keyof typeof GetUser400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type GetUser400Name =
  (typeof GetUser400Name)[keyof typeof GetUser400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type GetUser400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: GetUser400Name
  /** Código de status HTTP 400. */
  status_code: GetUser400StatusCode
}

export type GetUser200UserRole =
  (typeof GetUser200UserRole)[keyof typeof GetUser200UserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUser200UserRole = {
  admin: 'admin',
  user: 'user',
  dev: 'dev',
} as const

export type GetUser200User = {
  accountStatus: boolean
  /** @nullable */
  avatar: string | null
  email: string
  id: string
  /** @nullable */
  name: string | null
  /** @nullable */
  nickName: string | null
  passwordResetRequired: boolean
  /** @nullable */
  phone: string | null
  role: GetUser200UserRole
}

/**
 * Dados do usuário recuperados com sucesso
 */
export type GetUser200 = {
  message: string
  user: GetUser200User
}

/**
 * Código de status HTTP 500.
 */
export type DeleteUser500StatusCode =
  (typeof DeleteUser500StatusCode)[keyof typeof DeleteUser500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteUser500Name =
  (typeof DeleteUser500Name)[keyof typeof DeleteUser500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type DeleteUser500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteUser500Name
  /** Código de status HTTP 500. */
  status_code: DeleteUser500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type DeleteUser422StatusCode =
  (typeof DeleteUser422StatusCode)[keyof typeof DeleteUser422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteUser422Name =
  (typeof DeleteUser422Name)[keyof typeof DeleteUser422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type DeleteUser422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type DeleteUser422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: DeleteUser422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteUser422Name
  /** Código de status HTTP 422. */
  status_code: DeleteUser422StatusCode
}

/**
 * Código de status HTTP 409.
 */
export type DeleteUser409StatusCode =
  (typeof DeleteUser409StatusCode)[keyof typeof DeleteUser409StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser409StatusCode = {
  NUMBER_409: 409,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteUser409Name =
  (typeof DeleteUser409Name)[keyof typeof DeleteUser409Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser409Name = {
  ConflictError: 'ConflictError',
} as const

/**
 * Schema to represent Conflict errors (HTTP 409)
 */
export type DeleteUser409 = {
  /** Ação recomendada para resolver o conflito. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que houve um conflito. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteUser409Name
  /** Código de status HTTP 409. */
  status_code: DeleteUser409StatusCode
}

/**
 * Código de status HTTP 404.
 */
export type DeleteUser404StatusCode =
  (typeof DeleteUser404StatusCode)[keyof typeof DeleteUser404StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser404StatusCode = {
  NUMBER_404: 404,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteUser404Name =
  (typeof DeleteUser404Name)[keyof typeof DeleteUser404Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser404Name = {
  NotFoundError: 'NotFoundError',
} as const

/**
 * Schema to represent Not Found errors (HTTP 404)
 */
export type DeleteUser404 = {
  /** Ação recomendada para o recurso não encontrado. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o recurso não foi encontrado. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteUser404Name
  /** Código de status HTTP 404. */
  status_code: DeleteUser404StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type DeleteUser403StatusCode =
  (typeof DeleteUser403StatusCode)[keyof typeof DeleteUser403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteUser403Name =
  (typeof DeleteUser403Name)[keyof typeof DeleteUser403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type DeleteUser403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteUser403Name
  /** Código de status HTTP 403. */
  status_code: DeleteUser403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type DeleteUser401StatusCode =
  (typeof DeleteUser401StatusCode)[keyof typeof DeleteUser401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteUser401Name =
  (typeof DeleteUser401Name)[keyof typeof DeleteUser401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type DeleteUser401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteUser401Name
  /** Código de status HTTP 401. */
  status_code: DeleteUser401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type DeleteUser400StatusCode =
  (typeof DeleteUser400StatusCode)[keyof typeof DeleteUser400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type DeleteUser400Name =
  (typeof DeleteUser400Name)[keyof typeof DeleteUser400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type DeleteUser400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: DeleteUser400Name
  /** Código de status HTTP 400. */
  status_code: DeleteUser400StatusCode
}

/**
 * Usuário excluído com sucesso
 */
export type DeleteUser200 = {
  message: string
  userId: string
}

/**
 * Código de status HTTP 500.
 */
export type ListUsers500StatusCode =
  (typeof ListUsers500StatusCode)[keyof typeof ListUsers500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type ListUsers500Name =
  (typeof ListUsers500Name)[keyof typeof ListUsers500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type ListUsers500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: ListUsers500Name
  /** Código de status HTTP 500. */
  status_code: ListUsers500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type ListUsers422StatusCode =
  (typeof ListUsers422StatusCode)[keyof typeof ListUsers422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type ListUsers422Name =
  (typeof ListUsers422Name)[keyof typeof ListUsers422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type ListUsers422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type ListUsers422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: ListUsers422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: ListUsers422Name
  /** Código de status HTTP 422. */
  status_code: ListUsers422StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type ListUsers403StatusCode =
  (typeof ListUsers403StatusCode)[keyof typeof ListUsers403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type ListUsers403Name =
  (typeof ListUsers403Name)[keyof typeof ListUsers403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type ListUsers403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: ListUsers403Name
  /** Código de status HTTP 403. */
  status_code: ListUsers403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type ListUsers401StatusCode =
  (typeof ListUsers401StatusCode)[keyof typeof ListUsers401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type ListUsers401Name =
  (typeof ListUsers401Name)[keyof typeof ListUsers401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type ListUsers401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: ListUsers401Name
  /** Código de status HTTP 401. */
  status_code: ListUsers401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type ListUsers400StatusCode =
  (typeof ListUsers400StatusCode)[keyof typeof ListUsers400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type ListUsers400Name =
  (typeof ListUsers400Name)[keyof typeof ListUsers400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type ListUsers400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: ListUsers400Name
  /** Código de status HTTP 400. */
  status_code: ListUsers400StatusCode
}

export type ListUsers201UsersItemRole =
  (typeof ListUsers201UsersItemRole)[keyof typeof ListUsers201UsersItemRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsers201UsersItemRole = {
  admin: 'admin',
  user: 'user',
  dev: 'dev',
} as const

export type ListUsers201UsersItem = {
  accountStatus: boolean
  /** @nullable */
  avatar: string | null
  createdAt: string
  email: string
  id: string
  /** @nullable */
  name: string | null
  /** @nullable */
  nickName: string | null
  passwordResetRequired: boolean
  /** @nullable */
  phone: string | null
  role: ListUsers201UsersItemRole
}

/**
 * Lista de usuários recuperada com sucesso
 */
export type ListUsers201 = {
  currentPage: number
  message: string
  totalPages: number
  users: ListUsers201UsersItem[]
}

export type ListUsersRole = (typeof ListUsersRole)[keyof typeof ListUsersRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsersRole = {
  admin: 'admin',
  user: 'user',
  dev: 'dev',
} as const

export type ListUsersParams = {
  page?: string
  pageSize?: string
  search?: string
  role?: ListUsersRole
  accountStatus?: string
}

/**
 * Código de status HTTP 500.
 */
export type CreateUser500StatusCode =
  (typeof CreateUser500StatusCode)[keyof typeof CreateUser500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateUser500Name =
  (typeof CreateUser500Name)[keyof typeof CreateUser500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type CreateUser500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: CreateUser500Name
  /** Código de status HTTP 500. */
  status_code: CreateUser500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type CreateUser422StatusCode =
  (typeof CreateUser422StatusCode)[keyof typeof CreateUser422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateUser422Name =
  (typeof CreateUser422Name)[keyof typeof CreateUser422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type CreateUser422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type CreateUser422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: CreateUser422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: CreateUser422Name
  /** Código de status HTTP 422. */
  status_code: CreateUser422StatusCode
}

/**
 * Código de status HTTP 409.
 */
export type CreateUser409StatusCode =
  (typeof CreateUser409StatusCode)[keyof typeof CreateUser409StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser409StatusCode = {
  NUMBER_409: 409,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateUser409Name =
  (typeof CreateUser409Name)[keyof typeof CreateUser409Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser409Name = {
  ConflictError: 'ConflictError',
} as const

/**
 * Schema to represent Conflict errors (HTTP 409)
 */
export type CreateUser409 = {
  /** Ação recomendada para resolver o conflito. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que houve um conflito. */
  message: string
  /** Nome fixo do erro. */
  name: CreateUser409Name
  /** Código de status HTTP 409. */
  status_code: CreateUser409StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type CreateUser403StatusCode =
  (typeof CreateUser403StatusCode)[keyof typeof CreateUser403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateUser403Name =
  (typeof CreateUser403Name)[keyof typeof CreateUser403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type CreateUser403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: CreateUser403Name
  /** Código de status HTTP 403. */
  status_code: CreateUser403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type CreateUser401StatusCode =
  (typeof CreateUser401StatusCode)[keyof typeof CreateUser401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateUser401Name =
  (typeof CreateUser401Name)[keyof typeof CreateUser401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type CreateUser401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: CreateUser401Name
  /** Código de status HTTP 401. */
  status_code: CreateUser401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type CreateUser400StatusCode =
  (typeof CreateUser400StatusCode)[keyof typeof CreateUser400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type CreateUser400Name =
  (typeof CreateUser400Name)[keyof typeof CreateUser400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type CreateUser400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: CreateUser400Name
  /** Código de status HTTP 400. */
  status_code: CreateUser400StatusCode
}

export type CreateUser201UserRole =
  (typeof CreateUser201UserRole)[keyof typeof CreateUser201UserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUser201UserRole = {
  admin: 'admin',
  user: 'user',
  dev: 'dev',
} as const

export type CreateUser201User = {
  accountStatus: boolean
  /** @nullable */
  avatar: string | null
  email: string
  id: string
  /** @nullable */
  name: string | null
  /** @nullable */
  nickName: string | null
  passwordResetRequired: boolean
  /** @nullable */
  phone: string | null
  role: CreateUser201UserRole
}

/**
 * Usuário criado com sucesso
 */
export type CreateUser201 = {
  message: string
  user: CreateUser201User
}

export type CreateUserBodyRole =
  (typeof CreateUserBodyRole)[keyof typeof CreateUserBodyRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserBodyRole = {
  admin: 'admin',
  user: 'user',
  dev: 'dev',
} as const

export type CreateUserBody = {
  /**
   * @minLength 3
   * @maxLength 254
   */
  email: string
  /**
   * @minLength 2
   * @maxLength 100
   * @pattern ^\S+\s+\S+
   */
  name: string
  role?: CreateUserBodyRole
}

/**
 * Código de status HTTP 500.
 */
export type UserMe500StatusCode =
  (typeof UserMe500StatusCode)[keyof typeof UserMe500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserMe500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type UserMe500Name = (typeof UserMe500Name)[keyof typeof UserMe500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserMe500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type UserMe500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: UserMe500Name
  /** Código de status HTTP 500. */
  status_code: UserMe500StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type UserMe403StatusCode =
  (typeof UserMe403StatusCode)[keyof typeof UserMe403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserMe403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type UserMe403Name = (typeof UserMe403Name)[keyof typeof UserMe403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserMe403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type UserMe403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: UserMe403Name
  /** Código de status HTTP 403. */
  status_code: UserMe403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type UserMe401StatusCode =
  (typeof UserMe401StatusCode)[keyof typeof UserMe401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserMe401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type UserMe401Name = (typeof UserMe401Name)[keyof typeof UserMe401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserMe401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type UserMe401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: UserMe401Name
  /** Código de status HTTP 401. */
  status_code: UserMe401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type UserMe400StatusCode =
  (typeof UserMe400StatusCode)[keyof typeof UserMe400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserMe400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type UserMe400Name = (typeof UserMe400Name)[keyof typeof UserMe400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserMe400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type UserMe400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: UserMe400Name
  /** Código de status HTTP 400. */
  status_code: UserMe400StatusCode
}

export type UserMe201UserRole =
  (typeof UserMe201UserRole)[keyof typeof UserMe201UserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserMe201UserRole = {
  admin: 'admin',
  user: 'user',
  dev: 'dev',
} as const

export type UserMe201User = {
  accountStatus: boolean
  /** @nullable */
  avatar: string | null
  calendarAuthorized: boolean
  email: string
  id: string
  /** @nullable */
  name: string | null
  /** @nullable */
  nickName: string | null
  passwordResetRequired: boolean
  /** @nullable */
  phone: string | null
  role: UserMe201UserRole
}

/**
 * Dados do usuário recuperados com sucesso
 */
export type UserMe201 = {
  message: string
  user: UserMe201User
}

/**
 * Código de status HTTP 500.
 */
export type RefreshUserSession500StatusCode =
  (typeof RefreshUserSession500StatusCode)[keyof typeof RefreshUserSession500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshUserSession500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type RefreshUserSession500Name =
  (typeof RefreshUserSession500Name)[keyof typeof RefreshUserSession500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshUserSession500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type RefreshUserSession500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: RefreshUserSession500Name
  /** Código de status HTTP 500. */
  status_code: RefreshUserSession500StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type RefreshUserSession403StatusCode =
  (typeof RefreshUserSession403StatusCode)[keyof typeof RefreshUserSession403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshUserSession403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type RefreshUserSession403Name =
  (typeof RefreshUserSession403Name)[keyof typeof RefreshUserSession403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshUserSession403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type RefreshUserSession403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: RefreshUserSession403Name
  /** Código de status HTTP 403. */
  status_code: RefreshUserSession403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type RefreshUserSession401StatusCode =
  (typeof RefreshUserSession401StatusCode)[keyof typeof RefreshUserSession401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshUserSession401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type RefreshUserSession401Name =
  (typeof RefreshUserSession401Name)[keyof typeof RefreshUserSession401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshUserSession401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type RefreshUserSession401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: RefreshUserSession401Name
  /** Código de status HTTP 401. */
  status_code: RefreshUserSession401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type RefreshUserSession400StatusCode =
  (typeof RefreshUserSession400StatusCode)[keyof typeof RefreshUserSession400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshUserSession400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type RefreshUserSession400Name =
  (typeof RefreshUserSession400Name)[keyof typeof RefreshUserSession400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshUserSession400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type RefreshUserSession400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: RefreshUserSession400Name
  /** Código de status HTTP 400. */
  status_code: RefreshUserSession400StatusCode
}

export type RefreshUserSession201UserRole =
  (typeof RefreshUserSession201UserRole)[keyof typeof RefreshUserSession201UserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshUserSession201UserRole = {
  admin: 'admin',
  user: 'user',
  dev: 'dev',
} as const

export type RefreshUserSession201User = {
  accountStatus: boolean
  /** @nullable */
  avatar: string | null
  calendarAuthorized: boolean
  email: string
  id: string
  /** @nullable */
  name: string | null
  /** @nullable */
  nickName: string | null
  passwordResetRequired: boolean
  /** @nullable */
  phone: string | null
  role: RefreshUserSession201UserRole
}

/**
 * Sessão atualizada com sucesso
 */
export type RefreshUserSession201 = {
  message: string
  sessionId: string
  user: RefreshUserSession201User
}

/**
 * Código de status HTTP 500.
 */
export type LogoutUser500StatusCode =
  (typeof LogoutUser500StatusCode)[keyof typeof LogoutUser500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogoutUser500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type LogoutUser500Name =
  (typeof LogoutUser500Name)[keyof typeof LogoutUser500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogoutUser500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type LogoutUser500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: LogoutUser500Name
  /** Código de status HTTP 500. */
  status_code: LogoutUser500StatusCode
}

/**
 * Código de status HTTP 403.
 */
export type LogoutUser403StatusCode =
  (typeof LogoutUser403StatusCode)[keyof typeof LogoutUser403StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogoutUser403StatusCode = {
  NUMBER_403: 403,
} as const

/**
 * Nome fixo do erro.
 */
export type LogoutUser403Name =
  (typeof LogoutUser403Name)[keyof typeof LogoutUser403Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogoutUser403Name = {
  ForbiddenError: 'ForbiddenError',
} as const

/**
 * Schema to represent Forbidden errors (HTTP 403)
 */
export type LogoutUser403 = {
  /** Ação recomendada para acessar o recurso. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando acesso proibido. */
  message: string
  /** Nome fixo do erro. */
  name: LogoutUser403Name
  /** Código de status HTTP 403. */
  status_code: LogoutUser403StatusCode
}

/**
 * Código de status HTTP 401.
 */
export type LogoutUser401StatusCode =
  (typeof LogoutUser401StatusCode)[keyof typeof LogoutUser401StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogoutUser401StatusCode = {
  NUMBER_401: 401,
} as const

/**
 * Nome fixo do erro.
 */
export type LogoutUser401Name =
  (typeof LogoutUser401Name)[keyof typeof LogoutUser401Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogoutUser401Name = {
  UnauthorizedError: 'UnauthorizedError',
} as const

/**
 * Schema to represent Unauthorized errors (HTTP 401)
 */
export type LogoutUser401 = {
  /** Ação recomendada para a autenticação. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que o acesso não está autorizado. */
  message: string
  /** Nome fixo do erro. */
  name: LogoutUser401Name
  /** Código de status HTTP 401. */
  status_code: LogoutUser401StatusCode
}

/**
 * Código de status HTTP 400.
 */
export type LogoutUser400StatusCode =
  (typeof LogoutUser400StatusCode)[keyof typeof LogoutUser400StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogoutUser400StatusCode = {
  NUMBER_400: 400,
} as const

/**
 * Nome fixo do erro.
 */
export type LogoutUser400Name =
  (typeof LogoutUser400Name)[keyof typeof LogoutUser400Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogoutUser400Name = {
  BadRequestError: 'BadRequestError',
} as const

/**
 * Schema to represent Bad Request errors (HTTP 400)
 */
export type LogoutUser400 = {
  /** Ação recomendada para corrigir a requisição. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando que a requisição é inválida. */
  message: string
  /** Nome fixo do erro. */
  name: LogoutUser400Name
  /** Código de status HTTP 400. */
  status_code: LogoutUser400StatusCode
}

/**
 * Usuário desconectado com sucesso
 */
export type LogoutUser200 = {
  message: string
}

/**
 * Código de status HTTP 500.
 */
export type LoginUserGoogleCallback500StatusCode =
  (typeof LoginUserGoogleCallback500StatusCode)[keyof typeof LoginUserGoogleCallback500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginUserGoogleCallback500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type LoginUserGoogleCallback500Name =
  (typeof LoginUserGoogleCallback500Name)[keyof typeof LoginUserGoogleCallback500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginUserGoogleCallback500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type LoginUserGoogleCallback500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: LoginUserGoogleCallback500Name
  /** Código de status HTTP 500. */
  status_code: LoginUserGoogleCallback500StatusCode
}

/**
 * Código de status HTTP 422.
 */
export type LoginUserGoogleCallback422StatusCode =
  (typeof LoginUserGoogleCallback422StatusCode)[keyof typeof LoginUserGoogleCallback422StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginUserGoogleCallback422StatusCode = {
  NUMBER_422: 422,
} as const

/**
 * Nome fixo do erro.
 */
export type LoginUserGoogleCallback422Name =
  (typeof LoginUserGoogleCallback422Name)[keyof typeof LoginUserGoogleCallback422Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginUserGoogleCallback422Name = {
  UnprocessableEntityError: 'UnprocessableEntityError',
} as const

export type LoginUserGoogleCallback422DetailsItem = {
  /** Mensagem de validação para o campo. */
  message: string
  /** Caminho para o campo com erro. */
  path: string[]
}

/**
 * Schema to represent Unprocessable Entity errors (HTTP 422)
 */
export type LoginUserGoogleCallback422 = {
  /** Ação recomendada para corrigir os dados enviados. */
  action: string
  /** Detalhes adicionais sobre os erros de validação. */
  details?: LoginUserGoogleCallback422DetailsItem[]
  /** Mensagem indicando que a entidade não pôde ser processada. */
  message: string
  /** Nome fixo do erro. */
  name: LoginUserGoogleCallback422Name
  /** Código de status HTTP 422. */
  status_code: LoginUserGoogleCallback422StatusCode
}

/**
 * Redireciona para o frontend após configurar cookies de sessão
 * @nullable
 */
export type LoginUserGoogleCallback302 =
  | (typeof LoginUserGoogleCallback302)[keyof typeof LoginUserGoogleCallback302]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginUserGoogleCallback302 = {
  null: 'null',
} as const

export type LoginUserGoogleCallbackParams = {
  /**
   * Código de autorização do Google
   */
  code?: string
  /**
   * Escopos autorizados pelo usuário
   */
  scope?: string
  /**
   * Índice da conta Google usada na autenticação
   */
  authuser?: string
  /**
   * Tipo de prompt utilizado no login
   */
  prompt?: string
  /**
   * Valor usado para proteção contra CSRF
   */
  state?: string
}

/**
 * Código de status HTTP 500.
 */
export type LoginUserGoogle500StatusCode =
  (typeof LoginUserGoogle500StatusCode)[keyof typeof LoginUserGoogle500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginUserGoogle500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type LoginUserGoogle500Name =
  (typeof LoginUserGoogle500Name)[keyof typeof LoginUserGoogle500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginUserGoogle500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type LoginUserGoogle500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: LoginUserGoogle500Name
  /** Código de status HTTP 500. */
  status_code: LoginUserGoogle500StatusCode
}

/**
 * Redirecionamento para o Google OAuth
 * @nullable
 */
export type LoginUserGoogle302 =
  | (typeof LoginUserGoogle302)[keyof typeof LoginUserGoogle302]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginUserGoogle302 = {
  null: 'null',
} as const

/**
 * Código de status HTTP 500.
 */
export type ServerHealthCheck500StatusCode =
  (typeof ServerHealthCheck500StatusCode)[keyof typeof ServerHealthCheck500StatusCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServerHealthCheck500StatusCode = {
  NUMBER_500: 500,
} as const

/**
 * Nome fixo do erro.
 */
export type ServerHealthCheck500Name =
  (typeof ServerHealthCheck500Name)[keyof typeof ServerHealthCheck500Name]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServerHealthCheck500Name = {
  InternalServerError: 'InternalServerError',
} as const

/**
 * Schema to represent Internal Server errors (HTTP 500)
 */
export type ServerHealthCheck500 = {
  /** Ação recomendada para lidar com o erro interno. */
  action: string
  /** Detalhes adicionais sobre o erro. */
  details?: unknown
  /** Mensagem indicando um erro interno no servidor. */
  message: string
  /** Nome fixo do erro. */
  name: ServerHealthCheck500Name
  /** Código de status HTTP 500. */
  status_code: ServerHealthCheck500StatusCode
}

/**
 * Server health check
 */
export type ServerHealthCheck200 = {
  message: string
}
