/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * BBZ App Backend API
 * API documentation for BBZ App Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key, SWRConfiguration } from 'swr'
import useSwr from 'swr'
import type { SWRMutationConfiguration } from 'swr/mutation'
import useSWRMutation from 'swr/mutation'
import { customFetch } from '../../mutator/custom-fetch'
import type {
  CreateRoom201,
  CreateRoom400,
  CreateRoom401,
  CreateRoom403,
  CreateRoom409,
  CreateRoom422,
  CreateRoom500,
  CreateRoomBody,
  DeleteRoom200,
  DeleteRoom400,
  DeleteRoom401,
  DeleteRoom403,
  DeleteRoom404,
  DeleteRoom422,
  DeleteRoom500,
  GetRoom200,
  GetRoom400,
  GetRoom401,
  GetRoom403,
  GetRoom404,
  GetRoom422,
  GetRoom500,
  ListRooms200,
  ListRooms400,
  ListRooms401,
  ListRooms403,
  ListRooms422,
  ListRooms500,
  ListRoomsParams,
  OpenDoor200,
  OpenDoor400,
  OpenDoor401,
  OpenDoor403,
  OpenDoor404,
  OpenDoor422,
  OpenDoor500,
  OpenDoorParams,
  UpdateRoom200,
  UpdateRoom400,
  UpdateRoom401,
  UpdateRoom403,
  UpdateRoom404,
  UpdateRoom409,
  UpdateRoom422,
  UpdateRoom500,
  UpdateRoomBody,
} from '../bBZAppBackendAPI.schemas'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Este endpoint permite criar uma nova sala no sistema com as seguintes características:

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo de criação**:
  1. Cria o registro de sala com os dados fornecidos
  2. Retorna a sala criada com seus dados completos
* **Resposta**: Retorna a sala criada com seu ID e status

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Criar uma nova sala
 */
export type createRoomResponse = {
  data: CreateRoom201
  status: number
  headers: Headers
}

export const getCreateRoomUrl = () => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room`
}

export const createRoom = async (
  createRoomBody: CreateRoomBody,
  options?: RequestInit,
): Promise<createRoomResponse> => {
  return customFetch<Promise<createRoomResponse>>(getCreateRoomUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRoomBody),
  })
}

export const getCreateRoomMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: CreateRoomBody },
  ): Promise<createRoomResponse> => {
    return createRoom(arg, options)
  }
}
export const getCreateRoomMutationKey = () =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/room`] as const

export type CreateRoomMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRoom>>
>
export type CreateRoomMutationError =
  | CreateRoom400
  | CreateRoom401
  | CreateRoom403
  | CreateRoom409
  | CreateRoom422
  | CreateRoom500

/**
 * @summary Criar uma nova sala
 */
export const useCreateRoom = <
  TError =
    | CreateRoom400
    | CreateRoom401
    | CreateRoom403
    | CreateRoom409
    | CreateRoom422
    | CreateRoom500,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createRoom>>,
    TError,
    Key,
    CreateRoomBody,
    Awaited<ReturnType<typeof createRoom>>
  > & { swrKey?: string }
  request?: SecondParameter<typeof customFetch>
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateRoomMutationKey()
  const swrFn = getCreateRoomMutationFetcher(requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite listar salas com filtros e paginação.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Recursos de busca**:
  1. Filtragem por termo de busca (name e description)
  2. Filtragem por status de ativação (isActive)
  3. Filtragem por faixa de capacidade
  4. Paginação com controle de página atual e tamanho da página
* **Resposta**: Retorna lista de salas paginada com metadados de paginação

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Permite acesso aos perfis 'admin', 'dev' e 'user'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Listar salas com filtros e paginação
 */
export type listRoomsResponse = {
  data: ListRooms200
  status: number
  headers: Headers
}

export const getListRoomsUrl = (params?: ListRoomsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room`
}

export const listRooms = async (
  params?: ListRoomsParams,
  options?: RequestInit,
): Promise<listRoomsResponse> => {
  return customFetch<Promise<listRoomsResponse>>(getListRoomsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getListRoomsKey = (params?: ListRoomsParams) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room`,
    ...(params ? [params] : []),
  ] as const

export type ListRoomsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listRooms>>
>
export type ListRoomsQueryError =
  | ListRooms400
  | ListRooms401
  | ListRooms403
  | ListRooms422
  | ListRooms500

/**
 * @summary Listar salas com filtros e paginação
 */
export const useListRooms = <
  TError =
    | ListRooms400
    | ListRooms401
    | ListRooms403
    | ListRooms422
    | ListRooms500,
>(
  params?: ListRoomsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof listRooms>>, TError> & {
      swrKey?: Key
      enabled?: boolean
    }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getListRoomsKey(params) : null))
  const swrFn = () => listRooms(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite excluir uma sala específica permanentemente.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo**:
  1. Valida o ID da sala a ser excluída
  2. Verifica se a sala existe no banco de dados
  3. Exclui permanentemente a sala (hard delete)
  4. Retorna mensagem de confirmação

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Excluir uma sala
 */
export type deleteRoomResponse = {
  data: DeleteRoom200
  status: number
  headers: Headers
}

export const getDeleteRoomUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room/${id}`
}

export const deleteRoom = async (
  id: string,
  options?: RequestInit,
): Promise<deleteRoomResponse> => {
  return customFetch<Promise<deleteRoomResponse>>(getDeleteRoomUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteRoomMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<deleteRoomResponse> => {
    return deleteRoom(id, options)
  }
}
export const getDeleteRoomMutationKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/room/${id}`] as const

export type DeleteRoomMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRoom>>
>
export type DeleteRoomMutationError =
  | DeleteRoom400
  | DeleteRoom401
  | DeleteRoom403
  | DeleteRoom404
  | DeleteRoom422
  | DeleteRoom500

/**
 * @summary Excluir uma sala
 */
export const useDeleteRoom = <
  TError =
    | DeleteRoom400
    | DeleteRoom401
    | DeleteRoom403
    | DeleteRoom404
    | DeleteRoom422
    | DeleteRoom500,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteRoom>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteRoom>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteRoomMutationKey(id)
  const swrFn = getDeleteRoomMutationFetcher(id, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite obter os detalhes completos de uma sala específica.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo**:
  1. Valida o ID da sala a ser consultada
  2. Verifica se a sala existe no banco de dados
  3. Retorna os detalhes completos da sala

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Permite acesso aos perfis 'admin', 'dev' e 'user'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Obter detalhes de uma sala
 */
export type getRoomResponse = {
  data: GetRoom200
  status: number
  headers: Headers
}

export const getGetRoomUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room/${id}`
}

export const getRoom = async (
  id: string,
  options?: RequestInit,
): Promise<getRoomResponse> => {
  return customFetch<Promise<getRoomResponse>>(getGetRoomUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetRoomKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/room/${id}`] as const

export type GetRoomQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRoom>>
>
export type GetRoomQueryError =
  | GetRoom400
  | GetRoom401
  | GetRoom403
  | GetRoom404
  | GetRoom422
  | GetRoom500

/**
 * @summary Obter detalhes de uma sala
 */
export const useGetRoom = <
  TError =
    | GetRoom400
    | GetRoom401
    | GetRoom403
    | GetRoom404
    | GetRoom422
    | GetRoom500,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getRoom>>, TError> & {
      swrKey?: Key
      enabled?: boolean
    }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!id
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetRoomKey(id) : null))
  const swrFn = () => getRoom(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  )

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite atualizar parcialmente os dados de uma sala específica por meio de um PATCH.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Restrito a usuários com perfil 'admin' ou 'dev'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Atualização parcial**: Implementa o conceito de PATCH, atualizando apenas os campos enviados na requisição.
* **Processo**:
  1. Valida o ID da sala a ser atualizada
  2. Verifica se a sala existe no banco de dados
  3. Aplica apenas as alterações enviadas no corpo da requisição
  4. Retorna a sala com os dados atualizados

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserRole`: Restringe acesso aos perfis 'admin' e 'dev'
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Atualizar dados parciais de uma sala
 */
export type updateRoomResponse = {
  data: UpdateRoom200
  status: number
  headers: Headers
}

export const getUpdateRoomUrl = (id: string) => {
  return `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room/${id}`
}

export const updateRoom = async (
  id: string,
  updateRoomBody: UpdateRoomBody,
  options?: RequestInit,
): Promise<updateRoomResponse> => {
  return customFetch<Promise<updateRoomResponse>>(getUpdateRoomUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateRoomBody),
  })
}

export const getUpdateRoomMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (
    _: Key,
    { arg }: { arg: UpdateRoomBody },
  ): Promise<updateRoomResponse> => {
    return updateRoom(id, arg, options)
  }
}
export const getUpdateRoomMutationKey = (id: string) =>
  [`${process.env.NEXT_PUBLIC_API_URL}/v1/private/room/${id}`] as const

export type UpdateRoomMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRoom>>
>
export type UpdateRoomMutationError =
  | UpdateRoom400
  | UpdateRoom401
  | UpdateRoom403
  | UpdateRoom404
  | UpdateRoom409
  | UpdateRoom422
  | UpdateRoom500

/**
 * @summary Atualizar dados parciais de uma sala
 */
export const useUpdateRoom = <
  TError =
    | UpdateRoom400
    | UpdateRoom401
    | UpdateRoom403
    | UpdateRoom404
    | UpdateRoom409
    | UpdateRoom422
    | UpdateRoom500,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof updateRoom>>,
      TError,
      Key,
      UpdateRoomBody,
      Awaited<ReturnType<typeof updateRoom>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateRoomMutationKey(id)
  const swrFn = getUpdateRoomMutationFetcher(id, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
/**
 * Este endpoint permite gerar um código temporário para abrir a porta de uma sala específica, utilizando integração com a API DLOCK.

* **Segurança**: Protegido por autenticação JWT (token de sessão) e CSRF via cookie/header.
* **Autorização**: Acessível a usuários com perfil 'admin', 'dev' ou 'user'.
* **Validação de conta**: Verifica se a conta do usuário autenticado está ativa e não requer reset de senha.
* **Processo**:
  1. Valida o nome da sala a ser aberta
  2. Verifica se a sala existe no banco de dados
  3. Verifica se existe uma conta DLOCK cadastrada no sistema
     - Caso não exista, cria uma nova conta usando as credenciais armazenadas no ambiente
     - Verifica se o usuário com o email configurado para DLOCK existe no sistema
  4. Gerencia o token de acesso à API DLOCK automaticamente:
     - Verifica se o token está próximo de expirar (menos de 30 dias)
     - Realiza refresh automático do token quando necessário
     - Atualiza os dados da conta no banco de dados
  5. Consulta a API DLOCK para obter a lista de fechaduras cadastradas
  6. Identifica a fechadura correspondente à sala solicitada através do nome normalizado
  7. Gera um código temporário de acesso através da API DLOCK:
     - Se a solicitação ocorrer antes dos últimos 10 minutos da hora, gera um código válido por 1 hora
     - Se a solicitação ocorrer nos últimos 10 minutos da hora, gera um código válido por 2 horas
  8. Formata a data de expiração no fuso horário de São Paulo
  9. Retorna o código de acesso temporário e informações de expiração

**Middlewares aplicados**:
- `verifyJWT`: Valida o token JWT e extrai os dados do usuário autenticado
- `validateUserAccount`: Verifica se a conta do usuário autenticado está ativa
 * @summary Gerar código para abertura de porta de uma sala
 */
export type openDoorResponse = {
  data: OpenDoor200
  status: number
  headers: Headers
}

export const getOpenDoorUrl = (params: OpenDoorParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  return normalizedParams.size
    ? `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room/open-door?${normalizedParams.toString()}`
    : `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room/open-door`
}

export const openDoor = async (
  params: OpenDoorParams,
  options?: RequestInit,
): Promise<openDoorResponse> => {
  return customFetch<Promise<openDoorResponse>>(getOpenDoorUrl(params), {
    ...options,
    method: 'POST',
  })
}

export const getOpenDoorMutationFetcher = (
  params: OpenDoorParams,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<openDoorResponse> => {
    return openDoor(params, options)
  }
}
export const getOpenDoorMutationKey = (params: OpenDoorParams) =>
  [
    `${process.env.NEXT_PUBLIC_API_URL}/v1/private/room/open-door`,
    ...(params ? [params] : []),
  ] as const

export type OpenDoorMutationResult = NonNullable<
  Awaited<ReturnType<typeof openDoor>>
>
export type OpenDoorMutationError =
  | OpenDoor400
  | OpenDoor401
  | OpenDoor403
  | OpenDoor404
  | OpenDoor422
  | OpenDoor500

/**
 * @summary Gerar código para abertura de porta de uma sala
 */
export const useOpenDoor = <
  TError =
    | OpenDoor400
    | OpenDoor401
    | OpenDoor403
    | OpenDoor404
    | OpenDoor422
    | OpenDoor500,
>(
  params: OpenDoorParams,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof openDoor>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof openDoor>>
    > & { swrKey?: string }
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getOpenDoorMutationKey(params)
  const swrFn = getOpenDoorMutationFetcher(params, requestOptions)

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query,
  }
}
